// Code generated by internal/compiler/astgen; DO NOT EDIT.
//go:generate go run flag-lang/internal/compiler/astgen

package compiler

import (
	flagrt "flag-lang/runtime"
)

func compiler__parse_error_arity_3(line flagrt.Value, col flagrt.Value, msg flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			flagrt.Throw(flagrt.NewString(flagrt.Str("parse error at ", line, ":", col, ": ", msg)))
			return flagrt.NilValue()
		}()
	}()
}

func compiler__parse_error_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 3 {
		panic("compiler__parse_error expects exactly 3 arguments")
	}
	return compiler__parse_error_arity_3(args[0], args[1], args[2])
}

func compiler__token_line_arity_1(tok flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return flagrt.Call(astflagKw_line, tok)
	}()
}

func compiler__token_line_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__token_line expects exactly 1 arguments")
	}
	return compiler__token_line_arity_1(args[0])
}

func compiler__token_col_arity_1(tok flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return flagrt.Call(astflagKw_offset, tok)
	}()
}

func compiler__token_col_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__token_col expects exactly 1 arguments")
	}
	return compiler__token_col_arity_1(args[0])
}

func compiler__make_parser_arity_1(in flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return flagrt.NewMap(astflagKw_in, in, astflagKw_la, flagrt.Call(async__atom, astflagKw_none), astflagKw_last, flagrt.Call(async__atom, flagrt.NilValue()))
	}()
}

func compiler__make_parser_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__make_parser expects exactly 1 arguments")
	}
	return compiler__make_parser_arity_1(args[0])
}

func compiler__peek_arity_1(p flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			var la = flagrt.Call(async__deref, flagrt.Call(astflagKw_la, p))
			return func() flagrt.Value {
				if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(astflagKw_none, la))) {
					return func() flagrt.Value {
						var t = flagrt.Call(async__channel_receive, flagrt.Call(astflagKw_in, p))
						return func() flagrt.Value {
							if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsNil(t))) {
								return func() flagrt.Value {
									_ = flagrt.Call(async__reset_bang, flagrt.Call(astflagKw_la, p), astflagKw_eof)
									return astflagKw_eof
								}()
							}
							return func() flagrt.Value {
								_ = flagrt.Call(async__reset_bang, flagrt.Call(astflagKw_last, p), t)
								_ = flagrt.Call(async__reset_bang, flagrt.Call(astflagKw_la, p), t)
								return t
							}()
						}()
					}()
				}
				return la
			}()
		}()
	}()
}

func compiler__peek_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__peek expects exactly 1 arguments")
	}
	return compiler__peek_arity_1(args[0])
}

func compiler__next_tok_arity_1(p flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			var t = flagrt.Call(compiler__peek, p)
			_ = flagrt.Call(async__reset_bang, flagrt.Call(astflagKw_la, p), astflagKw_none)
			return t
		}()
	}()
}

func compiler__next_tok_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__next_tok expects exactly 1 arguments")
	}
	return compiler__next_tok_arity_1(args[0])
}

func compiler__eof_line_col_arity_1(p flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			var last = flagrt.Call(async__deref, flagrt.Call(astflagKw_last, p))
			return func() flagrt.Value {
				if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsNil(last))) {
					return astflagVec
				}
				return flagrt.NewArray(flagrt.Call(astflagKw_line, last), flagrt.Add(flagrt.Call(astflagKw_offset, last), flagrt.NewLong(int64(flagrt.Count(flagrt.Call(astflagKw_token, last))))))
			}()
		}()
	}()
}

func compiler__eof_line_col_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__eof_line_col expects exactly 1 arguments")
	}
	return compiler__eof_line_col_arity_1(args[0])
}

func compiler__starts_with_char_q_arity_2(token flagrt.Value, ch flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			if !(flagrt.IsTruthy(func() flagrt.Value {
				if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(token))) {
					return flagrt.NewBool(false)
				}
				return flagrt.NewBool(true)
			}())) {
				return func() flagrt.Value {
					if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(token))) {
						return flagrt.NewBool(false)
					}
					return flagrt.NewBool(true)
				}()
			}
			return flagrt.NewBool(flagrt.Eq(ch, flagrt.First(flagrt.Seq(token))))
		}()
	}()
}

func compiler__starts_with_char_q_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 2 {
		panic("compiler__starts_with_char_q expects exactly 2 arguments")
	}
	return compiler__starts_with_char_q_arity_2(args[0], args[1])
}

func compiler__ends_with_char_q_arity_2(token flagrt.Value, ch flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			if !(flagrt.IsTruthy(func() flagrt.Value {
				if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(token))) {
					return flagrt.NewBool(false)
				}
				return flagrt.NewBool(true)
			}())) {
				return func() flagrt.Value {
					if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(token))) {
						return flagrt.NewBool(false)
					}
					return flagrt.NewBool(true)
				}()
			}
			return flagrt.NewBool(flagrt.Eq(ch, flagrt.Last(flagrt.Seq(token))))
		}()
	}()
}

func compiler__ends_with_char_q_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 2 {
		panic("compiler__ends_with_char_q expects exactly 2 arguments")
	}
	return compiler__ends_with_char_q_arity_2(args[0], args[1])
}

func compiler__contains_float_mark_q_arity_1(token flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			var cs = flagrt.Seq(token)
			for {
				__loopResult := func() flagrt.Value {
					return func() flagrt.Value {
						if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(cs))) {
							return flagrt.NewBool(false)
						}
						return func() flagrt.Value {
							var ch = flagrt.First(cs)
							return func() flagrt.Value {
								if flagrt.IsTruthy(func() flagrt.Value {
									if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(ch, flagrt.NewString(".")))) {
										return flagrt.NewBool(flagrt.Eq(ch, flagrt.NewString(".")))
									}
									if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(ch, flagrt.NewString("e")))) {
										return flagrt.NewBool(flagrt.Eq(ch, flagrt.NewString("e")))
									}
									return flagrt.NewBool(flagrt.Eq(ch, flagrt.NewString("E")))
								}()) {
									return flagrt.NewBool(true)
								}
								return flagrt.NewRecur(flagrt.Rest(cs))
							}()
						}()
					}()
				}()
				if __recurValues, __isRecur := flagrt.UnwrapRecur(__loopResult); __isRecur {
					if len(__recurValues) != 1 {
						panic("internal error: recur arity mismatch")
					}
					cs = __recurValues[0]
					continue
				}
				return __loopResult
			}
		}()
	}()
}

func compiler__contains_float_mark_q_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__contains_float_mark_q expects exactly 1 arguments")
	}
	return compiler__contains_float_mark_q_arity_1(args[0])
}

func compiler__slash_count_arity_1(token flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			var cs = flagrt.Seq(token)
			var n = flagrt.NewLong(0)
			for {
				__loopResult := func() flagrt.Value {
					return func() flagrt.Value {
						if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(cs))) {
							return n
						}
						return flagrt.NewRecur(flagrt.Rest(cs), func() flagrt.Value {
							if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(flagrt.NewString("/"), flagrt.First(cs)))) {
								return flagrt.Add(n, flagrt.NewLong(1))
							}
							return n
						}())
					}()
				}()
				if __recurValues, __isRecur := flagrt.UnwrapRecur(__loopResult); __isRecur {
					if len(__recurValues) != 2 {
						panic("internal error: recur arity mismatch")
					}
					cs = __recurValues[0]
					n = __recurValues[1]
					continue
				}
				return __loopResult
			}
		}()
	}()
}

func compiler__slash_count_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__slash_count expects exactly 1 arguments")
	}
	return compiler__slash_count_arity_1(args[0])
}

func compiler__split_once_arity_2(token flagrt.Value, sep flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			var cs = flagrt.Seq(token)
			var left = astflagStr_
			for {
				__loopResult := func() flagrt.Value {
					return func() flagrt.Value {
						if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(cs))) {
							return flagrt.NilValue()
						}
						return func() flagrt.Value {
							if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(sep, flagrt.First(cs)))) {
								return func() flagrt.Value {
									var r = flagrt.Rest(cs)
									var right = astflagStr_
									for {
										__loopResult := func() flagrt.Value {
											return func() flagrt.Value {
												if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(r))) {
													return flagrt.NewArray(left, right)
												}
												return flagrt.NewRecur(flagrt.Rest(r), flagrt.NewString(flagrt.Str(right, flagrt.First(r))))
											}()
										}()
										if __recurValues, __isRecur := flagrt.UnwrapRecur(__loopResult); __isRecur {
											if len(__recurValues) != 2 {
												panic("internal error: recur arity mismatch")
											}
											r = __recurValues[0]
											right = __recurValues[1]
											continue
										}
										return __loopResult
									}
								}()
							}
							return flagrt.NewRecur(flagrt.Rest(cs), flagrt.NewString(flagrt.Str(left, flagrt.First(cs))))
						}()
					}()
				}()
				if __recurValues, __isRecur := flagrt.UnwrapRecur(__loopResult); __isRecur {
					if len(__recurValues) != 2 {
						panic("internal error: recur arity mismatch")
					}
					cs = __recurValues[0]
					left = __recurValues[1]
					continue
				}
				return __loopResult
			}
		}()
	}()
}

func compiler__split_once_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 2 {
		panic("compiler__split_once expects exactly 2 arguments")
	}
	return compiler__split_once_arity_2(args[0], args[1])
}

func compiler__unescape_char_arity_1(ch flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(ch, flagrt.NewString("n")))) {
				return astflagStr___2
			}
			return func() flagrt.Value {
				if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(ch, flagrt.NewString("t")))) {
					return astflagStr___1
				}
				return func() flagrt.Value {
					if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(ch, flagrt.NewString("r")))) {
						return astflagStr__
					}
					return func() flagrt.Value {
						if flagrt.IsTruthy(flagrt.NewBool(true)) {
							return ch
						}
						return flagrt.NilValue()
					}()
				}()
			}()
		}()
	}()
}

func compiler__unescape_char_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__unescape_char expects exactly 1 arguments")
	}
	return compiler__unescape_char_arity_1(args[0])
}

func compiler__unquote_go_string_arity_1(token flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			var chars = flagrt.Seq(token)
			var n = flagrt.NewLong(int64(flagrt.Count(chars)))
			return func() flagrt.Value {
				if flagrt.IsTruthy(func() flagrt.Value {
					if flagrt.Lt(n, flagrt.NewLong(2)) {
						return flagrt.NewBool(flagrt.Lt(n, flagrt.NewLong(2)))
					}
					if flagrt.IsTruthy(func() flagrt.Value {
						if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(flagrt.NewString("\""), flagrt.First(chars)))) {
							return flagrt.NewBool(false)
						}
						return flagrt.NewBool(true)
					}()) {
						return func() flagrt.Value {
							if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(flagrt.NewString("\""), flagrt.First(chars)))) {
								return flagrt.NewBool(false)
							}
							return flagrt.NewBool(true)
						}()
					}
					return func() flagrt.Value {
						if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(flagrt.NewString("\""), flagrt.Last(chars)))) {
							return flagrt.NewBool(false)
						}
						return flagrt.NewBool(true)
					}()
				}()) {
					return astflagKw_error
				}
				return func() flagrt.Value {
					var remaining = flagrt.Take(flagrt.Sub(n, flagrt.NewLong(2)), flagrt.Drop(flagrt.NewLong(1), chars))
					var out = astflagStr_
					var escaped = flagrt.NewBool(false)
					for {
						__loopResult := func() flagrt.Value {
							return func() flagrt.Value {
								if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(remaining))) {
									return func() flagrt.Value {
										if flagrt.IsTruthy(escaped) {
											return astflagKw_error
										}
										return out
									}()
								}
								return func() flagrt.Value {
									var ch = flagrt.First(remaining)
									return func() flagrt.Value {
										if flagrt.IsTruthy(escaped) {
											return flagrt.NewRecur(flagrt.Rest(remaining), flagrt.NewString(flagrt.Str(out, flagrt.Call(compiler__unescape_char, ch))), flagrt.NewBool(false))
										}
										return func() flagrt.Value {
											if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(ch, flagrt.NewString("\\")))) {
												return flagrt.NewRecur(flagrt.Rest(remaining), out, flagrt.NewBool(true))
											}
											return func() flagrt.Value {
												if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(ch, flagrt.NewString("\"")))) {
													return astflagKw_error
												}
												return flagrt.NewRecur(flagrt.Rest(remaining), flagrt.NewString(flagrt.Str(out, ch)), flagrt.NewBool(false))
											}()
										}()
									}()
								}()
							}()
						}()
						if __recurValues, __isRecur := flagrt.UnwrapRecur(__loopResult); __isRecur {
							if len(__recurValues) != 3 {
								panic("internal error: recur arity mismatch")
							}
							remaining = __recurValues[0]
							out = __recurValues[1]
							escaped = __recurValues[2]
							continue
						}
						return __loopResult
					}
				}()
			}()
		}()
	}()
}

func compiler__unquote_go_string_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__unquote_go_string expects exactly 1 arguments")
	}
	return compiler__unquote_go_string_arity_1(args[0])
}

func compiler__string_token_q_arity_1(tok flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return flagrt.Call(compiler__starts_with_char_q, flagrt.Call(astflagKw_token, tok), astflagStr___3)
	}()
}

func compiler__string_token_q_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__string_token_q expects exactly 1 arguments")
	}
	return compiler__string_token_q_arity_1(args[0])
}

func compiler__strip_edges_arity_3(token flagrt.Value, left flagrt.Value, right flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			var chars = flagrt.Seq(token)
			var n = flagrt.NewLong(int64(flagrt.Count(chars)))
			return func() flagrt.Value {
				if flagrt.Le(n, flagrt.Add(left, right)) {
					return astflagStr_
				}
				return func() flagrt.Value {
					var remaining = flagrt.Take(flagrt.Sub(flagrt.Sub(n, left), right), flagrt.Drop(left, chars))
					var out = astflagStr_
					for {
						__loopResult := func() flagrt.Value {
							return func() flagrt.Value {
								if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(remaining))) {
									return out
								}
								return flagrt.NewRecur(flagrt.Rest(remaining), flagrt.NewString(flagrt.Str(out, flagrt.First(remaining))))
							}()
						}()
						if __recurValues, __isRecur := flagrt.UnwrapRecur(__loopResult); __isRecur {
							if len(__recurValues) != 2 {
								panic("internal error: recur arity mismatch")
							}
							remaining = __recurValues[0]
							out = __recurValues[1]
							continue
						}
						return __loopResult
					}
				}()
			}()
		}()
	}()
}

func compiler__strip_edges_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 3 {
		panic("compiler__strip_edges expects exactly 3 arguments")
	}
	return compiler__strip_edges_arity_3(args[0], args[1], args[2])
}

func compiler__triple_quoted_q_arity_1(token flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			var chars = flagrt.Seq(token)
			var n = flagrt.NewLong(int64(flagrt.Count(chars)))
			return func() flagrt.Value {
				if !(flagrt.Ge(n, flagrt.NewLong(6))) {
					return flagrt.NewBool(flagrt.Ge(n, flagrt.NewLong(6)))
				}
				if !(flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(flagrt.NewString("\""), flagrt.Call(flagrt.BuiltinFunction("nth"), chars, flagrt.NewLong(0)))))) {
					return flagrt.NewBool(flagrt.Eq(flagrt.NewString("\""), flagrt.Call(flagrt.BuiltinFunction("nth"), chars, flagrt.NewLong(0))))
				}
				if !(flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(flagrt.NewString("\""), flagrt.Call(flagrt.BuiltinFunction("nth"), chars, flagrt.NewLong(1)))))) {
					return flagrt.NewBool(flagrt.Eq(flagrt.NewString("\""), flagrt.Call(flagrt.BuiltinFunction("nth"), chars, flagrt.NewLong(1))))
				}
				return flagrt.NewBool(flagrt.Eq(flagrt.NewString("\""), flagrt.Call(flagrt.BuiltinFunction("nth"), chars, flagrt.NewLong(2))))
			}()
		}()
	}()
}

func compiler__triple_quoted_q_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__triple_quoted_q expects exactly 1 arguments")
	}
	return compiler__triple_quoted_q_arity_1(args[0])
}

func compiler__triple_quoted_closed_q_arity_1(token flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			var chars = flagrt.Seq(token)
			var n = flagrt.NewLong(int64(flagrt.Count(chars)))
			return func() flagrt.Value {
				if !(flagrt.Ge(n, flagrt.NewLong(6))) {
					return flagrt.NewBool(flagrt.Ge(n, flagrt.NewLong(6)))
				}
				if !(flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(flagrt.NewString("\""), flagrt.Call(flagrt.BuiltinFunction("nth"), chars, flagrt.Sub(n, flagrt.NewLong(1))))))) {
					return flagrt.NewBool(flagrt.Eq(flagrt.NewString("\""), flagrt.Call(flagrt.BuiltinFunction("nth"), chars, flagrt.Sub(n, flagrt.NewLong(1)))))
				}
				if !(flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(flagrt.NewString("\""), flagrt.Call(flagrt.BuiltinFunction("nth"), chars, flagrt.Sub(n, flagrt.NewLong(2))))))) {
					return flagrt.NewBool(flagrt.Eq(flagrt.NewString("\""), flagrt.Call(flagrt.BuiltinFunction("nth"), chars, flagrt.Sub(n, flagrt.NewLong(2)))))
				}
				return flagrt.NewBool(flagrt.Eq(flagrt.NewString("\""), flagrt.Call(flagrt.BuiltinFunction("nth"), chars, flagrt.Sub(n, flagrt.NewLong(3)))))
			}()
		}()
	}()
}

func compiler__triple_quoted_closed_q_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__triple_quoted_closed_q expects exactly 1 arguments")
	}
	return compiler__triple_quoted_closed_q_arity_1(args[0])
}

func compiler__parse_char_token_arity_3(token flagrt.Value, line flagrt.Value, col flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			var text = flagrt.Call(flagrt.BuiltinFunction("subs"), token, flagrt.NewLong(1))
			return func() flagrt.Value {
				if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(text, flagrt.NewString("space")))) {
					return flagrt.NewMap(astflagKw_kind, astflagKw_char, astflagKw_value, flagrt.NewString(" "), astflagKw_line, line, astflagKw_col, col)
				}
				return func() flagrt.Value {
					if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(text, flagrt.NewString("newline")))) {
						return flagrt.NewMap(astflagKw_kind, astflagKw_char, astflagKw_value, flagrt.NewString("\n"), astflagKw_line, line, astflagKw_col, col)
					}
					return func() flagrt.Value {
						if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(text, flagrt.NewString("tab")))) {
							return flagrt.NewMap(astflagKw_kind, astflagKw_char, astflagKw_value, flagrt.NewString("\t"), astflagKw_line, line, astflagKw_col, col)
						}
						return func() flagrt.Value {
							if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(flagrt.NewLong(1), flagrt.NewLong(int64(flagrt.Count(flagrt.Seq(text))))))) {
								return flagrt.NewMap(astflagKw_kind, astflagKw_char, astflagKw_value, text, astflagKw_line, line, astflagKw_col, col)
							}
							return func() flagrt.Value {
								if flagrt.IsTruthy(flagrt.NewBool(true)) {
									return flagrt.Call(compiler__parse_error, line, col, astflagStr_unsupported_character_li)
								}
								return flagrt.NilValue()
							}()
						}()
					}()
				}()
			}()
		}()
	}()
}

func compiler__parse_char_token_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 3 {
		panic("compiler__parse_char_token expects exactly 3 arguments")
	}
	return compiler__parse_char_token_arity_3(args[0], args[1], args[2])
}

func compiler__signed_decimal_int_q_arity_1(token flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			if !(flagrt.IsTruthy(func() flagrt.Value {
				if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(token))) {
					return flagrt.NewBool(false)
				}
				return flagrt.NewBool(true)
			}())) {
				return func() flagrt.Value {
					if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(token))) {
						return flagrt.NewBool(false)
					}
					return flagrt.NewBool(true)
				}()
			}
			return func() flagrt.Value {
				var cs = flagrt.Seq(token)
				var idx = flagrt.NewLong(0)
				for {
					__loopResult := func() flagrt.Value {
						return func() flagrt.Value {
							if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(cs))) {
								return flagrt.NewBool(flagrt.Gt(idx, flagrt.NewLong(0)))
							}
							return func() flagrt.Value {
								var ch = flagrt.First(cs)
								return func() flagrt.Value {
									if flagrt.IsTruthy(func() flagrt.Value {
										if !(flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(idx, flagrt.NewLong(0))))) {
											return flagrt.NewBool(flagrt.Eq(idx, flagrt.NewLong(0)))
										}
										return func() flagrt.Value {
											if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(ch, flagrt.NewString("+")))) {
												return flagrt.NewBool(flagrt.Eq(ch, flagrt.NewString("+")))
											}
											return flagrt.NewBool(flagrt.Eq(ch, flagrt.NewString("-")))
										}()
									}()) {
										return func() flagrt.Value {
											if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(flagrt.Rest(cs)))) {
												return flagrt.NewBool(false)
											}
											return flagrt.NewRecur(flagrt.Rest(cs), flagrt.Add(idx, flagrt.NewLong(1)))
										}()
									}
									return func() flagrt.Value {
										if flagrt.IsTruthy(func() flagrt.Value {
											if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsNil(flagrt.Call(flagrt.GoBind_packages_LongParse, ch)))) {
												return flagrt.NewBool(false)
											}
											return flagrt.NewBool(true)
										}()) {
											return flagrt.NewRecur(flagrt.Rest(cs), flagrt.Add(idx, flagrt.NewLong(1)))
										}
										return flagrt.NewBool(false)
									}()
								}()
							}()
						}()
					}()
					if __recurValues, __isRecur := flagrt.UnwrapRecur(__loopResult); __isRecur {
						if len(__recurValues) != 2 {
							panic("internal error: recur arity mismatch")
						}
						cs = __recurValues[0]
						idx = __recurValues[1]
						continue
					}
					return __loopResult
				}
			}()
		}()
	}()
}

func compiler__signed_decimal_int_q_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__signed_decimal_int_q expects exactly 1 arguments")
	}
	return compiler__signed_decimal_int_q_arity_1(args[0])
}

func compiler__parse_atom_token_arity_1(tok flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			var token = flagrt.Call(astflagKw_token, tok)
			var line = flagrt.Call(compiler__token_line, tok)
			var col = flagrt.Call(compiler__token_col, tok)
			return func() flagrt.Value {
				if flagrt.IsTruthy(func() flagrt.Value {
					if !(flagrt.IsTruthy(flagrt.Call(compiler__starts_with_char_q, token, astflagStr___4))) {
						return flagrt.Call(compiler__starts_with_char_q, token, astflagStr___4)
					}
					return flagrt.NewBool(flagrt.Gt(flagrt.NewLong(int64(flagrt.Count(token))), flagrt.NewLong(1)))
				}()) {
					return flagrt.NewMap(astflagKw_kind, astflagKw_keyword, astflagKw_name, flagrt.Call(flagrt.BuiltinFunction("subs"), token, flagrt.NewLong(1)), astflagKw_line, line, astflagKw_col, col)
				}
				return func() flagrt.Value {
					if flagrt.IsTruthy(func() flagrt.Value {
						if !(flagrt.IsTruthy(flagrt.Call(compiler__starts_with_char_q, token, astflagStr___5))) {
							return flagrt.Call(compiler__starts_with_char_q, token, astflagStr___5)
						}
						return flagrt.NewBool(flagrt.Gt(flagrt.NewLong(int64(flagrt.Count(token))), flagrt.NewLong(1)))
					}()) {
						return flagrt.Call(compiler__parse_char_token, token, line, col)
					}
					return func() flagrt.Value {
						if flagrt.IsTruthy(func() flagrt.Value {
							if !(flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(flagrt.NewLong(1), flagrt.Call(compiler__slash_count, token))))) {
								return flagrt.NewBool(flagrt.Eq(flagrt.NewLong(1), flagrt.Call(compiler__slash_count, token)))
							}
							if !(flagrt.IsTruthy(func() flagrt.Value {
								if flagrt.IsTruthy(flagrt.Call(compiler__starts_with_char_q, token, astflagStr___6)) {
									return flagrt.NewBool(false)
								}
								return flagrt.NewBool(true)
							}())) {
								return func() flagrt.Value {
									if flagrt.IsTruthy(flagrt.Call(compiler__starts_with_char_q, token, astflagStr___6)) {
										return flagrt.NewBool(false)
									}
									return flagrt.NewBool(true)
								}()
							}
							return func() flagrt.Value {
								if flagrt.IsTruthy(flagrt.Call(compiler__ends_with_char_q, token, astflagStr___6)) {
									return flagrt.NewBool(false)
								}
								return flagrt.NewBool(true)
							}()
						}()) {
							return func() flagrt.Value {
								var parts = flagrt.Call(compiler__split_once, token, astflagStr___6)
								var numerator = flagrt.Call(flagrt.GoBind_packages_LongParse, flagrt.First(parts))
								var denominator = flagrt.Call(flagrt.GoBind_packages_LongParse, flagrt.First(flagrt.Rest(parts)))
								return func() flagrt.Value {
									if flagrt.IsTruthy(func() flagrt.Value {
										if !(flagrt.IsTruthy(func() flagrt.Value {
											if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsNil(numerator))) {
												return flagrt.NewBool(false)
											}
											return flagrt.NewBool(true)
										}())) {
											return func() flagrt.Value {
												if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsNil(numerator))) {
													return flagrt.NewBool(false)
												}
												return flagrt.NewBool(true)
											}()
										}
										return func() flagrt.Value {
											if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsNil(denominator))) {
												return flagrt.NewBool(false)
											}
											return flagrt.NewBool(true)
										}()
									}()) {
										return func() flagrt.Value {
											if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(flagrt.NewLong(0), denominator))) {
												return flagrt.Call(compiler__parse_error, line, col, astflagStr_ratio_denominator_cannot)
											}
											return flagrt.NewMap(astflagKw_kind, astflagKw_ratio, astflagKw_numerator, numerator, astflagKw_denominator, denominator, astflagKw_line, line, astflagKw_col, col)
										}()
									}
									return flagrt.NewMap(astflagKw_kind, astflagKw_symbol, astflagKw_name, token, astflagKw_line, line, astflagKw_col, col)
								}()
							}()
						}
						return func() flagrt.Value {
							if flagrt.IsTruthy(func() flagrt.Value {
								if !(flagrt.IsTruthy(flagrt.Call(compiler__ends_with_char_q, token, astflagStr_N))) {
									return flagrt.Call(compiler__ends_with_char_q, token, astflagStr_N)
								}
								return flagrt.Call(compiler__signed_decimal_int_q, flagrt.Call(flagrt.BuiltinFunction("subs"), token, flagrt.NewLong(0), flagrt.Sub(flagrt.NewLong(int64(flagrt.Count(token))), flagrt.NewLong(1))))
							}()) {
								return flagrt.NewMap(astflagKw_kind, astflagKw_bigint, astflagKw_value, flagrt.Call(flagrt.BuiltinFunction("subs"), token, flagrt.NewLong(0), flagrt.Sub(flagrt.NewLong(int64(flagrt.Count(token))), flagrt.NewLong(1))), astflagKw_line, line, astflagKw_col, col)
							}
							return func() flagrt.Value {
								if flagrt.IsTruthy(flagrt.NewBool(true)) {
									return func() flagrt.Value {
										var as_int = flagrt.Call(flagrt.GoBind_packages_LongParse, token)
										return func() flagrt.Value {
											if flagrt.IsTruthy(func() flagrt.Value {
												if !(flagrt.IsTruthy(func() flagrt.Value {
													if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsNil(as_int))) {
														return flagrt.NewBool(false)
													}
													return flagrt.NewBool(true)
												}())) {
													return func() flagrt.Value {
														if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsNil(as_int))) {
															return flagrt.NewBool(false)
														}
														return flagrt.NewBool(true)
													}()
												}
												return flagrt.Call(compiler__signed_decimal_int_q, token)
											}()) {
												return flagrt.NewMap(astflagKw_kind, astflagKw_int, astflagKw_value, as_int, astflagKw_line, line, astflagKw_col, col)
											}
											return func() flagrt.Value {
												if flagrt.IsTruthy(flagrt.Call(compiler__contains_float_mark_q, token)) {
													return func() flagrt.Value {
														var __flag_try_result flagrt.Value
														func() {
															defer func() {
																r := recover()
																if r == nil {
																	return
																}
																__flag_thrown := flagrt.PanicValue(r)
																if flagrt.CatchMatches("Exception", __flag_thrown) {
																	__flag_try_result = func() flagrt.Value {
																		var e = __flag_thrown
																		_ = e
																		return func() flagrt.Value {
																			return flagrt.NewMap(astflagKw_kind, astflagKw_symbol, astflagKw_name, token, astflagKw_line, line, astflagKw_col, col)
																		}()
																	}()
																	return
																}
																panic(r)
															}()
															__flag_try_result = func() flagrt.Value {
																return flagrt.NewMap(astflagKw_kind, astflagKw_float, astflagKw_value, flagrt.Double(flagrt.Call(flagrt.GoBind_runtime_JSONReadStr, token)), astflagKw_raw, token, astflagKw_line, line, astflagKw_col, col)
															}()
														}()
														return __flag_try_result
													}()
												}
												return flagrt.NewMap(astflagKw_kind, astflagKw_symbol, astflagKw_name, token, astflagKw_line, line, astflagKw_col, col)
											}()
										}()
									}()
								}
								return flagrt.NilValue()
							}()
						}()
					}()
				}()
			}()
		}()
	}()
}

func compiler__parse_atom_token_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__parse_atom_token expects exactly 1 arguments")
	}
	return compiler__parse_atom_token_arity_1(args[0])
}

func compiler__comment_list_q_arity_1(elements flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			if !(flagrt.IsTruthy(func() flagrt.Value {
				if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(elements))) {
					return flagrt.NewBool(false)
				}
				return flagrt.NewBool(true)
			}())) {
				return func() flagrt.Value {
					if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(elements))) {
						return flagrt.NewBool(false)
					}
					return flagrt.NewBool(true)
				}()
			}
			if !(flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(astflagKw_symbol, flagrt.Call(astflagKw_kind, flagrt.First(elements)))))) {
				return flagrt.NewBool(flagrt.Eq(astflagKw_symbol, flagrt.Call(astflagKw_kind, flagrt.First(elements))))
			}
			return flagrt.NewBool(flagrt.Eq(flagrt.NewString("comment"), flagrt.Call(astflagKw_name, flagrt.First(elements))))
		}()
	}()
}

func compiler__comment_list_q_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__comment_list_q expects exactly 1 arguments")
	}
	return compiler__comment_list_q_arity_1(args[0])
}

func compiler__collection_node_arity_3(kind flagrt.Value, elements flagrt.Value, tok flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(kind, astflagKw_map))) {
				return flagrt.NewMap(astflagKw_kind, astflagKw_map, astflagKw_entries, elements, astflagKw_line, flagrt.Call(compiler__token_line, tok), astflagKw_col, flagrt.Call(compiler__token_col, tok))
			}
			return flagrt.NewMap(astflagKw_kind, kind, astflagKw_elements, elements, astflagKw_line, flagrt.Call(compiler__token_line, tok), astflagKw_col, flagrt.Call(compiler__token_col, tok))
		}()
	}()
}

func compiler__collection_node_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 3 {
		panic("compiler__collection_node expects exactly 3 arguments")
	}
	return compiler__collection_node_arity_3(args[0], args[1], args[2])
}

func compiler__dispatch_error_arity_1(tok flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(flagrt.NewString("#"), flagrt.Call(astflagKw_token, tok)))) {
				return flagrt.Call(compiler__parse_error, flagrt.Call(compiler__token_line, tok), flagrt.Call(compiler__token_col, tok), astflagStr_unexpected_end_after__)
			}
			return flagrt.Call(compiler__parse_error, flagrt.Call(compiler__token_line, tok), flagrt.Call(compiler__token_col, tok), astflagStr_unsupported_reader_dispa)
		}()
	}()
}

func compiler__dispatch_error_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__dispatch_error expects exactly 1 arguments")
	}
	return compiler__dispatch_error_arity_1(args[0])
}

func compiler__read_string_token_arity_1(p flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			var tok = flagrt.Call(compiler__next_tok, p)
			var token = flagrt.Call(astflagKw_token, tok)
			var line = flagrt.Call(compiler__token_line, tok)
			var col = flagrt.Call(compiler__token_col, tok)
			return func() flagrt.Value {
				if flagrt.IsTruthy(flagrt.Call(compiler__triple_quoted_q, token)) {
					return func() flagrt.Value {
						if flagrt.IsTruthy(flagrt.Call(compiler__triple_quoted_closed_q, token)) {
							return flagrt.NewMap(astflagKw_kind, astflagKw_string, astflagKw_value, flagrt.Call(compiler__strip_edges, token, flagrt.NewLong(3), flagrt.NewLong(3)), astflagKw_line, line, astflagKw_col, col)
						}
						return flagrt.Call(compiler__parse_error, line, col, astflagStr_unterminated_string_lite)
					}()
				}
				return func() flagrt.Value {
					var unquoted = flagrt.Call(compiler__unquote_go_string, token)
					return func() flagrt.Value {
						if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(astflagKw_error, unquoted))) {
							return flagrt.Call(compiler__parse_error, line, col, astflagStr_unterminated_string_lite)
						}
						return flagrt.NewMap(astflagKw_kind, astflagKw_string, astflagKw_value, unquoted, astflagKw_line, line, astflagKw_col, col)
					}()
				}()
			}()
		}()
	}()
}

func compiler__read_string_token_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__read_string_token expects exactly 1 arguments")
	}
	return compiler__read_string_token_arity_1(args[0])
}

func compiler__read_expr_arity_1(p flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			var tok = flagrt.Call(compiler__peek, p)
			return func() flagrt.Value {
				if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(astflagKw_eof, tok))) {
					return func() flagrt.Value {
						var pos = flagrt.Call(compiler__eof_line_col, p)
						return flagrt.Call(compiler__parse_error, flagrt.First(pos), flagrt.First(flagrt.Rest(pos)), astflagStr_unexpected_end_of_input)
					}()
				}
				return func() flagrt.Value {
					var token = flagrt.Call(astflagKw_token, tok)
					return func() flagrt.Value {
						if flagrt.IsTruthy(func() flagrt.Value {
							if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(token, flagrt.NewString("(")))) {
								return flagrt.NewBool(flagrt.Eq(token, flagrt.NewString("(")))
							}
							if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(token, flagrt.NewString("[")))) {
								return flagrt.NewBool(flagrt.Eq(token, flagrt.NewString("[")))
							}
							if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(token, flagrt.NewString("|")))) {
								return flagrt.NewBool(flagrt.Eq(token, flagrt.NewString("|")))
							}
							if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(token, flagrt.NewString("{")))) {
								return flagrt.NewBool(flagrt.Eq(token, flagrt.NewString("{")))
							}
							return flagrt.NewBool(flagrt.Eq(token, flagrt.NewString("#{")))
						}()) {
							return func() flagrt.Value {
								var kind = func() flagrt.Value {
									if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(token, flagrt.NewString("(")))) {
										return astflagKw_list
									}
									return func() flagrt.Value {
										if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(token, flagrt.NewString("[")))) {
											return astflagKw_vector
										}
										return func() flagrt.Value {
											if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(token, flagrt.NewString("|")))) {
												return astflagKw_pipe_vector
											}
											return func() flagrt.Value {
												if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(token, flagrt.NewString("{")))) {
													return astflagKw_map
												}
												return func() flagrt.Value {
													if flagrt.IsTruthy(flagrt.NewBool(true)) {
														return astflagKw_set
													}
													return flagrt.NilValue()
												}()
											}()
										}()
									}()
								}()
								var closer = func() flagrt.Value {
									if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(token, flagrt.NewString("(")))) {
										return astflagStr___10
									}
									return func() flagrt.Value {
										if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(token, flagrt.NewString("[")))) {
											return astflagStr___9
										}
										return func() flagrt.Value {
											if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(token, flagrt.NewString("|")))) {
												return astflagStr___8
											}
											return func() flagrt.Value {
												if flagrt.IsTruthy(flagrt.NewBool(true)) {
													return astflagStr___7
												}
												return flagrt.NilValue()
											}()
										}()
									}()
								}()
								var missing = func() flagrt.Value {
									if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(token, flagrt.NewString("(")))) {
										return astflagStr_missing_closing_____3
									}
									return func() flagrt.Value {
										if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(token, flagrt.NewString("[")))) {
											return astflagStr_missing_closing_____2
										}
										return func() flagrt.Value {
											if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(token, flagrt.NewString("|")))) {
												return astflagStr_missing_closing_____1
											}
											return func() flagrt.Value {
												if flagrt.IsTruthy(flagrt.NewBool(true)) {
													return astflagStr_missing_closing____
												}
												return flagrt.NilValue()
											}()
										}()
									}()
								}()
								var open = flagrt.Call(compiler__next_tok, p)
								return func() flagrt.Value {
									var elements = astflagVec_1
									for {
										__loopResult := func() flagrt.Value {
											return func() flagrt.Value {
												var cur = flagrt.Call(compiler__peek, p)
												return func() flagrt.Value {
													if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(astflagKw_eof, cur))) {
														return flagrt.Call(compiler__parse_error, flagrt.Call(compiler__token_line, open), flagrt.Call(compiler__token_col, open), missing)
													}
													return func() flagrt.Value {
														if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(closer, flagrt.Call(astflagKw_token, cur)))) {
															return func() flagrt.Value {
																_ = flagrt.Call(compiler__next_tok, p)
																return func() flagrt.Value {
																	if flagrt.IsTruthy(func() flagrt.Value {
																		if !(flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(kind, astflagKw_list)))) {
																			return flagrt.NewBool(flagrt.Eq(kind, astflagKw_list))
																		}
																		return flagrt.Call(compiler__comment_list_q, elements)
																	}()) {
																		return flagrt.NilValue()
																	}
																	return flagrt.Call(compiler__collection_node, kind, elements, open)
																}()
															}()
														}
														return func() flagrt.Value {
															var item = compiler__read_expr_arity_1(p)
															return func() flagrt.Value {
																if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsNil(item))) {
																	return flagrt.NewRecur(elements)
																}
																return flagrt.NewRecur(flagrt.Conj(elements, item))
															}()
														}()
													}()
												}()
											}()
										}()
										if __recurValues, __isRecur := flagrt.UnwrapRecur(__loopResult); __isRecur {
											if len(__recurValues) != 1 {
												panic("internal error: recur arity mismatch")
											}
											elements = __recurValues[0]
											continue
										}
										return __loopResult
									}
								}()
							}()
						}
						return func() flagrt.Value {
							if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(token, flagrt.NewString("#(")))) {
								return func() flagrt.Value {
									var open = flagrt.Call(compiler__next_tok, p)
									return func() flagrt.Value {
										var elements = astflagVec_1
										for {
											__loopResult := func() flagrt.Value {
												return func() flagrt.Value {
													var cur = flagrt.Call(compiler__peek, p)
													return func() flagrt.Value {
														if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(astflagKw_eof, cur))) {
															return flagrt.Call(compiler__parse_error, flagrt.Call(compiler__token_line, open), flagrt.Call(compiler__token_col, open), astflagStr_missing_closing_____3)
														}
														return func() flagrt.Value {
															if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(flagrt.NewString(")"), flagrt.Call(astflagKw_token, cur)))) {
																return func() flagrt.Value {
																	_ = flagrt.Call(compiler__next_tok, p)
																	return flagrt.NewMap(astflagKw_kind, astflagKw_hash_fn, astflagKw_body, flagrt.NewMap(astflagKw_kind, astflagKw_list, astflagKw_elements, elements, astflagKw_line, flagrt.Call(compiler__token_line, open), astflagKw_col, flagrt.Call(compiler__token_col, open)), astflagKw_line, flagrt.Call(compiler__token_line, open), astflagKw_col, flagrt.Call(compiler__token_col, open))
																}()
															}
															return func() flagrt.Value {
																var item = compiler__read_expr_arity_1(p)
																return func() flagrt.Value {
																	if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsNil(item))) {
																		return flagrt.NewRecur(elements)
																	}
																	return flagrt.NewRecur(flagrt.Conj(elements, item))
																}()
															}()
														}()
													}()
												}()
											}()
											if __recurValues, __isRecur := flagrt.UnwrapRecur(__loopResult); __isRecur {
												if len(__recurValues) != 1 {
													panic("internal error: recur arity mismatch")
												}
												elements = __recurValues[0]
												continue
											}
											return __loopResult
										}
									}()
								}()
							}
							return func() flagrt.Value {
								if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(token, flagrt.NewString("^")))) {
									return func() flagrt.Value {
										var meta_tok = flagrt.Call(compiler__next_tok, p)
										var meta = compiler__read_expr_arity_1(p)
										var target = compiler__read_expr_arity_1(p)
										return flagrt.NewMap(astflagKw_kind, astflagKw_meta, astflagKw_meta, meta, astflagKw_target, target, astflagKw_line, flagrt.Call(compiler__token_line, meta_tok), astflagKw_col, flagrt.Call(compiler__token_col, meta_tok))
									}()
								}
								return func() flagrt.Value {
									if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(token, flagrt.NewString("'")))) {
										return func() flagrt.Value {
											var quote_tok = flagrt.Call(compiler__next_tok, p)
											var quoted = compiler__read_expr_arity_1(p)
											return func() flagrt.Value {
												if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(astflagKw_symbol, flagrt.Call(astflagKw_kind, quoted)))) {
													return flagrt.NewMap(astflagKw_kind, astflagKw_quoted_symbol, astflagKw_name, flagrt.Call(astflagKw_name, quoted), astflagKw_line, flagrt.Call(compiler__token_line, quote_tok), astflagKw_col, flagrt.Call(compiler__token_col, quote_tok))
												}
												return func() flagrt.Value {
													if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(astflagKw_list, flagrt.Call(astflagKw_kind, quoted)))) {
														return flagrt.NewMap(astflagKw_kind, astflagKw_quoted_list, astflagKw_elements, flagrt.Call(astflagKw_elements, quoted), astflagKw_line, flagrt.Call(compiler__token_line, quote_tok), astflagKw_col, flagrt.Call(compiler__token_col, quote_tok))
													}
													return func() flagrt.Value {
														if flagrt.IsTruthy(flagrt.NewBool(true)) {
															return flagrt.Call(compiler__parse_error, flagrt.Call(compiler__token_line, quote_tok), flagrt.Call(compiler__token_col, quote_tok), astflagStr_quote_currently_supports)
														}
														return flagrt.NilValue()
													}()
												}()
											}()
										}()
									}
									return func() flagrt.Value {
										if flagrt.IsTruthy(flagrt.Call(compiler__string_token_q, tok)) {
											return flagrt.Call(compiler__read_string_token, p)
										}
										return func() flagrt.Value {
											if flagrt.IsTruthy(func() flagrt.Value {
												if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(token, flagrt.NewString(")")))) {
													return flagrt.NewBool(flagrt.Eq(token, flagrt.NewString(")")))
												}
												if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(token, flagrt.NewString("]")))) {
													return flagrt.NewBool(flagrt.Eq(token, flagrt.NewString("]")))
												}
												return flagrt.NewBool(flagrt.Eq(token, flagrt.NewString("}")))
											}()) {
												return flagrt.Call(compiler__parse_error, flagrt.Call(compiler__token_line, tok), flagrt.Call(compiler__token_col, tok), astflagStr_expected_expression)
											}
											return func() flagrt.Value {
												if flagrt.IsTruthy(flagrt.Call(compiler__starts_with_char_q, token, astflagStr___11)) {
													return func() flagrt.Value {
														_ = flagrt.Call(compiler__next_tok, p)
														return flagrt.Call(compiler__dispatch_error, tok)
													}()
												}
												return func() flagrt.Value {
													if flagrt.IsTruthy(flagrt.NewBool(true)) {
														return func() flagrt.Value {
															_ = flagrt.Call(compiler__next_tok, p)
															return flagrt.Call(compiler__parse_atom_token, tok)
														}()
													}
													return flagrt.NilValue()
												}()
											}()
										}()
									}()
								}()
							}()
						}()
					}()
				}()
			}()
		}()
	}()
}

func compiler__read_expr_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__read_expr expects exactly 1 arguments")
	}
	return compiler__read_expr_arity_1(args[0])
}

func compiler__ast_node__gtcanonical_arity_1(expr flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			var kind = flagrt.Call(astflagKw_kind, expr)
			var line = flagrt.Call(astflagKw_line, expr)
			var col = flagrt.Call(astflagKw_col, expr)
			var join = flagrt.NewFunction(func(args ...flagrt.Value) flagrt.Value {
				if len(args) != 1 {
					panic("fn expects exactly 1 arguments")
				}
				nodes := args[0]
				return func() flagrt.Value {
					var remaining = nodes
					var out = astflagStr_
					var first_q = flagrt.NewBool(true)
					for {
						__loopResult := func() flagrt.Value {
							return func() flagrt.Value {
								if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(remaining))) {
									return out
								}
								return func() flagrt.Value {
									var piece = compiler__ast_node__gtcanonical_arity_1(flagrt.First(remaining))
									return func() flagrt.Value {
										if flagrt.IsTruthy(first_q) {
											return flagrt.NewRecur(flagrt.Rest(remaining), piece, flagrt.NewBool(false))
										}
										return flagrt.NewRecur(flagrt.Rest(remaining), flagrt.NewString(flagrt.Str(out, " ", piece)), flagrt.NewBool(false))
									}()
								}()
							}()
						}()
						if __recurValues, __isRecur := flagrt.UnwrapRecur(__loopResult); __isRecur {
							if len(__recurValues) != 3 {
								panic("internal error: recur arity mismatch")
							}
							remaining = __recurValues[0]
							out = __recurValues[1]
							first_q = __recurValues[2]
							continue
						}
						return __loopResult
					}
				}()
			})
			return func() flagrt.Value {
				if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(kind, astflagKw_list))) {
					return flagrt.NewString(flagrt.Str("(:list :line ", line, " :col ", col, " :elements [", flagrt.Call(join, flagrt.Call(astflagKw_elements, expr)), "])"))
				}
				return func() flagrt.Value {
					if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(kind, astflagKw_vector))) {
						return flagrt.NewString(flagrt.Str("(:vector :line ", line, " :col ", col, " :elements [", flagrt.Call(join, flagrt.Call(astflagKw_elements, expr)), "])"))
					}
					return func() flagrt.Value {
						if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(kind, astflagKw_pipe_vector))) {
							return flagrt.NewString(flagrt.Str("(:pipe-vector :line ", line, " :col ", col, " :elements [", flagrt.Call(join, flagrt.Call(astflagKw_elements, expr)), "])"))
						}
						return func() flagrt.Value {
							if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(kind, astflagKw_map))) {
								return flagrt.NewString(flagrt.Str("(:map :line ", line, " :col ", col, " :entries [", flagrt.Call(join, flagrt.Call(astflagKw_entries, expr)), "])"))
							}
							return func() flagrt.Value {
								if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(kind, astflagKw_set))) {
									return flagrt.NewString(flagrt.Str("(:set :line ", line, " :col ", col, " :elements [", flagrt.Call(join, flagrt.Call(astflagKw_elements, expr)), "])"))
								}
								return func() flagrt.Value {
									if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(kind, astflagKw_hash_fn))) {
										return flagrt.NewString(flagrt.Str("(:hash-fn :line ", line, " :col ", col, " :body ", compiler__ast_node__gtcanonical_arity_1(flagrt.Call(astflagKw_body, expr)), ")"))
									}
									return func() flagrt.Value {
										if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(kind, astflagKw_meta))) {
											return flagrt.NewString(flagrt.Str("(:meta :line ", line, " :col ", col, " :meta ", compiler__ast_node__gtcanonical_arity_1(flagrt.Call(astflagKw_meta, expr)), " :target ", compiler__ast_node__gtcanonical_arity_1(flagrt.Call(astflagKw_target, expr)), ")"))
										}
										return func() flagrt.Value {
											if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(kind, astflagKw_symbol))) {
												return flagrt.NewString(flagrt.Str("(:symbol :name ", flagrt.Call(astflagKw_name, expr), " :line ", line, " :col ", col, ")"))
											}
											return func() flagrt.Value {
												if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(kind, astflagKw_keyword))) {
													return flagrt.NewString(flagrt.Str("(:keyword :name ", flagrt.Call(astflagKw_name, expr), " :line ", line, " :col ", col, ")"))
												}
												return func() flagrt.Value {
													if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(kind, astflagKw_quoted_symbol))) {
														return flagrt.NewString(flagrt.Str("(:quoted-symbol :name ", flagrt.Call(astflagKw_name, expr), " :line ", line, " :col ", col, ")"))
													}
													return func() flagrt.Value {
														if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(kind, astflagKw_quoted_list))) {
															return flagrt.NewString(flagrt.Str("(:quoted-list :line ", line, " :col ", col, " :elements [", flagrt.Call(join, flagrt.Call(astflagKw_elements, expr)), "])"))
														}
														return func() flagrt.Value {
															if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(kind, astflagKw_string))) {
																return flagrt.NewString(flagrt.Str("(:string :value ", flagrt.NewString(flagrt.Format("%q", flagrt.Call(astflagKw_value, expr))), " :line ", line, " :col ", col, ")"))
															}
															return func() flagrt.Value {
																if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(kind, astflagKw_char))) {
																	return flagrt.NewString(flagrt.Str("(:char :value ", flagrt.NewString(flagrt.Format("%q", flagrt.Call(astflagKw_value, expr))), " :line ", line, " :col ", col, ")"))
																}
																return func() flagrt.Value {
																	if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(kind, astflagKw_int))) {
																		return flagrt.NewString(flagrt.Str("(:int :value ", flagrt.Call(astflagKw_value, expr), " :line ", line, " :col ", col, ")"))
																	}
																	return func() flagrt.Value {
																		if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(kind, astflagKw_bigint))) {
																			return flagrt.NewString(flagrt.Str("(:bigint :value ", flagrt.Call(astflagKw_value, expr), " :line ", line, " :col ", col, ")"))
																		}
																		return func() flagrt.Value {
																			if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(kind, astflagKw_float))) {
																				return flagrt.NewString(flagrt.Str("(:float :value ", flagrt.Call(astflagKw_value, expr), " :raw ", flagrt.Call(astflagKw_raw, expr), " :line ", line, " :col ", col, ")"))
																			}
																			return func() flagrt.Value {
																				if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(kind, astflagKw_ratio))) {
																					return flagrt.NewString(flagrt.Str("(:ratio :numerator ", flagrt.Call(astflagKw_numerator, expr), " :denominator ", flagrt.Call(astflagKw_denominator, expr), " :line ", line, " :col ", col, ")"))
																				}
																				return func() flagrt.Value {
																					if flagrt.IsTruthy(flagrt.NewBool(true)) {
																						return func() flagrt.Value {
																							flagrt.Throw(flagrt.NewString(flagrt.Str("unsupported AST node ", kind)))
																							return flagrt.NilValue()
																						}()
																					}
																					return flagrt.NilValue()
																				}()
																			}()
																		}()
																	}()
																}()
															}()
														}()
													}()
												}()
											}()
										}()
									}()
								}()
							}()
						}()
					}()
				}()
			}()
		}()
	}()
}

func compiler__ast_node__gtcanonical_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__ast_node__gtcanonical expects exactly 1 arguments")
	}
	return compiler__ast_node__gtcanonical_arity_1(args[0])
}

func compiler__asts__gtcanonical_arity_1(exprs flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			var remaining = exprs
			var out = astflagStr_
			var first_q = flagrt.NewBool(true)
			for {
				__loopResult := func() flagrt.Value {
					return func() flagrt.Value {
						if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(remaining))) {
							return out
						}
						return func() flagrt.Value {
							var piece = flagrt.Call(compiler__ast_node__gtcanonical, flagrt.First(remaining))
							return func() flagrt.Value {
								if flagrt.IsTruthy(first_q) {
									return flagrt.NewRecur(flagrt.Rest(remaining), piece, flagrt.NewBool(false))
								}
								return flagrt.NewRecur(flagrt.Rest(remaining), flagrt.NewString(flagrt.Str(out, "\n", piece)), flagrt.NewBool(false))
							}()
						}()
					}()
				}()
				if __recurValues, __isRecur := flagrt.UnwrapRecur(__loopResult); __isRecur {
					if len(__recurValues) != 3 {
						panic("internal error: recur arity mismatch")
					}
					remaining = __recurValues[0]
					out = __recurValues[1]
					first_q = __recurValues[2]
					continue
				}
				return __loopResult
			}
		}()
	}()
}

func compiler__asts__gtcanonical_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__asts__gtcanonical expects exactly 1 arguments")
	}
	return compiler__asts__gtcanonical_arity_1(args[0])
}

func compiler__drain_remaining_arity_1(in flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			var _more = flagrt.NewBool(true)
			_ = _more
			for {
				__loopResult := func() flagrt.Value {
					return func() flagrt.Value {
						if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsNil(flagrt.Call(async__channel_receive, in)))) {
							return flagrt.NilValue()
						}
						return flagrt.NewRecur(flagrt.NewBool(true))
					}()
				}()
				if __recurValues, __isRecur := flagrt.UnwrapRecur(__loopResult); __isRecur {
					if len(__recurValues) != 1 {
						panic("internal error: recur arity mismatch")
					}
					_more = __recurValues[0]
					continue
				}
				return __loopResult
			}
		}()
	}()
}

func compiler__drain_remaining_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__drain_remaining expects exactly 1 arguments")
	}
	return compiler__drain_remaining_arity_1(args[0])
}

func compiler__build_ast_from_tokens_arity_1(in flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			var out = flagrt.Call(async__make_channel, flagrt.NewLong(64))
			var p = flagrt.Call(compiler__make_parser, in)
			_ = flagrt.Call(async__go_run, flagrt.NewFunction(func(args ...flagrt.Value) flagrt.Value {
				if len(args) != 0 {
					panic("fn expects exactly 0 arguments")
				}
				return func() flagrt.Value {
					return func() flagrt.Value {
						var __flag_try_result flagrt.Value
						defer func() {
							_ = func() flagrt.Value {
								_ = flagrt.Call(async__channel_close, out)
								return flagrt.Call(compiler__drain_remaining, in)
							}()
						}()
						func() {
							defer func() {
								r := recover()
								if r == nil {
									return
								}
								__flag_thrown := flagrt.PanicValue(r)
								if flagrt.CatchMatches("Exception", __flag_thrown) {
									__flag_try_result = func() flagrt.Value {
										var e = __flag_thrown
										_ = e
										return func() flagrt.Value {
											return flagrt.Call(async__channel_send, out, flagrt.NewMap(astflagKw_kind, astflagKw_error, astflagKw_message, flagrt.ExMessage(e)))
										}()
									}()
									return
								}
								panic(r)
							}()
							__flag_try_result = func() flagrt.Value {
								return func() flagrt.Value {
									var _more = flagrt.NewBool(true)
									_ = _more
									for {
										__loopResult := func() flagrt.Value {
											return func() flagrt.Value {
												var tok = flagrt.Call(compiler__peek, p)
												return func() flagrt.Value {
													if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(astflagKw_eof, tok))) {
														return flagrt.NilValue()
													}
													return func() flagrt.Value {
														var form = flagrt.Call(compiler__read_expr, p)
														return func() flagrt.Value {
															if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsNil(form))) {
																return flagrt.NewRecur(flagrt.NewBool(true))
															}
															return func() flagrt.Value {
																_ = flagrt.Call(async__channel_send, out, form)
																return flagrt.NewRecur(flagrt.NewBool(true))
															}()
														}()
													}()
												}()
											}()
										}()
										if __recurValues, __isRecur := flagrt.UnwrapRecur(__loopResult); __isRecur {
											if len(__recurValues) != 1 {
												panic("internal error: recur arity mismatch")
											}
											_more = __recurValues[0]
											continue
										}
										return __loopResult
									}
								}()
							}()
						}()
						return __flag_try_result
					}()
				}()
			}))
			return out
		}()
	}()
}

func compiler__build_ast_from_tokens_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__build_ast_from_tokens expects exactly 1 arguments")
	}
	return compiler__build_ast_from_tokens_arity_1(args[0])
}

var async__deref = flagrt.GoBind_async_Deref
var async__reset_bang = flagrt.GoBind_async_Reset

var async__atom = flagrt.GoBind_async_Atom
var async__swap_bang = flagrt.GoBind_async_Swap

var compiler__parse_error = flagrt.NewFunction(compiler__parse_error_variadic)
var compiler__token_line = flagrt.NewFunction(compiler__token_line_variadic)
var compiler__token_col = flagrt.NewFunction(compiler__token_col_variadic)
var compiler__make_parser = flagrt.NewFunction(compiler__make_parser_variadic)
var compiler__peek = flagrt.NewFunction(compiler__peek_variadic)
var compiler__next_tok = flagrt.NewFunction(compiler__next_tok_variadic)
var compiler__eof_line_col = flagrt.NewFunction(compiler__eof_line_col_variadic)
var compiler__starts_with_char_q = flagrt.NewFunction(compiler__starts_with_char_q_variadic)
var compiler__ends_with_char_q = flagrt.NewFunction(compiler__ends_with_char_q_variadic)
var compiler__contains_float_mark_q = flagrt.NewFunction(compiler__contains_float_mark_q_variadic)
var compiler__slash_count = flagrt.NewFunction(compiler__slash_count_variadic)
var compiler__split_once = flagrt.NewFunction(compiler__split_once_variadic)
var compiler__unescape_char = flagrt.NewFunction(compiler__unescape_char_variadic)
var compiler__unquote_go_string = flagrt.NewFunction(compiler__unquote_go_string_variadic)
var compiler__string_token_q = flagrt.NewFunction(compiler__string_token_q_variadic)
var compiler__strip_edges = flagrt.NewFunction(compiler__strip_edges_variadic)
var compiler__triple_quoted_q = flagrt.NewFunction(compiler__triple_quoted_q_variadic)
var compiler__triple_quoted_closed_q = flagrt.NewFunction(compiler__triple_quoted_closed_q_variadic)
var compiler__parse_char_token = flagrt.NewFunction(compiler__parse_char_token_variadic)
var compiler__signed_decimal_int_q = flagrt.NewFunction(compiler__signed_decimal_int_q_variadic)
var compiler__parse_atom_token = flagrt.NewFunction(compiler__parse_atom_token_variadic)
var compiler__comment_list_q = flagrt.NewFunction(compiler__comment_list_q_variadic)
var compiler__collection_node = flagrt.NewFunction(compiler__collection_node_variadic)
var compiler__dispatch_error = flagrt.NewFunction(compiler__dispatch_error_variadic)
var compiler__read_string_token = flagrt.NewFunction(compiler__read_string_token_variadic)
var compiler__read_expr = flagrt.NewFunction(compiler__read_expr_variadic)
var compiler__ast_node__gtcanonical = flagrt.NewFunction(compiler__ast_node__gtcanonical_variadic)
var compiler__asts__gtcanonical = flagrt.NewFunction(compiler__asts__gtcanonical_variadic)
var compiler__drain_remaining = flagrt.NewFunction(compiler__drain_remaining_variadic)
var compiler__build_ast_from_tokens = flagrt.NewFunction(compiler__build_ast_from_tokens_variadic)
var astflagKw_line = flagrt.NewKeyword("line")
var astflagKw_offset = flagrt.NewKeyword("offset")
var astflagKw_in = flagrt.NewKeyword("in")
var astflagKw_la = flagrt.NewKeyword("la")
var astflagKw_none = flagrt.NewKeyword("none")
var astflagKw_last = flagrt.NewKeyword("last")
var astflagKw_eof = flagrt.NewKeyword("eof")
var astflagVec = flagrt.NewArray(flagrt.NewLong(1), flagrt.NewLong(1))
var astflagKw_token = flagrt.NewKeyword("token")
var astflagStr_ = flagrt.NewString("")
var astflagStr__ = flagrt.NewString("\r")
var astflagStr___1 = flagrt.NewString("\t")
var astflagStr___2 = flagrt.NewString("\n")
var astflagKw_error = flagrt.NewKeyword("error")
var astflagStr___3 = flagrt.NewString("\"")
var astflagKw_kind = flagrt.NewKeyword("kind")
var astflagKw_char = flagrt.NewKeyword("char")
var astflagKw_value = flagrt.NewKeyword("value")
var astflagKw_col = flagrt.NewKeyword("col")
var astflagStr_unsupported_character_li = flagrt.NewString("unsupported character literal")
var astflagStr___4 = flagrt.NewString(":")
var astflagKw_keyword = flagrt.NewKeyword("keyword")
var astflagKw_name = flagrt.NewKeyword("name")
var astflagStr___5 = flagrt.NewString("\\")
var astflagStr___6 = flagrt.NewString("/")
var astflagStr_ratio_denominator_cannot = flagrt.NewString("ratio denominator cannot be zero")
var astflagKw_ratio = flagrt.NewKeyword("ratio")
var astflagKw_numerator = flagrt.NewKeyword("numerator")
var astflagKw_denominator = flagrt.NewKeyword("denominator")
var astflagKw_symbol = flagrt.NewKeyword("symbol")
var astflagStr_N = flagrt.NewString("N")
var astflagKw_bigint = flagrt.NewKeyword("bigint")
var astflagKw_int = flagrt.NewKeyword("int")
var astflagKw_float = flagrt.NewKeyword("float")
var astflagKw_raw = flagrt.NewKeyword("raw")
var astflagKw_map = flagrt.NewKeyword("map")
var astflagKw_entries = flagrt.NewKeyword("entries")
var astflagKw_elements = flagrt.NewKeyword("elements")
var astflagStr_unexpected_end_after__ = flagrt.NewString("unexpected end after #")
var astflagStr_unsupported_reader_dispa = flagrt.NewString("unsupported reader dispatch")
var astflagKw_string = flagrt.NewKeyword("string")
var astflagStr_unterminated_string_lite = flagrt.NewString("unterminated string literal")
var astflagStr_unexpected_end_of_input = flagrt.NewString("unexpected end of input")
var astflagKw_list = flagrt.NewKeyword("list")
var astflagKw_vector = flagrt.NewKeyword("vector")
var astflagKw_pipe_vector = flagrt.NewKeyword("pipe-vector")
var astflagKw_set = flagrt.NewKeyword("set")
var astflagStr___7 = flagrt.NewString("}")
var astflagStr___8 = flagrt.NewString("|")
var astflagStr___9 = flagrt.NewString("]")
var astflagStr___10 = flagrt.NewString(")")
var astflagStr_missing_closing____ = flagrt.NewString("missing closing \"}\"")
var astflagStr_missing_closing_____1 = flagrt.NewString("missing closing \"|\"")
var astflagStr_missing_closing_____2 = flagrt.NewString("missing closing \"]\"")
var astflagStr_missing_closing_____3 = flagrt.NewString("missing closing \")\"")
var astflagVec_1 = flagrt.NewArray()
var astflagKw_hash_fn = flagrt.NewKeyword("hash-fn")
var astflagKw_body = flagrt.NewKeyword("body")
var astflagKw_meta = flagrt.NewKeyword("meta")
var astflagKw_target = flagrt.NewKeyword("target")
var astflagKw_quoted_symbol = flagrt.NewKeyword("quoted-symbol")
var astflagKw_quoted_list = flagrt.NewKeyword("quoted-list")
var astflagStr_quote_currently_supports = flagrt.NewString("quote currently supports symbols and lists")
var astflagStr_expected_expression = flagrt.NewString("expected expression")
var astflagStr___11 = flagrt.NewString("#")
var astflagKw_message = flagrt.NewKeyword("message")
