// Code generated by internal/compiler/expandmacrosgen; DO NOT EDIT.
//go:generate go run flag-lang/internal/compiler/expandmacrosgen

package compiler

import (
	flagrt "flag-lang/runtime"
)

func compiler__symbol_node_q_arity_1(expr flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return flagrt.NewBool(flagrt.Eq(macflagKw_symbol, flagrt.Call(macflagKw_kind, expr)))
	}()
}

func compiler__symbol_node_q_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__symbol_node_q expects exactly 1 arguments")
	}
	return compiler__symbol_node_q_arity_1(args[0])
}

func compiler__list_node_q_arity_1(expr flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return flagrt.NewBool(flagrt.Eq(macflagKw_list, flagrt.Call(macflagKw_kind, expr)))
	}()
}

func compiler__list_node_q_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__list_node_q expects exactly 1 arguments")
	}
	return compiler__list_node_q_arity_1(args[0])
}

func compiler__vector_node_q_arity_1(expr flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return flagrt.NewBool(flagrt.Eq(macflagKw_vector, flagrt.Call(macflagKw_kind, expr)))
	}()
}

func compiler__vector_node_q_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__vector_node_q expects exactly 1 arguments")
	}
	return compiler__vector_node_q_arity_1(args[0])
}

func compiler__pipe_vector_node_q_arity_1(expr flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return flagrt.NewBool(flagrt.Eq(macflagKw_pipe_vector, flagrt.Call(macflagKw_kind, expr)))
	}()
}

func compiler__pipe_vector_node_q_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__pipe_vector_node_q expects exactly 1 arguments")
	}
	return compiler__pipe_vector_node_q_arity_1(args[0])
}

func compiler__map_node_q_arity_1(expr flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return flagrt.NewBool(flagrt.Eq(macflagKw_map, flagrt.Call(macflagKw_kind, expr)))
	}()
}

func compiler__map_node_q_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__map_node_q expects exactly 1 arguments")
	}
	return compiler__map_node_q_arity_1(args[0])
}

func compiler__set_node_q_arity_1(expr flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return flagrt.NewBool(flagrt.Eq(macflagKw_set, flagrt.Call(macflagKw_kind, expr)))
	}()
}

func compiler__set_node_q_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__set_node_q expects exactly 1 arguments")
	}
	return compiler__set_node_q_arity_1(args[0])
}

func compiler__hash_fn_node_q_arity_1(expr flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return flagrt.NewBool(flagrt.Eq(macflagKw_hash_fn, flagrt.Call(macflagKw_kind, expr)))
	}()
}

func compiler__hash_fn_node_q_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__hash_fn_node_q expects exactly 1 arguments")
	}
	return compiler__hash_fn_node_q_arity_1(args[0])
}

func compiler__meta_node_q_arity_1(expr flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return flagrt.NewBool(flagrt.Eq(macflagKw_meta, flagrt.Call(macflagKw_kind, expr)))
	}()
}

func compiler__meta_node_q_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__meta_node_q expects exactly 1 arguments")
	}
	return compiler__meta_node_q_arity_1(args[0])
}

func compiler__string_node_q_arity_1(expr flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return flagrt.NewBool(flagrt.Eq(macflagKw_string, flagrt.Call(macflagKw_kind, expr)))
	}()
}

func compiler__string_node_q_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__string_node_q expects exactly 1 arguments")
	}
	return compiler__string_node_q_arity_1(args[0])
}

func compiler__unwrap_meta_arity_1(expr flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			if flagrt.IsTruthy(flagrt.Call(compiler__meta_node_q, expr)) {
				return flagrt.Call(macflagKw_target, expr)
			}
			return expr
		}()
	}()
}

func compiler__unwrap_meta_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__unwrap_meta expects exactly 1 arguments")
	}
	return compiler__unwrap_meta_arity_1(args[0])
}

func compiler__node_children_arity_1(expr flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			if flagrt.IsTruthy(flagrt.Call(compiler__map_node_q, expr)) {
				return flagrt.Call(macflagKw_entries, expr)
			}
			return flagrt.Call(macflagKw_elements, expr)
		}()
	}()
}

func compiler__node_children_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__node_children expects exactly 1 arguments")
	}
	return compiler__node_children_arity_1(args[0])
}

func compiler__with_children_arity_2(expr flagrt.Value, children flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			if flagrt.IsTruthy(flagrt.Call(compiler__map_node_q, expr)) {
				return flagrt.Assoc(expr, macflagKw_entries, children)
			}
			return flagrt.Assoc(expr, macflagKw_elements, children)
		}()
	}()
}

func compiler__with_children_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 2 {
		panic("compiler__with_children expects exactly 2 arguments")
	}
	return compiler__with_children_arity_2(args[0], args[1])
}

func compiler__splice_node_q_arity_1(expr flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			if flagrt.IsTruthy(flagrt.Call(compiler__list_node_q, expr)) {
				return flagrt.Call(compiler__list_node_q, expr)
			}
			if flagrt.IsTruthy(flagrt.Call(compiler__vector_node_q, expr)) {
				return flagrt.Call(compiler__vector_node_q, expr)
			}
			return flagrt.Call(compiler__pipe_vector_node_q, expr)
		}()
	}()
}

func compiler__splice_node_q_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__splice_node_q expects exactly 1 arguments")
	}
	return compiler__splice_node_q_arity_1(args[0])
}

func compiler__walk_node_q_arity_1(expr flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			if flagrt.IsTruthy(flagrt.Call(compiler__splice_node_q, expr)) {
				return flagrt.Call(compiler__splice_node_q, expr)
			}
			if flagrt.IsTruthy(flagrt.Call(compiler__map_node_q, expr)) {
				return flagrt.Call(compiler__map_node_q, expr)
			}
			return flagrt.Call(compiler__set_node_q, expr)
		}()
	}()
}

func compiler__walk_node_q_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__walk_node_q expects exactly 1 arguments")
	}
	return compiler__walk_node_q_arity_1(args[0])
}

func compiler__make_symbol_arity_1(name flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return flagrt.NewMap(macflagKw_kind, macflagKw_symbol, macflagKw_name, name)
	}()
}

func compiler__make_symbol_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__make_symbol expects exactly 1 arguments")
	}
	return compiler__make_symbol_arity_1(args[0])
}

func compiler__make_list_arity_1(elements flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return flagrt.NewMap(macflagKw_kind, macflagKw_list, macflagKw_elements, elements)
	}()
}

func compiler__make_list_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__make_list expects exactly 1 arguments")
	}
	return compiler__make_list_arity_1(args[0])
}

func compiler__wrap_literal_arity_1(expr flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return flagrt.NewMap(macflagKw_kind, macflagKw_macro_literal, macflagKw_inner, expr)
	}()
}

func compiler__wrap_literal_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__wrap_literal expects exactly 1 arguments")
	}
	return compiler__wrap_literal_arity_1(args[0])
}

func compiler__unwrap_literal_arity_1(expr flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(macflagKw_macro_literal, flagrt.Call(macflagKw_kind, expr)))) {
				return compiler__unwrap_literal_arity_1(flagrt.Call(macflagKw_inner, expr))
			}
			return expr
		}()
	}()
}

func compiler__unwrap_literal_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__unwrap_literal expects exactly 1 arguments")
	}
	return compiler__unwrap_literal_arity_1(args[0])
}

func compiler__unwrap_literal_tree_arity_1(expr flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			var expr = flagrt.Call(compiler__unwrap_literal, expr)
			return func() flagrt.Value {
				if flagrt.IsTruthy(flagrt.Call(compiler__walk_node_q, expr)) {
					return flagrt.Call(compiler__with_children, expr, func() flagrt.Value {
						var remaining = flagrt.Call(compiler__node_children, expr)
						var acc = macflagVec
						for {
							__loopResult := func() flagrt.Value {
								return func() flagrt.Value {
									if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(remaining))) {
										return acc
									}
									return flagrt.NewRecur(flagrt.Rest(remaining), flagrt.Conj(acc, compiler__unwrap_literal_tree_arity_1(flagrt.First(remaining))))
								}()
							}()
							if __recurValues, __isRecur := flagrt.UnwrapRecur(__loopResult); __isRecur {
								if len(__recurValues) != 2 {
									panic("internal error: recur arity mismatch")
								}
								remaining = __recurValues[0]
								acc = __recurValues[1]
								continue
							}
							return __loopResult
						}
					}())
				}
				return func() flagrt.Value {
					if flagrt.IsTruthy(flagrt.Call(compiler__hash_fn_node_q, expr)) {
						return flagrt.Assoc(expr, macflagKw_body, compiler__unwrap_literal_tree_arity_1(flagrt.Call(macflagKw_body, expr)))
					}
					return func() flagrt.Value {
						if flagrt.IsTruthy(flagrt.Call(compiler__meta_node_q, expr)) {
							return flagrt.Assoc(expr, macflagKw_meta, compiler__unwrap_literal_tree_arity_1(flagrt.Call(macflagKw_meta, expr)), macflagKw_target, compiler__unwrap_literal_tree_arity_1(flagrt.Call(macflagKw_target, expr)))
						}
						return expr
					}()
				}()
			}()
		}()
	}()
}

func compiler__unwrap_literal_tree_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__unwrap_literal_tree expects exactly 1 arguments")
	}
	return compiler__unwrap_literal_tree_arity_1(args[0])
}

func compiler__macro_definition_q_arity_1(expr flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			if !(flagrt.IsTruthy(flagrt.Call(compiler__list_node_q, expr))) {
				return flagrt.Call(compiler__list_node_q, expr)
			}
			if !(flagrt.IsTruthy(func() flagrt.Value {
				if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(flagrt.Call(compiler__node_children, expr)))) {
					return flagrt.NewBool(false)
				}
				return flagrt.NewBool(true)
			}())) {
				return func() flagrt.Value {
					if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(flagrt.Call(compiler__node_children, expr)))) {
						return flagrt.NewBool(false)
					}
					return flagrt.NewBool(true)
				}()
			}
			if !(flagrt.IsTruthy(flagrt.Call(compiler__symbol_node_q, flagrt.Call(compiler__unwrap_meta, flagrt.First(flagrt.Call(compiler__node_children, expr)))))) {
				return flagrt.Call(compiler__symbol_node_q, flagrt.Call(compiler__unwrap_meta, flagrt.First(flagrt.Call(compiler__node_children, expr))))
			}
			return flagrt.NewBool(flagrt.Eq(flagrt.NewString("defmacro"), flagrt.Call(macflagKw_name, flagrt.Call(compiler__unwrap_meta, flagrt.First(flagrt.Call(compiler__node_children, expr))))))
		}()
	}()
}

func compiler__macro_definition_q_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__macro_definition_q expects exactly 1 arguments")
	}
	return compiler__macro_definition_q_arity_1(args[0])
}

func compiler__append_all_arity_2(target flagrt.Value, items flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			var remaining = items
			var out = target
			for {
				__loopResult := func() flagrt.Value {
					return func() flagrt.Value {
						if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(remaining))) {
							return out
						}
						return flagrt.NewRecur(flagrt.Rest(remaining), flagrt.Conj(out, flagrt.First(remaining)))
					}()
				}()
				if __recurValues, __isRecur := flagrt.UnwrapRecur(__loopResult); __isRecur {
					if len(__recurValues) != 2 {
						panic("internal error: recur arity mismatch")
					}
					remaining = __recurValues[0]
					out = __recurValues[1]
					continue
				}
				return __loopResult
			}
		}()
	}()
}

func compiler__append_all_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 2 {
		panic("compiler__append_all expects exactly 2 arguments")
	}
	return compiler__append_all_arity_2(args[0], args[1])
}

func compiler__nth_node_arity_2(nodes flagrt.Value, n flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return flagrt.First(flagrt.Drop(n, nodes))
	}()
}

func compiler__nth_node_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 2 {
		panic("compiler__nth_node expects exactly 2 arguments")
	}
	return compiler__nth_node_arity_2(args[0], args[1])
}

func compiler__node_equal_q_arity_2(a flagrt.Value, b flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			if flagrt.IsTruthy(func() flagrt.Value {
				if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsNil(a))) {
					return flagrt.NewBool(flagrt.IsNil(a))
				}
				return flagrt.NewBool(flagrt.IsNil(b))
			}()) {
				return func() flagrt.Value {
					if !(flagrt.IsTruthy(flagrt.NewBool(flagrt.IsNil(a)))) {
						return flagrt.NewBool(flagrt.IsNil(a))
					}
					return flagrt.NewBool(flagrt.IsNil(b))
				}()
			}
			return func() flagrt.Value {
				var kind = flagrt.Call(macflagKw_kind, a)
				return func() flagrt.Value {
					if flagrt.IsTruthy(func() flagrt.Value {
						if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(kind, flagrt.Call(macflagKw_kind, b)))) {
							return flagrt.NewBool(false)
						}
						return flagrt.NewBool(true)
					}()) {
						return flagrt.NewBool(false)
					}
					return func() flagrt.Value {
						if flagrt.IsTruthy(func() flagrt.Value {
							if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(kind, macflagKw_symbol))) {
								return flagrt.NewBool(flagrt.Eq(kind, macflagKw_symbol))
							}
							if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(kind, macflagKw_keyword))) {
								return flagrt.NewBool(flagrt.Eq(kind, macflagKw_keyword))
							}
							return flagrt.NewBool(flagrt.Eq(kind, macflagKw_quoted_symbol))
						}()) {
							return flagrt.NewBool(flagrt.Eq(flagrt.Call(macflagKw_name, a), flagrt.Call(macflagKw_name, b)))
						}
						return func() flagrt.Value {
							if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(kind, macflagKw_string))) {
								return flagrt.NewBool(flagrt.Eq(flagrt.Call(macflagKw_value, a), flagrt.Call(macflagKw_value, b)))
							}
							return func() flagrt.Value {
								if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(kind, macflagKw_char))) {
									return flagrt.NewBool(flagrt.Eq(flagrt.Call(macflagKw_value, a), flagrt.Call(macflagKw_value, b)))
								}
								return func() flagrt.Value {
									if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(kind, macflagKw_int))) {
										return flagrt.NewBool(flagrt.Eq(flagrt.Call(macflagKw_value, a), flagrt.Call(macflagKw_value, b)))
									}
									return func() flagrt.Value {
										if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(kind, macflagKw_bigint))) {
											return flagrt.NewBool(flagrt.Eq(flagrt.Call(macflagKw_value, a), flagrt.Call(macflagKw_value, b)))
										}
										return func() flagrt.Value {
											if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(kind, macflagKw_float))) {
												return func() flagrt.Value {
													if !(flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(flagrt.Call(macflagKw_raw, a), flagrt.Call(macflagKw_raw, b))))) {
														return flagrt.NewBool(flagrt.Eq(flagrt.Call(macflagKw_raw, a), flagrt.Call(macflagKw_raw, b)))
													}
													return flagrt.NewBool(flagrt.Eq(flagrt.Call(macflagKw_value, a), flagrt.Call(macflagKw_value, b)))
												}()
											}
											return func() flagrt.Value {
												if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(kind, macflagKw_ratio))) {
													return func() flagrt.Value {
														if !(flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(flagrt.Call(macflagKw_numerator, a), flagrt.Call(macflagKw_numerator, b))))) {
															return flagrt.NewBool(flagrt.Eq(flagrt.Call(macflagKw_numerator, a), flagrt.Call(macflagKw_numerator, b)))
														}
														return flagrt.NewBool(flagrt.Eq(flagrt.Call(macflagKw_denominator, a), flagrt.Call(macflagKw_denominator, b)))
													}()
												}
												return func() flagrt.Value {
													if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(kind, macflagKw_hash_fn))) {
														return compiler__node_equal_q_arity_2(flagrt.Call(macflagKw_body, a), flagrt.Call(macflagKw_body, b))
													}
													return func() flagrt.Value {
														if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(kind, macflagKw_meta))) {
															return func() flagrt.Value {
																if !(flagrt.IsTruthy(compiler__node_equal_q_arity_2(flagrt.Call(macflagKw_meta, a), flagrt.Call(macflagKw_meta, b)))) {
																	return compiler__node_equal_q_arity_2(flagrt.Call(macflagKw_meta, a), flagrt.Call(macflagKw_meta, b))
																}
																return compiler__node_equal_q_arity_2(flagrt.Call(macflagKw_target, a), flagrt.Call(macflagKw_target, b))
															}()
														}
														return func() flagrt.Value {
															if flagrt.IsTruthy(flagrt.Call(compiler__walk_node_q, a)) {
																return func() flagrt.Value {
																	var as = flagrt.Call(compiler__node_children, a)
																	var bs = flagrt.Call(compiler__node_children, b)
																	return func() flagrt.Value {
																		if flagrt.IsTruthy(func() flagrt.Value {
																			if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(flagrt.NewLong(int64(flagrt.Count(as))), flagrt.NewLong(int64(flagrt.Count(bs)))))) {
																				return flagrt.NewBool(false)
																			}
																			return flagrt.NewBool(true)
																		}()) {
																			return flagrt.NewBool(false)
																		}
																		return func() flagrt.Value {
																			var left = as
																			var right = bs
																			for {
																				__loopResult := func() flagrt.Value {
																					return func() flagrt.Value {
																						if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(left))) {
																							return flagrt.NewBool(true)
																						}
																						return func() flagrt.Value {
																							if flagrt.IsTruthy(compiler__node_equal_q_arity_2(flagrt.First(left), flagrt.First(right))) {
																								return flagrt.NewRecur(flagrt.Rest(left), flagrt.Rest(right))
																							}
																							return flagrt.NewBool(false)
																						}()
																					}()
																				}()
																				if __recurValues, __isRecur := flagrt.UnwrapRecur(__loopResult); __isRecur {
																					if len(__recurValues) != 2 {
																						panic("internal error: recur arity mismatch")
																					}
																					left = __recurValues[0]
																					right = __recurValues[1]
																					continue
																				}
																				return __loopResult
																			}
																		}()
																	}()
																}()
															}
															return func() flagrt.Value {
																if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(kind, macflagKw_quoted_list))) {
																	return func() flagrt.Value {
																		var as = flagrt.Call(macflagKw_elements, a)
																		var bs = flagrt.Call(macflagKw_elements, b)
																		return func() flagrt.Value {
																			if flagrt.IsTruthy(func() flagrt.Value {
																				if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(flagrt.NewLong(int64(flagrt.Count(as))), flagrt.NewLong(int64(flagrt.Count(bs)))))) {
																					return flagrt.NewBool(false)
																				}
																				return flagrt.NewBool(true)
																			}()) {
																				return flagrt.NewBool(false)
																			}
																			return func() flagrt.Value {
																				var left = as
																				var right = bs
																				for {
																					__loopResult := func() flagrt.Value {
																						return func() flagrt.Value {
																							if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(left))) {
																								return flagrt.NewBool(true)
																							}
																							return func() flagrt.Value {
																								if flagrt.IsTruthy(compiler__node_equal_q_arity_2(flagrt.First(left), flagrt.First(right))) {
																									return flagrt.NewRecur(flagrt.Rest(left), flagrt.Rest(right))
																								}
																								return flagrt.NewBool(false)
																							}()
																						}()
																					}()
																					if __recurValues, __isRecur := flagrt.UnwrapRecur(__loopResult); __isRecur {
																						if len(__recurValues) != 2 {
																							panic("internal error: recur arity mismatch")
																						}
																						left = __recurValues[0]
																						right = __recurValues[1]
																						continue
																					}
																					return __loopResult
																				}
																			}()
																		}()
																	}()
																}
																return func() flagrt.Value {
																	if flagrt.IsTruthy(flagrt.NewBool(true)) {
																		return flagrt.NewBool(false)
																	}
																	return flagrt.NilValue()
																}()
															}()
														}()
													}()
												}()
											}()
										}()
									}()
								}()
							}()
						}()
					}()
				}()
			}()
		}()
	}()
}

func compiler__node_equal_q_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 2 {
		panic("compiler__node_equal_q expects exactly 2 arguments")
	}
	return compiler__node_equal_q_arity_2(args[0], args[1])
}

func compiler__parse_macro_params_arity_1(params_node flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			if flagrt.IsTruthy(func() flagrt.Value {
				if flagrt.IsTruthy(flagrt.Call(compiler__vector_node_q, params_node)) {
					return flagrt.NewBool(false)
				}
				return flagrt.NewBool(true)
			}()) {
				return func() flagrt.Value {
					flagrt.Throw(flagrt.NewMap(macflagKw_message, flagrt.NewString("defmacro expects a parameter vector"), macflagKw_data, flagrt.NewMap(macflagKw_form, params_node)))
					return flagrt.NilValue()
				}()
			}
			return func() flagrt.Value {
				var remaining = flagrt.Call(compiler__node_children, params_node)
				var params = macflagVec
				for {
					__loopResult := func() flagrt.Value {
						return func() flagrt.Value {
							if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(remaining))) {
								return flagrt.NewMap(macflagKw_params, params, macflagKw_rest_param, flagrt.NilValue())
							}
							return func() flagrt.Value {
								var param_node = flagrt.Call(compiler__unwrap_meta, flagrt.First(remaining))
								return func() flagrt.Value {
									if flagrt.IsTruthy(func() flagrt.Value {
										if flagrt.IsTruthy(flagrt.Call(compiler__symbol_node_q, param_node)) {
											return flagrt.NewBool(false)
										}
										return flagrt.NewBool(true)
									}()) {
										return func() flagrt.Value {
											flagrt.Throw(flagrt.NewMap(macflagKw_message, flagrt.NewString("defmacro parameters must be symbols"), macflagKw_data, flagrt.NewMap(macflagKw_form, params_node)))
											return flagrt.NilValue()
										}()
									}
									return func() flagrt.Value {
										if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(flagrt.NewString("&"), flagrt.Call(macflagKw_name, param_node)))) {
											return func() flagrt.Value {
												var tail = flagrt.Rest(remaining)
												return func() flagrt.Value {
													if flagrt.IsTruthy(func() flagrt.Value {
														if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(flagrt.NewLong(1), flagrt.NewLong(int64(flagrt.Count(tail)))))) {
															return flagrt.NewBool(false)
														}
														return flagrt.NewBool(true)
													}()) {
														return func() flagrt.Value {
															flagrt.Throw(flagrt.NewMap(macflagKw_message, flagrt.NewString("defmacro varargs must use [& name] at end"), macflagKw_data, flagrt.NewMap(macflagKw_form, params_node)))
															return flagrt.NilValue()
														}()
													}
													return func() flagrt.Value {
														var rest_node = flagrt.Call(compiler__unwrap_meta, flagrt.First(tail))
														return func() flagrt.Value {
															if flagrt.IsTruthy(func() flagrt.Value {
																if flagrt.IsTruthy(func() flagrt.Value {
																	if flagrt.IsTruthy(flagrt.Call(compiler__symbol_node_q, rest_node)) {
																		return flagrt.NewBool(false)
																	}
																	return flagrt.NewBool(true)
																}()) {
																	return func() flagrt.Value {
																		if flagrt.IsTruthy(flagrt.Call(compiler__symbol_node_q, rest_node)) {
																			return flagrt.NewBool(false)
																		}
																		return flagrt.NewBool(true)
																	}()
																}
																return flagrt.NewBool(flagrt.Eq(flagrt.NewString("&"), flagrt.Call(macflagKw_name, rest_node)))
															}()) {
																return func() flagrt.Value {
																	flagrt.Throw(flagrt.NewMap(macflagKw_message, flagrt.NewString("defmacro varargs expects symbol after &"), macflagKw_data, flagrt.NewMap(macflagKw_form, params_node)))
																	return flagrt.NilValue()
																}()
															}
															return flagrt.NewMap(macflagKw_params, params, macflagKw_rest_param, flagrt.Call(macflagKw_name, rest_node))
														}()
													}()
												}()
											}()
										}
										return flagrt.NewRecur(flagrt.Rest(remaining), flagrt.Conj(params, flagrt.Call(macflagKw_name, param_node)))
									}()
								}()
							}()
						}()
					}()
					if __recurValues, __isRecur := flagrt.UnwrapRecur(__loopResult); __isRecur {
						if len(__recurValues) != 2 {
							panic("internal error: recur arity mismatch")
						}
						remaining = __recurValues[0]
						params = __recurValues[1]
						continue
					}
					return __loopResult
				}
			}()
		}()
	}()
}

func compiler__parse_macro_params_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__parse_macro_params expects exactly 1 arguments")
	}
	return compiler__parse_macro_params_arity_1(args[0])
}

func compiler__compile_multi_arity_arity_3(name flagrt.Value, children flagrt.Value, start flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			var arity_forms = flagrt.Drop(start, children)
			return func() flagrt.Value {
				if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(arity_forms))) {
					return func() flagrt.Value {
						flagrt.Throw(flagrt.NewMap(macflagKw_message, flagrt.NewString("defmacro expects at least one arity"), macflagKw_data, flagrt.NewMap(macflagKw_name, name)))
						return flagrt.NilValue()
					}()
				}
				return func() flagrt.Value {
					var remaining = arity_forms
					var arities = macflagVec
					var seen = macflagMap
					var max_fixed = flagrt.NewLong(-1)
					var rest_min = flagrt.NewLong(-1)
					for {
						__loopResult := func() flagrt.Value {
							return func() flagrt.Value {
								if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(remaining))) {
									return func() flagrt.Value {
										if flagrt.IsTruthy(func() flagrt.Value {
											if !(flagrt.Ge(rest_min, flagrt.NewLong(0))) {
												return flagrt.NewBool(flagrt.Ge(rest_min, flagrt.NewLong(0)))
											}
											return flagrt.NewBool(flagrt.Gt(max_fixed, rest_min))
										}()) {
											return func() flagrt.Value {
												flagrt.Throw(flagrt.NewMap(macflagKw_message, flagrt.NewString("defmacro rest arity must have at least as many required parameters as the largest fixed arity"), macflagKw_data, flagrt.NewMap(macflagKw_name, name)))
												return flagrt.NilValue()
											}()
										}
										return flagrt.NewMap(macflagKw_name, name, macflagKw_arities, arities)
									}()
								}
								return func() flagrt.Value {
									var raw = flagrt.First(remaining)
									return func() flagrt.Value {
										if flagrt.IsTruthy(func() flagrt.Value {
											if flagrt.IsTruthy(func() flagrt.Value {
												if flagrt.IsTruthy(flagrt.Call(compiler__list_node_q, raw)) {
													return flagrt.NewBool(false)
												}
												return flagrt.NewBool(true)
											}()) {
												return func() flagrt.Value {
													if flagrt.IsTruthy(flagrt.Call(compiler__list_node_q, raw)) {
														return flagrt.NewBool(false)
													}
													return flagrt.NewBool(true)
												}()
											}
											return flagrt.NewBool(flagrt.Lt(flagrt.NewLong(int64(flagrt.Count(flagrt.Call(compiler__node_children, raw)))), flagrt.NewLong(2)))
										}()) {
											return func() flagrt.Value {
												flagrt.Throw(flagrt.NewMap(macflagKw_message, flagrt.NewString("defmacro arity expects ([params] body...)"), macflagKw_data, flagrt.NewMap(macflagKw_form, raw)))
												return flagrt.NilValue()
											}()
										}
										return func() flagrt.Value {
											var arity_children = flagrt.Call(compiler__node_children, raw)
											var params_expr = flagrt.First(arity_children)
											return func() flagrt.Value {
												if flagrt.IsTruthy(func() flagrt.Value {
													if flagrt.IsTruthy(flagrt.Call(compiler__vector_node_q, params_expr)) {
														return flagrt.NewBool(false)
													}
													return flagrt.NewBool(true)
												}()) {
													return func() flagrt.Value {
														flagrt.Throw(flagrt.NewMap(macflagKw_message, flagrt.NewString("defmacro arity expects a parameter vector"), macflagKw_data, flagrt.NewMap(macflagKw_form, raw)))
														return flagrt.NilValue()
													}()
												}
												return func() flagrt.Value {
													var param_spec = flagrt.Call(compiler__parse_macro_params, params_expr)
													var n = flagrt.NewLong(int64(flagrt.Count(flagrt.Call(macflagKw_params, param_spec))))
													var rest_param = flagrt.Call(macflagKw_rest_param, param_spec)
													var body_items = flagrt.Rest(arity_children)
													var body = func() flagrt.Value {
														if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(flagrt.NewLong(1), flagrt.NewLong(int64(flagrt.Count(body_items)))))) {
															return flagrt.First(body_items)
														}
														return flagrt.Call(compiler__make_list, flagrt.Cons(flagrt.Call(compiler__make_symbol, macflagStr_do), body_items))
													}()
													return func() flagrt.Value {
														if flagrt.IsTruthy(rest_param) {
															return func() flagrt.Value {
																if flagrt.Ge(rest_min, flagrt.NewLong(0)) {
																	return func() flagrt.Value {
																		flagrt.Throw(flagrt.NewMap(macflagKw_message, flagrt.NewString("defmacro supports only one & rest arity"), macflagKw_data, flagrt.NewMap(macflagKw_name, name)))
																		return flagrt.NilValue()
																	}()
																}
																return flagrt.NewRecur(flagrt.Rest(remaining), flagrt.Conj(arities, flagrt.NewMap(macflagKw_params, flagrt.Call(macflagKw_params, param_spec), macflagKw_rest_param, rest_param, macflagKw_body, body)), seen, max_fixed, n)
															}()
														}
														return func() flagrt.Value {
															if flagrt.IsTruthy(flagrt.NewBool(flagrt.Contains(seen, n))) {
																return func() flagrt.Value {
																	flagrt.Throw(flagrt.NewMap(macflagKw_message, flagrt.NewString(flagrt.Str("duplicate macro arity with ", n, " arguments")), macflagKw_data, flagrt.NewMap(macflagKw_name, name)))
																	return flagrt.NilValue()
																}()
															}
															return flagrt.NewRecur(flagrt.Rest(remaining), flagrt.Conj(arities, flagrt.NewMap(macflagKw_params, flagrt.Call(macflagKw_params, param_spec), macflagKw_rest_param, flagrt.NilValue(), macflagKw_body, body)), flagrt.Assoc(seen, n, flagrt.NewBool(true)), func() flagrt.Value {
																if flagrt.Gt(n, max_fixed) {
																	return n
																}
																return max_fixed
															}(), rest_min)
														}()
													}()
												}()
											}()
										}()
									}()
								}()
							}()
						}()
						if __recurValues, __isRecur := flagrt.UnwrapRecur(__loopResult); __isRecur {
							if len(__recurValues) != 5 {
								panic("internal error: recur arity mismatch")
							}
							remaining = __recurValues[0]
							arities = __recurValues[1]
							seen = __recurValues[2]
							max_fixed = __recurValues[3]
							rest_min = __recurValues[4]
							continue
						}
						return __loopResult
					}
				}()
			}()
		}()
	}()
}

func compiler__compile_multi_arity_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 3 {
		panic("compiler__compile_multi_arity expects exactly 3 arguments")
	}
	return compiler__compile_multi_arity_arity_3(args[0], args[1], args[2])
}

func compiler__compile_defmacro_arity_1(expr flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			var children = flagrt.Call(compiler__node_children, expr)
			return func() flagrt.Value {
				if flagrt.Lt(flagrt.NewLong(int64(flagrt.Count(children))), flagrt.NewLong(3)) {
					return func() flagrt.Value {
						flagrt.Throw(flagrt.NewMap(macflagKw_message, flagrt.NewString("defmacro expects name, optional docstring, vector params, and body"), macflagKw_data, flagrt.NewMap(macflagKw_form, expr)))
						return flagrt.NilValue()
					}()
				}
				return func() flagrt.Value {
					var name_node = flagrt.Call(compiler__unwrap_meta, flagrt.Call(stdlib__second, children))
					return func() flagrt.Value {
						if flagrt.IsTruthy(func() flagrt.Value {
							if flagrt.IsTruthy(flagrt.Call(compiler__symbol_node_q, name_node)) {
								return flagrt.NewBool(false)
							}
							return flagrt.NewBool(true)
						}()) {
							return func() flagrt.Value {
								flagrt.Throw(flagrt.NewMap(macflagKw_message, flagrt.NewString("defmacro expects a macro name"), macflagKw_data, flagrt.NewMap(macflagKw_form, expr)))
								return flagrt.NilValue()
							}()
						}
						return func() flagrt.Value {
							var maybe_doc = flagrt.Call(stdlib__third, children)
							var has_docstring = flagrt.Call(compiler__string_node_q, maybe_doc)
							var params_index = func() flagrt.Value {
								if flagrt.IsTruthy(has_docstring) {
									return flagrt.NewLong(3)
								}
								return flagrt.NewLong(2)
							}()
							var body_index = func() flagrt.Value {
								if flagrt.IsTruthy(has_docstring) {
									return flagrt.NewLong(4)
								}
								return flagrt.NewLong(3)
							}()
							return func() flagrt.Value {
								if flagrt.Ge(params_index, flagrt.NewLong(int64(flagrt.Count(children)))) {
									return func() flagrt.Value {
										flagrt.Throw(flagrt.NewMap(macflagKw_message, flagrt.NewString("defmacro expects name, optional docstring, vector params, and body"), macflagKw_data, flagrt.NewMap(macflagKw_form, expr)))
										return flagrt.NilValue()
									}()
								}
								return func() flagrt.Value {
									if flagrt.IsTruthy(flagrt.Call(compiler__list_node_q, flagrt.Call(compiler__nth_node, children, params_index))) {
										return flagrt.Call(compiler__compile_multi_arity, flagrt.Call(macflagKw_name, name_node), children, params_index)
									}
									return func() flagrt.Value {
										if flagrt.Ge(body_index, flagrt.NewLong(int64(flagrt.Count(children)))) {
											return func() flagrt.Value {
												flagrt.Throw(flagrt.NewMap(macflagKw_message, flagrt.NewString("defmacro expects name, optional docstring, vector params, and body"), macflagKw_data, flagrt.NewMap(macflagKw_form, expr)))
												return flagrt.NilValue()
											}()
										}
										return func() flagrt.Value {
											var params_node = flagrt.Call(compiler__nth_node, children, params_index)
											var param_spec = flagrt.Call(compiler__parse_macro_params, params_node)
											return flagrt.NewMap(macflagKw_name, flagrt.Call(macflagKw_name, name_node), macflagKw_params, flagrt.Call(macflagKw_params, param_spec), macflagKw_rest_param, flagrt.Call(macflagKw_rest_param, param_spec), macflagKw_body, flagrt.Call(compiler__nth_node, children, body_index), macflagKw_arities, macflagVec)
										}()
									}()
								}()
							}()
						}()
					}()
				}()
			}()
		}()
	}()
}

func compiler__compile_defmacro_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__compile_defmacro expects exactly 1 arguments")
	}
	return compiler__compile_defmacro_arity_1(args[0])
}

func compiler__bind_macro_args_arity_2(arity flagrt.Value, args flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			var params = flagrt.Call(macflagKw_params, arity)
			var rest_param = flagrt.Call(macflagKw_rest_param, arity)
			return func() flagrt.Value {
				if flagrt.IsTruthy(func() flagrt.Value {
					if !(flagrt.IsTruthy(flagrt.NewBool(flagrt.IsNil(rest_param)))) {
						return flagrt.NewBool(flagrt.IsNil(rest_param))
					}
					return func() flagrt.Value {
						if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(flagrt.NewLong(int64(flagrt.Count(args))), flagrt.NewLong(int64(flagrt.Count(params)))))) {
							return flagrt.NewBool(false)
						}
						return flagrt.NewBool(true)
					}()
				}()) {
					return func() flagrt.Value {
						flagrt.Throw(flagrt.NewMap(macflagKw_message, flagrt.NewString(flagrt.Str("macro expects exactly ", flagrt.NewLong(int64(flagrt.Count(params))), " arguments")), macflagKw_data, flagrt.NewMap(macflagKw_expected, flagrt.NewLong(int64(flagrt.Count(params))), macflagKw_got, flagrt.NewLong(int64(flagrt.Count(args))))))
						return flagrt.NilValue()
					}()
				}
				return func() flagrt.Value {
					if flagrt.IsTruthy(func() flagrt.Value {
						if !(flagrt.IsTruthy(rest_param)) {
							return rest_param
						}
						return flagrt.NewBool(flagrt.Lt(flagrt.NewLong(int64(flagrt.Count(args))), flagrt.NewLong(int64(flagrt.Count(params)))))
					}()) {
						return func() flagrt.Value {
							flagrt.Throw(flagrt.NewMap(macflagKw_message, flagrt.NewString(flagrt.Str("macro expects at least ", flagrt.NewLong(int64(flagrt.Count(params))), " arguments")), macflagKw_data, flagrt.NewMap(macflagKw_expected, flagrt.NewLong(int64(flagrt.Count(params))), macflagKw_got, flagrt.NewLong(int64(flagrt.Count(args))))))
							return flagrt.NilValue()
						}()
					}
					return func() flagrt.Value {
						var names = params
						var remaining_args = args
						var values = macflagMap
						for {
							__loopResult := func() flagrt.Value {
								return func() flagrt.Value {
									if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(names))) {
										return flagrt.NewMap(macflagKw_values, values, macflagKw_rest_bindings, func() flagrt.Value {
											if flagrt.IsTruthy(rest_param) {
												return flagrt.NewMap(rest_param, remaining_args)
											}
											return macflagMap
										}())
									}
									return flagrt.NewRecur(flagrt.Rest(names), flagrt.Rest(remaining_args), flagrt.Assoc(values, flagrt.First(names), flagrt.First(remaining_args)))
								}()
							}()
							if __recurValues, __isRecur := flagrt.UnwrapRecur(__loopResult); __isRecur {
								if len(__recurValues) != 3 {
									panic("internal error: recur arity mismatch")
								}
								names = __recurValues[0]
								remaining_args = __recurValues[1]
								values = __recurValues[2]
								continue
							}
							return __loopResult
						}
					}()
				}()
			}()
		}()
	}()
}

func compiler__bind_macro_args_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 2 {
		panic("compiler__bind_macro_args expects exactly 2 arguments")
	}
	return compiler__bind_macro_args_arity_2(args[0], args[1])
}

func compiler__literal_kind_q_arity_1(kind flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(kind, macflagKw_keyword))) {
				return flagrt.NewBool(flagrt.Eq(kind, macflagKw_keyword))
			}
			if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(kind, macflagKw_string))) {
				return flagrt.NewBool(flagrt.Eq(kind, macflagKw_string))
			}
			if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(kind, macflagKw_char))) {
				return flagrt.NewBool(flagrt.Eq(kind, macflagKw_char))
			}
			if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(kind, macflagKw_int))) {
				return flagrt.NewBool(flagrt.Eq(kind, macflagKw_int))
			}
			if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(kind, macflagKw_bigint))) {
				return flagrt.NewBool(flagrt.Eq(kind, macflagKw_bigint))
			}
			if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(kind, macflagKw_float))) {
				return flagrt.NewBool(flagrt.Eq(kind, macflagKw_float))
			}
			if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(kind, macflagKw_ratio))) {
				return flagrt.NewBool(flagrt.Eq(kind, macflagKw_ratio))
			}
			return flagrt.NewBool(flagrt.Eq(kind, macflagKw_quoted_symbol))
		}()
	}()
}

func compiler__literal_kind_q_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__literal_kind_q expects exactly 1 arguments")
	}
	return compiler__literal_kind_q_arity_1(args[0])
}

func compiler__macro_case_clause_arity_1(expr flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			if flagrt.IsTruthy(func() flagrt.Value {
				if flagrt.IsTruthy(flagrt.Call(compiler__list_node_q, expr)) {
					return flagrt.Call(compiler__list_node_q, expr)
				}
				return flagrt.Call(compiler__vector_node_q, expr)
			}()) {
				return func() flagrt.Value {
					var elems = flagrt.Call(compiler__node_children, expr)
					return func() flagrt.Value {
						if flagrt.Lt(flagrt.NewLong(int64(flagrt.Count(elems))), flagrt.NewLong(2)) {
							return flagrt.NilValue()
						}
						return func() flagrt.Value {
							if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(flagrt.NewLong(2), flagrt.NewLong(int64(flagrt.Count(elems)))))) {
								return flagrt.NewMap(macflagKw_pattern, flagrt.First(elems), macflagKw_body, flagrt.Call(stdlib__second, elems))
							}
							return flagrt.NewMap(macflagKw_pattern, flagrt.First(elems), macflagKw_body, flagrt.Call(compiler__make_list, flagrt.Cons(flagrt.Call(compiler__make_symbol, macflagStr_do), flagrt.Rest(elems))))
						}()
					}()
				}()
			}
			return flagrt.NilValue()
		}()
	}()
}

func compiler__macro_case_clause_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__macro_case_clause expects exactly 1 arguments")
	}
	return compiler__macro_case_clause_arity_1(args[0])
}

func compiler__expand_defrecord_macro_arity_1(args flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			if flagrt.IsTruthy(func() flagrt.Value {
				if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(flagrt.NewLong(2), flagrt.NewLong(int64(flagrt.Count(args)))))) {
					return flagrt.NewBool(false)
				}
				return flagrt.NewBool(true)
			}()) {
				return func() flagrt.Value {
					flagrt.Throw(flagrt.NewMap(macflagKw_message, flagrt.NewString("macro-defrecord expects a record name and field vector"), macflagKw_data, macflagMap))
					return flagrt.NilValue()
				}()
			}
			return flagrt.Call(compiler__make_list, flagrt.NewArray(flagrt.Call(compiler__make_symbol, macflagStr_defrecord_), flagrt.First(args), flagrt.Call(stdlib__second, args)))
		}()
	}()
}

func compiler__expand_defrecord_macro_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__expand_defrecord_macro expects exactly 1 arguments")
	}
	return compiler__expand_defrecord_macro_arity_1(args[0])
}

func compiler__macro_op_arity_5(op flagrt.Value, a flagrt.Value, b flagrt.Value, c flagrt.Value, d flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(op, macflagKw_seq))) {
				return func() flagrt.Value {
					var pats = a
					var remaining = b
					var bindings = c
					var rest_bindings = d
					for {
						__loopResult := func() flagrt.Value {
							return func() flagrt.Value {
								if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(pats))) {
									return func() flagrt.Value {
										if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(remaining))) {
											return flagrt.NewMap(macflagKw_matched, flagrt.NewBool(true), macflagKw_bindings, bindings, macflagKw_rest_bindings, rest_bindings)
										}
										return macflagMap_1
									}()
								}
								return func() flagrt.Value {
									var pat = flagrt.First(pats)
									return func() flagrt.Value {
										if flagrt.IsTruthy(func() flagrt.Value {
											if !(flagrt.IsTruthy(flagrt.Call(compiler__symbol_node_q, pat))) {
												return flagrt.Call(compiler__symbol_node_q, pat)
											}
											return flagrt.NewBool(flagrt.Eq(flagrt.NewString("&"), flagrt.Call(macflagKw_name, pat)))
										}()) {
											return func() flagrt.Value {
												var tail = flagrt.Rest(pats)
												return func() flagrt.Value {
													if flagrt.IsTruthy(func() flagrt.Value {
														if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(flagrt.NewLong(1), flagrt.NewLong(int64(flagrt.Count(tail)))))) {
															return flagrt.NewBool(false)
														}
														return flagrt.NewBool(true)
													}()) {
														return func() flagrt.Value {
															flagrt.Throw(flagrt.NewMap(macflagKw_message, flagrt.NewString("macro-case rest capture must be in the penultimate position"), macflagKw_data, macflagMap))
															return flagrt.NilValue()
														}()
													}
													return func() flagrt.Value {
														var name_node = flagrt.First(tail)
														return func() flagrt.Value {
															if flagrt.IsTruthy(func() flagrt.Value {
																if flagrt.IsTruthy(func() flagrt.Value {
																	if flagrt.IsTruthy(flagrt.Call(compiler__symbol_node_q, name_node)) {
																		return flagrt.NewBool(false)
																	}
																	return flagrt.NewBool(true)
																}()) {
																	return func() flagrt.Value {
																		if flagrt.IsTruthy(flagrt.Call(compiler__symbol_node_q, name_node)) {
																			return flagrt.NewBool(false)
																		}
																		return flagrt.NewBool(true)
																	}()
																}
																if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(flagrt.NewString(""), flagrt.Call(macflagKw_name, name_node)))) {
																	return flagrt.NewBool(flagrt.Eq(flagrt.NewString(""), flagrt.Call(macflagKw_name, name_node)))
																}
																return flagrt.NewBool(flagrt.Eq(flagrt.NewString("&"), flagrt.Call(macflagKw_name, name_node)))
															}()) {
																return func() flagrt.Value {
																	flagrt.Throw(flagrt.NewMap(macflagKw_message, flagrt.NewString("macro-case rest capture expects a symbol name"), macflagKw_data, macflagMap))
																	return flagrt.NilValue()
																}()
															}
															return flagrt.NewMap(macflagKw_matched, flagrt.NewBool(true), macflagKw_bindings, bindings, macflagKw_rest_bindings, flagrt.Assoc(rest_bindings, flagrt.Call(macflagKw_name, name_node), remaining))
														}()
													}()
												}()
											}()
										}
										return func() flagrt.Value {
											if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(remaining))) {
												return macflagMap_1
											}
											return func() flagrt.Value {
												var result = compiler__macro_op_arity_5(macflagKw_pat, pat, flagrt.NewArray(flagrt.First(remaining)), bindings, rest_bindings)
												return func() flagrt.Value {
													if flagrt.IsTruthy(func() flagrt.Value {
														if flagrt.IsTruthy(flagrt.Call(macflagKw_matched, result)) {
															return flagrt.NewBool(false)
														}
														return flagrt.NewBool(true)
													}()) {
														return macflagMap_1
													}
													return flagrt.NewRecur(flagrt.Rest(pats), flagrt.Rest(remaining), flagrt.Call(macflagKw_bindings, result), flagrt.Call(macflagKw_rest_bindings, result))
												}()
											}()
										}()
									}()
								}()
							}()
						}()
						if __recurValues, __isRecur := flagrt.UnwrapRecur(__loopResult); __isRecur {
							if len(__recurValues) != 4 {
								panic("internal error: recur arity mismatch")
							}
							pats = __recurValues[0]
							remaining = __recurValues[1]
							bindings = __recurValues[2]
							rest_bindings = __recurValues[3]
							continue
						}
						return __loopResult
					}
				}()
			}
			return func() flagrt.Value {
				if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(op, macflagKw_pat))) {
					return func() flagrt.Value {
						var pat = flagrt.Call(compiler__unwrap_meta, a)
						var items = func() flagrt.Value {
							if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(b))) {
								return b
							}
							return func() flagrt.Value {
								var remaining = b
								var out = macflagVec
								for {
									__loopResult := func() flagrt.Value {
										return func() flagrt.Value {
											if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(remaining))) {
												return out
											}
											return flagrt.NewRecur(flagrt.Rest(remaining), flagrt.Conj(out, flagrt.Call(compiler__unwrap_meta, flagrt.Call(compiler__unwrap_literal, flagrt.First(remaining)))))
										}()
									}()
									if __recurValues, __isRecur := flagrt.UnwrapRecur(__loopResult); __isRecur {
										if len(__recurValues) != 2 {
											panic("internal error: recur arity mismatch")
										}
										remaining = __recurValues[0]
										out = __recurValues[1]
										continue
									}
									return __loopResult
								}
							}()
						}()
						var bindings = c
						var rest_bindings = d
						return func() flagrt.Value {
							if flagrt.IsTruthy(flagrt.Call(compiler__symbol_node_q, pat)) {
								return func() flagrt.Value {
									if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(flagrt.NewString("_"), flagrt.Call(macflagKw_name, pat)))) {
										return func() flagrt.Value {
											if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(flagrt.NewLong(1), flagrt.NewLong(int64(flagrt.Count(items)))))) {
												return flagrt.NewMap(macflagKw_matched, flagrt.NewBool(true), macflagKw_bindings, bindings, macflagKw_rest_bindings, rest_bindings)
											}
											return macflagMap_1
										}()
									}
									return func() flagrt.Value {
										if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(flagrt.NewString("&"), flagrt.Call(macflagKw_name, pat)))) {
											return func() flagrt.Value {
												flagrt.Throw(flagrt.NewMap(macflagKw_message, flagrt.NewString("macro-case pattern cannot use bare &"), macflagKw_data, macflagMap))
												return flagrt.NilValue()
											}()
										}
										return func() flagrt.Value {
											if flagrt.IsTruthy(flagrt.NewBool(true)) {
												return func() flagrt.Value {
													if flagrt.IsTruthy(func() flagrt.Value {
														if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(flagrt.NewLong(1), flagrt.NewLong(int64(flagrt.Count(items)))))) {
															return flagrt.NewBool(false)
														}
														return flagrt.NewBool(true)
													}()) {
														return macflagMap_1
													}
													return func() flagrt.Value {
														if flagrt.IsTruthy(flagrt.NewBool(flagrt.Contains(bindings, flagrt.Call(macflagKw_name, pat)))) {
															return func() flagrt.Value {
																if flagrt.IsTruthy(flagrt.Call(compiler__node_equal_q, flagrt.Call(flagrt.BuiltinFunction("get"), bindings, flagrt.Call(macflagKw_name, pat)), flagrt.First(items))) {
																	return flagrt.NewMap(macflagKw_matched, flagrt.NewBool(true), macflagKw_bindings, bindings, macflagKw_rest_bindings, rest_bindings)
																}
																return macflagMap_1
															}()
														}
														return flagrt.NewMap(macflagKw_matched, flagrt.NewBool(true), macflagKw_bindings, flagrt.Assoc(bindings, flagrt.Call(macflagKw_name, pat), flagrt.First(items)), macflagKw_rest_bindings, rest_bindings)
													}()
												}()
											}
											return flagrt.NilValue()
										}()
									}()
								}()
							}
							return func() flagrt.Value {
								if flagrt.IsTruthy(flagrt.Call(compiler__literal_kind_q, flagrt.Call(macflagKw_kind, pat))) {
									return func() flagrt.Value {
										if flagrt.IsTruthy(func() flagrt.Value {
											if !(flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(flagrt.NewLong(1), flagrt.NewLong(int64(flagrt.Count(items))))))) {
												return flagrt.NewBool(flagrt.Eq(flagrt.NewLong(1), flagrt.NewLong(int64(flagrt.Count(items)))))
											}
											return flagrt.Call(compiler__node_equal_q, pat, flagrt.First(items))
										}()) {
											return flagrt.NewMap(macflagKw_matched, flagrt.NewBool(true), macflagKw_bindings, bindings, macflagKw_rest_bindings, rest_bindings)
										}
										return macflagMap_1
									}()
								}
								return func() flagrt.Value {
									if flagrt.IsTruthy(flagrt.Call(compiler__list_node_q, pat)) {
										return func() flagrt.Value {
											if flagrt.IsTruthy(func() flagrt.Value {
												if !(flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(flagrt.NewLong(1), flagrt.NewLong(int64(flagrt.Count(items))))))) {
													return flagrt.NewBool(flagrt.Eq(flagrt.NewLong(1), flagrt.NewLong(int64(flagrt.Count(items)))))
												}
												return flagrt.Call(compiler__list_node_q, flagrt.Call(compiler__unwrap_meta, flagrt.First(items)))
											}()) {
												return compiler__macro_op_arity_5(macflagKw_seq, flagrt.Call(compiler__node_children, pat), flagrt.Call(compiler__node_children, flagrt.Call(compiler__unwrap_meta, flagrt.First(items))), bindings, rest_bindings)
											}
											return compiler__macro_op_arity_5(macflagKw_seq, flagrt.Call(compiler__node_children, pat), items, bindings, rest_bindings)
										}()
									}
									return func() flagrt.Value {
										if flagrt.IsTruthy(flagrt.Call(compiler__vector_node_q, pat)) {
											return func() flagrt.Value {
												if flagrt.IsTruthy(func() flagrt.Value {
													if !(flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(flagrt.NewLong(1), flagrt.NewLong(int64(flagrt.Count(items))))))) {
														return flagrt.NewBool(flagrt.Eq(flagrt.NewLong(1), flagrt.NewLong(int64(flagrt.Count(items)))))
													}
													return flagrt.Call(compiler__vector_node_q, flagrt.Call(compiler__unwrap_meta, flagrt.First(items)))
												}()) {
													return compiler__macro_op_arity_5(macflagKw_seq, flagrt.Call(compiler__node_children, pat), flagrt.Call(compiler__node_children, flagrt.Call(compiler__unwrap_meta, flagrt.First(items))), bindings, rest_bindings)
												}
												return compiler__macro_op_arity_5(macflagKw_seq, flagrt.Call(compiler__node_children, pat), items, bindings, rest_bindings)
											}()
										}
										return func() flagrt.Value {
											if flagrt.IsTruthy(flagrt.Call(compiler__pipe_vector_node_q, pat)) {
												return func() flagrt.Value {
													if flagrt.IsTruthy(func() flagrt.Value {
														if !(flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(flagrt.NewLong(1), flagrt.NewLong(int64(flagrt.Count(items))))))) {
															return flagrt.NewBool(flagrt.Eq(flagrt.NewLong(1), flagrt.NewLong(int64(flagrt.Count(items)))))
														}
														return flagrt.Call(compiler__pipe_vector_node_q, flagrt.Call(compiler__unwrap_meta, flagrt.First(items)))
													}()) {
														return compiler__macro_op_arity_5(macflagKw_seq, flagrt.Call(compiler__node_children, pat), flagrt.Call(compiler__node_children, flagrt.Call(compiler__unwrap_meta, flagrt.First(items))), bindings, rest_bindings)
													}
													return compiler__macro_op_arity_5(macflagKw_seq, flagrt.Call(compiler__node_children, pat), items, bindings, rest_bindings)
												}()
											}
											return func() flagrt.Value {
												if flagrt.IsTruthy(flagrt.NewBool(true)) {
													return func() flagrt.Value {
														if flagrt.IsTruthy(func() flagrt.Value {
															if !(flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(flagrt.NewLong(1), flagrt.NewLong(int64(flagrt.Count(items))))))) {
																return flagrt.NewBool(flagrt.Eq(flagrt.NewLong(1), flagrt.NewLong(int64(flagrt.Count(items)))))
															}
															return flagrt.Call(compiler__node_equal_q, pat, flagrt.First(items))
														}()) {
															return flagrt.NewMap(macflagKw_matched, flagrt.NewBool(true), macflagKw_bindings, bindings, macflagKw_rest_bindings, rest_bindings)
														}
														return macflagMap_1
													}()
												}
												return flagrt.NilValue()
											}()
										}()
									}()
								}()
							}()
						}()
					}()
				}
				return func() flagrt.Value {
					if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(op, macflagKw_case))) {
						return func() flagrt.Value {
							if flagrt.Lt(flagrt.NewLong(int64(flagrt.Count(a))), flagrt.NewLong(2)) {
								return func() flagrt.Value {
									flagrt.Throw(flagrt.NewMap(macflagKw_message, flagrt.NewString("macro-case expects a target form and at least one clause"), macflagKw_data, macflagMap))
									return flagrt.NilValue()
								}()
							}
							return func() flagrt.Value {
								var target_expr = flagrt.First(a)
								return func() flagrt.Value {
									if flagrt.IsTruthy(func() flagrt.Value {
										if flagrt.IsTruthy(flagrt.Call(compiler__list_node_q, target_expr)) {
											return flagrt.NewBool(false)
										}
										return flagrt.NewBool(true)
									}()) {
										return func() flagrt.Value {
											flagrt.Throw(flagrt.NewMap(macflagKw_message, flagrt.NewString("macro-case expects a list target form"), macflagKw_data, macflagMap))
											return flagrt.NilValue()
										}()
									}
									return func() flagrt.Value {
										var target_elems = flagrt.Call(compiler__node_children, target_expr)
										var target = func() flagrt.Value {
											if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(target_elems))) {
												return macflagVec
											}
											return flagrt.Rest(target_elems)
										}()
										return func() flagrt.Value {
											var clauses = flagrt.Rest(a)
											for {
												__loopResult := func() flagrt.Value {
													return func() flagrt.Value {
														if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(clauses))) {
															return func() flagrt.Value {
																flagrt.Throw(flagrt.NewMap(macflagKw_message, flagrt.NewString("macro-case had no matching clause"), macflagKw_data, macflagMap))
																return flagrt.NilValue()
															}()
														}
														return func() flagrt.Value {
															var clause = flagrt.Call(compiler__macro_case_clause, flagrt.First(clauses))
															return func() flagrt.Value {
																if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsNil(clause))) {
																	return func() flagrt.Value {
																		flagrt.Throw(flagrt.NewMap(macflagKw_message, flagrt.NewString("macro-case clauses must be ([pattern] body) lists"), macflagKw_data, macflagMap))
																		return flagrt.NilValue()
																	}()
																}
																return func() flagrt.Value {
																	var result = compiler__macro_op_arity_5(macflagKw_pat, flagrt.Call(macflagKw_pattern, clause), target, macflagMap, macflagMap)
																	return func() flagrt.Value {
																		if flagrt.IsTruthy(flagrt.Call(macflagKw_matched, result)) {
																			return compiler__macro_op_arity_5(macflagKw_subst, flagrt.Call(macflagKw_body, clause), flagrt.Call(macflagKw_bindings, result), flagrt.Call(macflagKw_rest_bindings, result), flagrt.NilValue())
																		}
																		return flagrt.NewRecur(flagrt.Rest(clauses))
																	}()
																}()
															}()
														}()
													}()
												}()
												if __recurValues, __isRecur := flagrt.UnwrapRecur(__loopResult); __isRecur {
													if len(__recurValues) != 1 {
														panic("internal error: recur arity mismatch")
													}
													clauses = __recurValues[0]
													continue
												}
												return __loopResult
											}
										}()
									}()
								}()
							}()
						}()
					}
					return func() flagrt.Value {
						if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(op, macflagKw_subst))) {
							return func() flagrt.Value {
								var expr = a
								var values = b
								var rest_bindings = c
								return func() flagrt.Value {
									if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(macflagKw_macro_literal, flagrt.Call(macflagKw_kind, expr)))) {
										return expr
									}
									return func() flagrt.Value {
										if flagrt.IsTruthy(flagrt.Call(compiler__symbol_node_q, expr)) {
											return func() flagrt.Value {
												var replacement = flagrt.Call(flagrt.BuiltinFunction("get"), values, flagrt.Call(macflagKw_name, expr))
												return func() flagrt.Value {
													if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsNil(replacement))) {
														return expr
													}
													return flagrt.Call(compiler__wrap_literal, replacement)
												}()
											}()
										}
										return func() flagrt.Value {
											if flagrt.IsTruthy(flagrt.Call(compiler__splice_node_q, expr)) {
												return func() flagrt.Value {
													var out = func() flagrt.Value {
														var remaining = flagrt.Call(compiler__node_children, expr)
														var acc = macflagVec
														for {
															__loopResult := func() flagrt.Value {
																return func() flagrt.Value {
																	if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(remaining))) {
																		return acc
																	}
																	return func() flagrt.Value {
																		var child = flagrt.First(remaining)
																		var rest_items = func() flagrt.Value {
																			if flagrt.IsTruthy(flagrt.Call(compiler__symbol_node_q, child)) {
																				return flagrt.Call(flagrt.BuiltinFunction("get"), rest_bindings, flagrt.Call(macflagKw_name, child))
																			}
																			return flagrt.NilValue()
																		}()
																		return func() flagrt.Value {
																			if flagrt.IsTruthy(func() flagrt.Value {
																				if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsNil(rest_items))) {
																					return flagrt.NewBool(false)
																				}
																				return flagrt.NewBool(true)
																			}()) {
																				return flagrt.NewRecur(flagrt.Rest(remaining), func() flagrt.Value {
																					var items = rest_items
																					var out = acc
																					for {
																						__loopResult := func() flagrt.Value {
																							return func() flagrt.Value {
																								if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(items))) {
																									return out
																								}
																								return flagrt.NewRecur(flagrt.Rest(items), flagrt.Conj(out, flagrt.Call(compiler__wrap_literal, flagrt.First(items))))
																							}()
																						}()
																						if __recurValues, __isRecur := flagrt.UnwrapRecur(__loopResult); __isRecur {
																							if len(__recurValues) != 2 {
																								panic("internal error: recur arity mismatch")
																							}
																							items = __recurValues[0]
																							out = __recurValues[1]
																							continue
																						}
																						return __loopResult
																					}
																				}())
																			}
																			return flagrt.NewRecur(flagrt.Rest(remaining), flagrt.Conj(acc, compiler__macro_op_arity_5(macflagKw_subst, child, values, rest_bindings, flagrt.NilValue())))
																		}()
																	}()
																}()
															}()
															if __recurValues, __isRecur := flagrt.UnwrapRecur(__loopResult); __isRecur {
																if len(__recurValues) != 2 {
																	panic("internal error: recur arity mismatch")
																}
																remaining = __recurValues[0]
																acc = __recurValues[1]
																continue
															}
															return __loopResult
														}
													}()
													return func() flagrt.Value {
														if flagrt.IsTruthy(func() flagrt.Value {
															if !(flagrt.IsTruthy(flagrt.Call(compiler__list_node_q, expr))) {
																return flagrt.Call(compiler__list_node_q, expr)
															}
															if !(flagrt.IsTruthy(func() flagrt.Value {
																if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(out))) {
																	return flagrt.NewBool(false)
																}
																return flagrt.NewBool(true)
															}())) {
																return func() flagrt.Value {
																	if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(out))) {
																		return flagrt.NewBool(false)
																	}
																	return flagrt.NewBool(true)
																}()
															}
															return flagrt.Call(compiler__symbol_node_q, flagrt.First(out))
														}()) {
															return func() flagrt.Value {
																if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(flagrt.NewString("macro-case"), flagrt.Call(macflagKw_name, flagrt.First(out))))) {
																	return compiler__macro_op_arity_5(macflagKw_case, flagrt.Rest(out), flagrt.NilValue(), flagrt.NilValue(), flagrt.NilValue())
																}
																return func() flagrt.Value {
																	if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(flagrt.NewString("macro-defrecord"), flagrt.Call(macflagKw_name, flagrt.First(out))))) {
																		return flagrt.Call(compiler__expand_defrecord_macro, flagrt.Rest(out))
																	}
																	return func() flagrt.Value {
																		if flagrt.IsTruthy(flagrt.NewBool(true)) {
																			return flagrt.Call(compiler__with_children, expr, out)
																		}
																		return flagrt.NilValue()
																	}()
																}()
															}()
														}
														return flagrt.Call(compiler__with_children, expr, out)
													}()
												}()
											}
											return func() flagrt.Value {
												if flagrt.IsTruthy(func() flagrt.Value {
													if flagrt.IsTruthy(flagrt.Call(compiler__map_node_q, expr)) {
														return flagrt.Call(compiler__map_node_q, expr)
													}
													return flagrt.Call(compiler__set_node_q, expr)
												}()) {
													return flagrt.Call(compiler__with_children, expr, func() flagrt.Value {
														var remaining = flagrt.Call(compiler__node_children, expr)
														var acc = macflagVec
														for {
															__loopResult := func() flagrt.Value {
																return func() flagrt.Value {
																	if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(remaining))) {
																		return acc
																	}
																	return flagrt.NewRecur(flagrt.Rest(remaining), flagrt.Conj(acc, compiler__macro_op_arity_5(macflagKw_subst, flagrt.First(remaining), values, rest_bindings, flagrt.NilValue())))
																}()
															}()
															if __recurValues, __isRecur := flagrt.UnwrapRecur(__loopResult); __isRecur {
																if len(__recurValues) != 2 {
																	panic("internal error: recur arity mismatch")
																}
																remaining = __recurValues[0]
																acc = __recurValues[1]
																continue
															}
															return __loopResult
														}
													}())
												}
												return func() flagrt.Value {
													if flagrt.IsTruthy(flagrt.Call(compiler__hash_fn_node_q, expr)) {
														return flagrt.Assoc(expr, macflagKw_body, compiler__macro_op_arity_5(macflagKw_subst, flagrt.Call(macflagKw_body, expr), values, rest_bindings, flagrt.NilValue()))
													}
													return func() flagrt.Value {
														if flagrt.IsTruthy(flagrt.Call(compiler__meta_node_q, expr)) {
															return flagrt.Assoc(expr, macflagKw_meta, compiler__macro_op_arity_5(macflagKw_subst, flagrt.Call(macflagKw_meta, expr), values, rest_bindings, flagrt.NilValue()), macflagKw_target, compiler__macro_op_arity_5(macflagKw_subst, flagrt.Call(macflagKw_target, expr), values, rest_bindings, flagrt.NilValue()))
														}
														return expr
													}()
												}()
											}()
										}()
									}()
								}()
							}()
						}
						return func() flagrt.Value {
							if flagrt.IsTruthy(flagrt.NewBool(true)) {
								return func() flagrt.Value {
									flagrt.Throw(flagrt.NewMap(macflagKw_message, flagrt.NewString("unknown macro-op"), macflagKw_data, flagrt.NewMap(macflagKw_op, op)))
									return flagrt.NilValue()
								}()
							}
							return flagrt.NilValue()
						}()
					}()
				}()
			}()
		}()
	}()
}

func compiler__macro_op_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 5 {
		panic("compiler__macro_op expects exactly 5 arguments")
	}
	return compiler__macro_op_arity_5(args[0], args[1], args[2], args[3], args[4])
}

func compiler__substitute_node_arity_3(expr flagrt.Value, values flagrt.Value, rest_bindings flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return flagrt.Call(compiler__macro_op, macflagKw_subst, expr, values, rest_bindings, flagrt.NilValue())
	}()
}

func compiler__substitute_node_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 3 {
		panic("compiler__substitute_node expects exactly 3 arguments")
	}
	return compiler__substitute_node_arity_3(args[0], args[1], args[2])
}

func compiler__apply_macro_arity_arity_2(arity flagrt.Value, args flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			var bindings = flagrt.Call(compiler__bind_macro_args, arity, args)
			return flagrt.Call(compiler__unwrap_literal_tree, flagrt.Call(compiler__substitute_node, flagrt.Call(macflagKw_body, arity), flagrt.Call(macflagKw_values, bindings), flagrt.Call(macflagKw_rest_bindings, bindings)))
		}()
	}()
}

func compiler__apply_macro_arity_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 2 {
		panic("compiler__apply_macro_arity expects exactly 2 arguments")
	}
	return compiler__apply_macro_arity_arity_2(args[0], args[1])
}

func compiler__apply_multi_arity_arity_2(macro flagrt.Value, args flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			var remaining = flagrt.Call(macflagKw_arities, macro)
			var rest_arity = flagrt.NilValue()
			for {
				__loopResult := func() flagrt.Value {
					return func() flagrt.Value {
						if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(remaining))) {
							return func() flagrt.Value {
								if flagrt.IsTruthy(func() flagrt.Value {
									if !(flagrt.IsTruthy(rest_arity)) {
										return rest_arity
									}
									return flagrt.NewBool(flagrt.Ge(flagrt.NewLong(int64(flagrt.Count(args))), flagrt.NewLong(int64(flagrt.Count(flagrt.Call(macflagKw_params, rest_arity))))))
								}()) {
									return flagrt.Call(compiler__apply_macro_arity, rest_arity, args)
								}
								return func() flagrt.Value {
									flagrt.Throw(flagrt.NewMap(macflagKw_message, flagrt.NewString("macro expects arguments"), macflagKw_data, flagrt.NewMap(macflagKw_got, flagrt.NewLong(int64(flagrt.Count(args))))))
									return flagrt.NilValue()
								}()
							}()
						}
						return func() flagrt.Value {
							var arity = flagrt.First(remaining)
							return func() flagrt.Value {
								if flagrt.IsTruthy(func() flagrt.Value {
									if !(flagrt.IsTruthy(flagrt.NewBool(flagrt.IsNil(flagrt.Call(macflagKw_rest_param, arity))))) {
										return flagrt.NewBool(flagrt.IsNil(flagrt.Call(macflagKw_rest_param, arity)))
									}
									return flagrt.NewBool(flagrt.Eq(flagrt.NewLong(int64(flagrt.Count(args))), flagrt.NewLong(int64(flagrt.Count(flagrt.Call(macflagKw_params, arity))))))
								}()) {
									return flagrt.Call(compiler__apply_macro_arity, arity, args)
								}
								return flagrt.NewRecur(flagrt.Rest(remaining), func() flagrt.Value {
									if flagrt.IsTruthy(flagrt.Call(macflagKw_rest_param, arity)) {
										return arity
									}
									return rest_arity
								}())
							}()
						}()
					}()
				}()
				if __recurValues, __isRecur := flagrt.UnwrapRecur(__loopResult); __isRecur {
					if len(__recurValues) != 2 {
						panic("internal error: recur arity mismatch")
					}
					remaining = __recurValues[0]
					rest_arity = __recurValues[1]
					continue
				}
				return __loopResult
			}
		}()
	}()
}

func compiler__apply_multi_arity_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 2 {
		panic("compiler__apply_multi_arity expects exactly 2 arguments")
	}
	return compiler__apply_multi_arity_arity_2(args[0], args[1])
}

func compiler__apply_macro_arity_2(macro flagrt.Value, args flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(flagrt.Call(macflagKw_arities, macro)))) {
				return flagrt.Call(compiler__apply_macro_arity, flagrt.NewMap(macflagKw_params, flagrt.Call(macflagKw_params, macro), macflagKw_rest_param, flagrt.Call(macflagKw_rest_param, macro), macflagKw_body, flagrt.Call(macflagKw_body, macro)), args)
			}
			return flagrt.Call(compiler__apply_multi_arity, macro, args)
		}()
	}()
}

func compiler__apply_macro_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 2 {
		panic("compiler__apply_macro expects exactly 2 arguments")
	}
	return compiler__apply_macro_arity_2(args[0], args[1])
}

func compiler__expand_node_arity_3(expr flagrt.Value, macros flagrt.Value, depth flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			if flagrt.Gt(depth, flagrt.NewLong(100)) {
				return func() flagrt.Value {
					flagrt.Throw(flagrt.NewMap(macflagKw_message, flagrt.NewString("macro expansion depth exceeded"), macflagKw_data, flagrt.NewMap(macflagKw_expr, expr)))
					return flagrt.NilValue()
				}()
			}
			return func() flagrt.Value {
				if flagrt.IsTruthy(flagrt.Call(compiler__list_node_q, expr)) {
					return func() flagrt.Value {
						var children = flagrt.Call(compiler__node_children, expr)
						return func() flagrt.Value {
							if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(children))) {
								return expr
							}
							return func() flagrt.Value {
								var head = flagrt.First(children)
								var macro = func() flagrt.Value {
									if flagrt.IsTruthy(flagrt.Call(compiler__symbol_node_q, head)) {
										return flagrt.Call(flagrt.BuiltinFunction("get"), macros, flagrt.Call(macflagKw_name, head))
									}
									return flagrt.NilValue()
								}()
								return func() flagrt.Value {
									if flagrt.IsTruthy(macro) {
										return compiler__expand_node_arity_3(flagrt.Call(compiler__apply_macro, macro, flagrt.Rest(children)), macros, flagrt.Add(depth, flagrt.NewLong(1)))
									}
									return flagrt.Call(compiler__with_children, expr, func() flagrt.Value {
										var remaining = children
										var out = macflagVec
										for {
											__loopResult := func() flagrt.Value {
												return func() flagrt.Value {
													if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(remaining))) {
														return out
													}
													return flagrt.NewRecur(flagrt.Rest(remaining), flagrt.Conj(out, compiler__expand_node_arity_3(flagrt.First(remaining), macros, depth)))
												}()
											}()
											if __recurValues, __isRecur := flagrt.UnwrapRecur(__loopResult); __isRecur {
												if len(__recurValues) != 2 {
													panic("internal error: recur arity mismatch")
												}
												remaining = __recurValues[0]
												out = __recurValues[1]
												continue
											}
											return __loopResult
										}
									}())
								}()
							}()
						}()
					}()
				}
				return func() flagrt.Value {
					if flagrt.IsTruthy(flagrt.Call(compiler__walk_node_q, expr)) {
						return flagrt.Call(compiler__with_children, expr, func() flagrt.Value {
							var remaining = flagrt.Call(compiler__node_children, expr)
							var out = macflagVec
							for {
								__loopResult := func() flagrt.Value {
									return func() flagrt.Value {
										if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(remaining))) {
											return out
										}
										return flagrt.NewRecur(flagrt.Rest(remaining), flagrt.Conj(out, compiler__expand_node_arity_3(flagrt.First(remaining), macros, depth)))
									}()
								}()
								if __recurValues, __isRecur := flagrt.UnwrapRecur(__loopResult); __isRecur {
									if len(__recurValues) != 2 {
										panic("internal error: recur arity mismatch")
									}
									remaining = __recurValues[0]
									out = __recurValues[1]
									continue
								}
								return __loopResult
							}
						}())
					}
					return func() flagrt.Value {
						if flagrt.IsTruthy(flagrt.Call(compiler__hash_fn_node_q, expr)) {
							return flagrt.Assoc(expr, macflagKw_body, compiler__expand_node_arity_3(flagrt.Call(macflagKw_body, expr), macros, depth))
						}
						return func() flagrt.Value {
							if flagrt.IsTruthy(flagrt.Call(compiler__meta_node_q, expr)) {
								return flagrt.Assoc(expr, macflagKw_meta, compiler__expand_node_arity_3(flagrt.Call(macflagKw_meta, expr), macros, depth), macflagKw_target, compiler__expand_node_arity_3(flagrt.Call(macflagKw_target, expr), macros, depth))
							}
							return expr
						}()
					}()
				}()
			}()
		}()
	}()
}

func compiler__expand_node_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 3 {
		panic("compiler__expand_node expects exactly 3 arguments")
	}
	return compiler__expand_node_arity_3(args[0], args[1], args[2])
}

func compiler__register_macro_arity_2(macros flagrt.Value, expr flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			var macro = flagrt.Call(compiler__compile_defmacro, expr)
			return flagrt.Assoc(macros, flagrt.Call(macflagKw_name, macro), macro)
		}()
	}()
}

func compiler__register_macro_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 2 {
		panic("compiler__register_macro expects exactly 2 arguments")
	}
	return compiler__register_macro_arity_2(args[0], args[1])
}

func compiler__expand_macros_arity_1(in flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		return func() flagrt.Value {
			var out = flagrt.Call(async__make_channel, flagrt.NewLong(64))
			_ = flagrt.Call(async__go_run, flagrt.NewFunction(func(args ...flagrt.Value) flagrt.Value {
				if len(args) != 0 {
					panic("fn expects exactly 0 arguments")
				}
				return func() flagrt.Value {
					return func() flagrt.Value {
						var __flag_try_result flagrt.Value
						defer func() {
							_ = func() flagrt.Value {
								return flagrt.Call(async__channel_close, out)
							}()
						}()
						func() {
							defer func() {
								r := recover()
								if r == nil {
									return
								}
								__flag_thrown := flagrt.PanicValue(r)
								if flagrt.CatchMatches("Exception", __flag_thrown) {
									__flag_try_result = func() flagrt.Value {
										var e = __flag_thrown
										_ = e
										return func() flagrt.Value {
											return flagrt.Call(async__channel_send, out, flagrt.NewMap(macflagKw_kind, macflagKw_error, macflagKw_message, flagrt.ExMessage(e)))
										}()
									}()
									return
								}
								panic(r)
							}()
							__flag_try_result = func() flagrt.Value {
								return func() flagrt.Value {
									var macros = macflagMap
									for {
										__loopResult := func() flagrt.Value {
											return func() flagrt.Value {
												var expr = flagrt.Call(async__channel_receive, in)
												return func() flagrt.Value {
													if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsNil(expr))) {
														return flagrt.NilValue()
													}
													return func() flagrt.Value {
														if flagrt.IsTruthy(flagrt.Call(compiler__macro_definition_q, expr)) {
															return flagrt.NewRecur(flagrt.Call(compiler__register_macro, macros, expr))
														}
														return func() flagrt.Value {
															var expanded = flagrt.Call(compiler__expand_node, expr, macros, flagrt.NewLong(0))
															return func() flagrt.Value {
																if flagrt.IsTruthy(flagrt.Call(compiler__macro_definition_q, expanded)) {
																	return flagrt.NewRecur(flagrt.Call(compiler__register_macro, macros, expanded))
																}
																return func() flagrt.Value {
																	_ = flagrt.Call(async__channel_send, out, expanded)
																	return flagrt.NewRecur(macros)
																}()
															}()
														}()
													}()
												}()
											}()
										}()
										if __recurValues, __isRecur := flagrt.UnwrapRecur(__loopResult); __isRecur {
											if len(__recurValues) != 1 {
												panic("internal error: recur arity mismatch")
											}
											macros = __recurValues[0]
											continue
										}
										return __loopResult
									}
								}()
							}()
						}()
						return __flag_try_result
					}()
				}()
			}))
			return out
		}()
	}()
}

func compiler__expand_macros_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__expand_macros expects exactly 1 arguments")
	}
	return compiler__expand_macros_arity_1(args[0])
}

var compiler__symbol_node_q = flagrt.NewFunction(compiler__symbol_node_q_variadic)
var compiler__list_node_q = flagrt.NewFunction(compiler__list_node_q_variadic)
var compiler__vector_node_q = flagrt.NewFunction(compiler__vector_node_q_variadic)
var compiler__pipe_vector_node_q = flagrt.NewFunction(compiler__pipe_vector_node_q_variadic)
var compiler__map_node_q = flagrt.NewFunction(compiler__map_node_q_variadic)
var compiler__set_node_q = flagrt.NewFunction(compiler__set_node_q_variadic)
var compiler__hash_fn_node_q = flagrt.NewFunction(compiler__hash_fn_node_q_variadic)
var compiler__meta_node_q = flagrt.NewFunction(compiler__meta_node_q_variadic)
var compiler__string_node_q = flagrt.NewFunction(compiler__string_node_q_variadic)
var compiler__unwrap_meta = flagrt.NewFunction(compiler__unwrap_meta_variadic)
var compiler__node_children = flagrt.NewFunction(compiler__node_children_variadic)
var compiler__with_children = flagrt.NewFunction(compiler__with_children_variadic)
var compiler__splice_node_q = flagrt.NewFunction(compiler__splice_node_q_variadic)
var compiler__walk_node_q = flagrt.NewFunction(compiler__walk_node_q_variadic)
var compiler__make_symbol = flagrt.NewFunction(compiler__make_symbol_variadic)
var compiler__make_list = flagrt.NewFunction(compiler__make_list_variadic)
var compiler__wrap_literal = flagrt.NewFunction(compiler__wrap_literal_variadic)
var compiler__unwrap_literal = flagrt.NewFunction(compiler__unwrap_literal_variadic)
var compiler__unwrap_literal_tree = flagrt.NewFunction(compiler__unwrap_literal_tree_variadic)
var compiler__macro_definition_q = flagrt.NewFunction(compiler__macro_definition_q_variadic)
var compiler__append_all = flagrt.NewFunction(compiler__append_all_variadic)
var compiler__nth_node = flagrt.NewFunction(compiler__nth_node_variadic)
var compiler__node_equal_q = flagrt.NewFunction(compiler__node_equal_q_variadic)
var compiler__parse_macro_params = flagrt.NewFunction(compiler__parse_macro_params_variadic)
var compiler__compile_multi_arity = flagrt.NewFunction(compiler__compile_multi_arity_variadic)
var compiler__compile_defmacro = flagrt.NewFunction(compiler__compile_defmacro_variadic)
var compiler__bind_macro_args = flagrt.NewFunction(compiler__bind_macro_args_variadic)
var compiler__literal_kind_q = flagrt.NewFunction(compiler__literal_kind_q_variadic)
var compiler__macro_case_clause = flagrt.NewFunction(compiler__macro_case_clause_variadic)
var compiler__expand_defrecord_macro = flagrt.NewFunction(compiler__expand_defrecord_macro_variadic)
var compiler__macro_op = flagrt.NewFunction(compiler__macro_op_variadic)
var compiler__substitute_node = flagrt.NewFunction(compiler__substitute_node_variadic)
var compiler__apply_macro_arity = flagrt.NewFunction(compiler__apply_macro_arity_variadic)
var compiler__apply_multi_arity = flagrt.NewFunction(compiler__apply_multi_arity_variadic)
var compiler__apply_macro = flagrt.NewFunction(compiler__apply_macro_variadic)
var compiler__expand_node = flagrt.NewFunction(compiler__expand_node_variadic)
var compiler__register_macro = flagrt.NewFunction(compiler__register_macro_variadic)
var compiler__expand_macros = flagrt.NewFunction(compiler__expand_macros_variadic)
var macflagKw_symbol = flagrt.NewKeyword("symbol")
var macflagKw_kind = flagrt.NewKeyword("kind")
var macflagKw_list = flagrt.NewKeyword("list")
var macflagKw_vector = flagrt.NewKeyword("vector")
var macflagKw_pipe_vector = flagrt.NewKeyword("pipe-vector")
var macflagKw_map = flagrt.NewKeyword("map")
var macflagKw_set = flagrt.NewKeyword("set")
var macflagKw_hash_fn = flagrt.NewKeyword("hash-fn")
var macflagKw_meta = flagrt.NewKeyword("meta")
var macflagKw_string = flagrt.NewKeyword("string")
var macflagKw_target = flagrt.NewKeyword("target")
var macflagKw_entries = flagrt.NewKeyword("entries")
var macflagKw_elements = flagrt.NewKeyword("elements")
var macflagKw_name = flagrt.NewKeyword("name")
var macflagKw_macro_literal = flagrt.NewKeyword("macro-literal")
var macflagKw_inner = flagrt.NewKeyword("inner")
var macflagVec = flagrt.NewArray()
var macflagKw_body = flagrt.NewKeyword("body")
var macflagKw_keyword = flagrt.NewKeyword("keyword")
var macflagKw_quoted_symbol = flagrt.NewKeyword("quoted-symbol")
var macflagKw_value = flagrt.NewKeyword("value")
var macflagKw_char = flagrt.NewKeyword("char")
var macflagKw_int = flagrt.NewKeyword("int")
var macflagKw_bigint = flagrt.NewKeyword("bigint")
var macflagKw_float = flagrt.NewKeyword("float")
var macflagKw_raw = flagrt.NewKeyword("raw")
var macflagKw_ratio = flagrt.NewKeyword("ratio")
var macflagKw_numerator = flagrt.NewKeyword("numerator")
var macflagKw_denominator = flagrt.NewKeyword("denominator")
var macflagKw_quoted_list = flagrt.NewKeyword("quoted-list")
var macflagKw_form = flagrt.NewKeyword("form")
var macflagKw_message = flagrt.NewKeyword("message")
var macflagKw_data = flagrt.NewKeyword("data")
var macflagKw_params = flagrt.NewKeyword("params")
var macflagKw_rest_param = flagrt.NewKeyword("rest-param")
var macflagMap = flagrt.NewMap()
var macflagKw_arities = flagrt.NewKeyword("arities")
var macflagStr_do = flagrt.NewString("do")
var macflagKw_expected = flagrt.NewKeyword("expected")
var macflagKw_got = flagrt.NewKeyword("got")
var macflagKw_values = flagrt.NewKeyword("values")
var macflagKw_rest_bindings = flagrt.NewKeyword("rest-bindings")
var macflagKw_pattern = flagrt.NewKeyword("pattern")
var macflagStr_defrecord_ = flagrt.NewString("defrecord*")
var macflagKw_seq = flagrt.NewKeyword("seq")
var macflagKw_matched = flagrt.NewKeyword("matched")
var macflagKw_bindings = flagrt.NewKeyword("bindings")
var macflagMap_1 = flagrt.NewMap(macflagKw_matched, flagrt.NewBool(false))
var macflagKw_pat = flagrt.NewKeyword("pat")
var macflagKw_case = flagrt.NewKeyword("case")
var macflagKw_subst = flagrt.NewKeyword("subst")
var macflagKw_op = flagrt.NewKeyword("op")
var macflagKw_expr = flagrt.NewKeyword("expr")
var macflagKw_error = flagrt.NewKeyword("error")
