// Code generated by internal/compiler/tokenschemagen; DO NOT EDIT.

package compiler

//go:generate go run flag-lang/internal/compiler/tokenschemagen

type ParseTokenKind int

const (
	TokenEOF             ParseTokenKind = 0
	TokenError           ParseTokenKind = 1
	TokenListOpen        ParseTokenKind = 2
	TokenListClose       ParseTokenKind = 3
	TokenVectorOpen      ParseTokenKind = 4
	TokenVectorClose     ParseTokenKind = 5
	TokenMapOpen         ParseTokenKind = 6
	TokenMapClose        ParseTokenKind = 7
	TokenMetadata        ParseTokenKind = 8
	TokenQuote           ParseTokenKind = 9
	TokenDispatchSetOpen ParseTokenKind = 10
	TokenDispatchFnOpen  ParseTokenKind = 11
	TokenString          ParseTokenKind = 12
	TokenAtom            ParseTokenKind = 13
)
