// Code generated by internal/compiler/tokengen; DO NOT EDIT.
//go:generate go run flag-lang/internal/compiler/tokengen

package compiler

import (
	flagrt "flag-lang/runtime"
)

type SourceToken struct {
	Token  string `flag:"token"`
	Line   int64  `flag:"line"`
	Offset int64  `flag:"offset"`
}

type TokenState struct {
	Token       string `flag:"token"`
	StartLine   int64  `flag:"start-line"`
	StartOffset int64  `flag:"start-offset"`
	InString    bool   `flag:"in-string"`
	Triple      bool   `flag:"triple"`
	Escaped     bool   `flag:"escaped"`
}

type ParseToken struct {
	Kind    int64  `flag:"kind"`
	Lexeme  string `flag:"lexeme"`
	String  string `flag:"string"`
	Message string `flag:"message"`
	Line    int64  `flag:"line"`
	Col     int64  `flag:"col"`
}

func inc_arity_1(x flagrt.Value) flagrt.Value {
	return flagrt.Add(x, flagrt.NewLong(1))
}

func inc_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("inc expects exactly 1 arguments")
	}
	return inc_arity_1(args[0])
}

func close_arity_1(x flagrt.Value) flagrt.Value {
	var if_result_2 flagrt.Value
	if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(flagrt.TypeOf(x), flagrt.NewKeyword("file")))) {
		if_result_2 = flagrt.Call(flagrt.BuiltinFunction("close-file"), x)
	} else {
		var if_result_1 flagrt.Value
		if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(flagrt.TypeOf(x), flagrt.NewKeyword("channel")))) {
			if_result_1 = flagrt.Call(flagrt.BuiltinFunction("close-channel"), x)
		} else {
			if_result_1 = func() flagrt.Value {
				flagrt.Throw(flagrt.NewString(flagrt.Str("close expects a file or channel, got ", flagrt.TypeOf(x))))
				return flagrt.NilValue()
			}()
		}
		if_result_2 = if_result_1
	}
	return if_result_2
}

func close_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("close expects exactly 1 arguments")
	}
	return close_arity_1(args[0])
}

func stdlib__second_arity_1(coll flagrt.Value) flagrt.Value {
	return flagrt.First(flagrt.Rest(coll))
}

func stdlib__second_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("stdlib__second expects exactly 1 arguments")
	}
	return stdlib__second_arity_1(args[0])
}

func stdlib__third_arity_1(coll flagrt.Value) flagrt.Value {
	return flagrt.First(flagrt.Rest(flagrt.Rest(coll)))
}

func stdlib__third_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("stdlib__third expects exactly 1 arguments")
	}
	return stdlib__third_arity_1(args[0])
}

func compiler__whitespace_char_q_arity_1(ch flagrt.Value) flagrt.Value {
	return flagrt.NewBool(flagrt.Contains(compiler__whitespace_chars, ch))
}

func compiler__whitespace_char_q_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__whitespace_char_q expects exactly 1 arguments")
	}
	return compiler__whitespace_char_q_arity_1(args[0])
}

func compiler__delimiter_char_q_arity_1(ch flagrt.Value) flagrt.Value {
	return flagrt.NewBool(flagrt.Contains(compiler__delimiter_chars, ch))
}

func compiler__delimiter_char_q_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__delimiter_char_q expects exactly 1 arguments")
	}
	return compiler__delimiter_char_q_arity_1(args[0])
}

func compiler____gtSourceToken_arity_3(token flagrt.Value, line flagrt.Value, offset flagrt.Value) flagrt.Value {
	return flagrt.NewRecord(SourceToken{Token: flagrt.RequireString(token), Line: flagrt.RequireLong(line), Offset: flagrt.RequireLong(offset)})
}

func compiler____gtSourceToken_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 3 {
		panic("compiler____gtSourceToken expects exactly 3 arguments")
	}
	return compiler____gtSourceToken_arity_3(args[0], args[1], args[2])
}

func compiler__map__gtSourceToken_arity_1(m flagrt.Value) flagrt.Value {
	return flagrt.NewRecord(SourceToken{Token: flagrt.RequireString(flagrt.Get(m, flagKw_token)), Line: flagrt.RequireLong(flagrt.Get(m, flagKw_line)), Offset: flagrt.RequireLong(flagrt.Get(m, flagKw_offset))})
}

func compiler__map__gtSourceToken_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__map__gtSourceToken expects exactly 1 arguments")
	}
	return compiler__map__gtSourceToken_arity_1(args[0])
}

func compiler____gtTokenState_arity_6(token flagrt.Value, start_line flagrt.Value, start_offset flagrt.Value, in_string flagrt.Value, triple flagrt.Value, escaped flagrt.Value) flagrt.Value {
	return flagrt.NewRecord(TokenState{Token: flagrt.RequireString(token), StartLine: flagrt.RequireLong(start_line), StartOffset: flagrt.RequireLong(start_offset), InString: flagrt.RequireBool(in_string), Triple: flagrt.RequireBool(triple), Escaped: flagrt.RequireBool(escaped)})
}

func compiler____gtTokenState_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 6 {
		panic("compiler____gtTokenState expects exactly 6 arguments")
	}
	return compiler____gtTokenState_arity_6(args[0], args[1], args[2], args[3], args[4], args[5])
}

func compiler__map__gtTokenState_arity_1(m flagrt.Value) flagrt.Value {
	return flagrt.NewRecord(TokenState{Token: flagrt.RequireString(flagrt.Get(m, flagKw_token)), StartLine: flagrt.RequireLong(flagrt.Get(m, flagKw_start_line)), StartOffset: flagrt.RequireLong(flagrt.Get(m, flagKw_start_offset)), InString: flagrt.RequireBool(flagrt.Get(m, flagKw_in_string)), Triple: flagrt.RequireBool(flagrt.Get(m, flagKw_triple)), Escaped: flagrt.RequireBool(flagrt.Get(m, flagKw_escaped))})
}

func compiler__map__gtTokenState_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__map__gtTokenState expects exactly 1 arguments")
	}
	return compiler__map__gtTokenState_arity_1(args[0])
}

func compiler____gtParseToken_arity_6(kind flagrt.Value, lexeme flagrt.Value, string_ flagrt.Value, message flagrt.Value, line flagrt.Value, col flagrt.Value) flagrt.Value {
	return flagrt.NewRecord(ParseToken{Kind: flagrt.RequireLong(kind), Lexeme: flagrt.RequireString(lexeme), String: flagrt.RequireString(string_), Message: flagrt.RequireString(message), Line: flagrt.RequireLong(line), Col: flagrt.RequireLong(col)})
}

func compiler____gtParseToken_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 6 {
		panic("compiler____gtParseToken expects exactly 6 arguments")
	}
	return compiler____gtParseToken_arity_6(args[0], args[1], args[2], args[3], args[4], args[5])
}

func compiler__map__gtParseToken_arity_1(m flagrt.Value) flagrt.Value {
	return flagrt.NewRecord(ParseToken{Kind: flagrt.RequireLong(flagrt.Get(m, flagKw_kind)), Lexeme: flagrt.RequireString(flagrt.Get(m, flagKw_lexeme)), String: flagrt.RequireString(flagrt.Get(m, flagKw_string)), Message: flagrt.RequireString(flagrt.Get(m, flagKw_message)), Line: flagrt.RequireLong(flagrt.Get(m, flagKw_line)), Col: flagrt.RequireLong(flagrt.Get(m, flagKw_col))})
}

func compiler__map__gtParseToken_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__map__gtParseToken expects exactly 1 arguments")
	}
	return compiler__map__gtParseToken_arity_1(args[0])
}

func compiler__emit_token_bang_arity_4(out flagrt.Value, token flagrt.Value, line flagrt.Value, offset flagrt.Value) flagrt.Value {
	var if_result_185 flagrt.Value
	if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(token))) {
		if_result_185 = flagrt.NilValue()
	} else {
		if_result_185 = flagrt.Call(async__channel_send, out, flagrt.Call(compiler____gtSourceToken, token, line, offset))
	}
	return if_result_185
}

func compiler__emit_token_bang_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 4 {
		panic("compiler__emit_token_bang expects exactly 4 arguments")
	}
	return compiler__emit_token_bang_arity_4(args[0], args[1], args[2], args[3])
}

func compiler__make_state_arity_6(token flagrt.Value, start_line flagrt.Value, start_offset flagrt.Value, in_string flagrt.Value, triple flagrt.Value, escaped flagrt.Value) flagrt.Value {
	return flagrt.Call(compiler____gtTokenState, token, start_line, start_offset, in_string, triple, escaped)
}

func compiler__make_state_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 6 {
		panic("compiler__make_state expects exactly 6 arguments")
	}
	return compiler__make_state_arity_6(args[0], args[1], args[2], args[3], args[4], args[5])
}

func compiler__starts_triple_quote_q_arity_1(chars flagrt.Value) flagrt.Value {
	var let_result_189 flagrt.Value
	{
		var and_tmp = flagrt.NewBool(flagrt.Eq(flagrt.NewString("\""), flagrt.First(chars)))
		var if_result_188 flagrt.Value
		if flagrt.IsTruthy(and_tmp) {
			var let_result_187 flagrt.Value
			{
				var and_tmp = flagrt.NewBool(flagrt.Eq(flagrt.NewString("\""), flagrt.Call(stdlib__second, chars)))
				var if_result_186 flagrt.Value
				if flagrt.IsTruthy(and_tmp) {
					if_result_186 = flagrt.NewBool(flagrt.Eq(flagrt.NewString("\""), flagrt.Call(stdlib__third, chars)))
				} else {
					if_result_186 = and_tmp
				}
				let_result_187 = if_result_186
			}
			if_result_188 = let_result_187
		} else {
			if_result_188 = and_tmp
		}
		let_result_189 = if_result_188
	}
	return let_result_189
}

func compiler__starts_triple_quote_q_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__starts_triple_quote_q expects exactly 1 arguments")
	}
	return compiler__starts_triple_quote_q_arity_1(args[0])
}

func compiler__starts_dispatch_set_q_arity_1(chars flagrt.Value) flagrt.Value {
	var let_result_191 flagrt.Value
	{
		var and_tmp = flagrt.NewBool(flagrt.Eq(flagrt.NewString("#"), flagrt.First(chars)))
		var if_result_190 flagrt.Value
		if flagrt.IsTruthy(and_tmp) {
			if_result_190 = flagrt.NewBool(flagrt.Eq(flagrt.NewString("{"), flagrt.Call(stdlib__second, chars)))
		} else {
			if_result_190 = and_tmp
		}
		let_result_191 = if_result_190
	}
	return let_result_191
}

func compiler__starts_dispatch_set_q_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__starts_dispatch_set_q expects exactly 1 arguments")
	}
	return compiler__starts_dispatch_set_q_arity_1(args[0])
}

func compiler__starts_dispatch_fn_q_arity_1(chars flagrt.Value) flagrt.Value {
	var let_result_193 flagrt.Value
	{
		var and_tmp = flagrt.NewBool(flagrt.Eq(flagrt.NewString("#"), flagrt.First(chars)))
		var if_result_192 flagrt.Value
		if flagrt.IsTruthy(and_tmp) {
			if_result_192 = flagrt.NewBool(flagrt.Eq(flagrt.NewString("("), flagrt.Call(stdlib__second, chars)))
		} else {
			if_result_192 = and_tmp
		}
		let_result_193 = if_result_192
	}
	return let_result_193
}

func compiler__starts_dispatch_fn_q_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__starts_dispatch_fn_q expects exactly 1 arguments")
	}
	return compiler__starts_dispatch_fn_q_arity_1(args[0])
}

func compiler__strip_quoted_token_arity_3(token flagrt.Value, prefix flagrt.Value, suffix flagrt.Value) flagrt.Value {
	var let_result_196 flagrt.Value
	{
		var chars = flagrt.Seq(token)
		var total = flagrt.NewLong(int64(flagrt.Count(chars)))
		var if_result_195 flagrt.Value
		if flagrt.Le(total, flagrt.Add(prefix, suffix)) {
			if_result_195 = flagStr_
		} else {
			if_result_195 = func() flagrt.Value {
				var remaining = flagrt.Take(flagrt.Sub(flagrt.Sub(total, prefix), suffix), flagrt.Drop(prefix, chars))
				var out = flagStr_
				for {
					var if_result_194 flagrt.Value
					if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(remaining))) {
						if_result_194 = out
					} else {
						if_result_194 = flagrt.NewRecur(flagrt.Rest(remaining), flagrt.NewString(flagrt.Str(out, flagrt.First(remaining))))
					}
					__loopResult := if_result_194
					if __recurValues, __isRecur := flagrt.UnwrapRecur(__loopResult); __isRecur {
						if len(__recurValues) != 2 {
							panic("internal error: recur arity mismatch")
						}
						remaining = __recurValues[0]
						out = __recurValues[1]
						continue
					}
					return __loopResult
				}
			}()
		}
		let_result_196 = if_result_195
	}
	return let_result_196
}

func compiler__strip_quoted_token_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 3 {
		panic("compiler__strip_quoted_token expects exactly 3 arguments")
	}
	return compiler__strip_quoted_token_arity_3(args[0], args[1], args[2])
}

func compiler__token__gtstring_value_arity_1(token flagrt.Value) flagrt.Value {
	var let_result_212 flagrt.Value
	{
		var chars = flagrt.Seq(token)
		var n = flagrt.NewLong(int64(flagrt.Count(chars)))
		var let_result_204 flagrt.Value
		{
			var and_tmp = flagrt.Ge(n, flagrt.NewLong(6))
			var if_result_203 flagrt.Value
			if and_tmp {
				var let_result_202 flagrt.Value
				{
					var and_tmp = flagrt.Call(compiler__starts_triple_quote_q, chars)
					var if_result_201 flagrt.Value
					if flagrt.IsTruthy(and_tmp) {
						var let_result_200 flagrt.Value
						{
							var and_tmp = flagrt.NewBool(flagrt.Eq(flagrt.NewString("\""), flagrt.First(flagrt.Drop(flagrt.Sub(n, flagrt.NewLong(3)), chars))))
							var if_result_199 flagrt.Value
							if flagrt.IsTruthy(and_tmp) {
								var let_result_198 flagrt.Value
								{
									var and_tmp = flagrt.NewBool(flagrt.Eq(flagrt.NewString("\""), flagrt.First(flagrt.Drop(flagrt.Sub(n, flagrt.NewLong(2)), chars))))
									var if_result_197 flagrt.Value
									if flagrt.IsTruthy(and_tmp) {
										if_result_197 = flagrt.NewBool(flagrt.Eq(flagrt.NewString("\""), flagrt.First(flagrt.Drop(flagrt.Sub(n, flagrt.NewLong(1)), chars))))
									} else {
										if_result_197 = and_tmp
									}
									let_result_198 = if_result_197
								}
								if_result_199 = let_result_198
							} else {
								if_result_199 = and_tmp
							}
							let_result_200 = if_result_199
						}
						if_result_201 = let_result_200
					} else {
						if_result_201 = and_tmp
					}
					let_result_202 = if_result_201
				}
				if_result_203 = let_result_202
			} else {
				if_result_203 = flagrt.NewBool(and_tmp)
			}
			let_result_204 = if_result_203
		}
		var if_result_211 flagrt.Value
		if flagrt.IsTruthy(let_result_204) {
			if_result_211 = flagrt.Call(compiler__strip_quoted_token, token, flagrt.NewLong(3), flagrt.NewLong(3))
		} else {
			var let_result_208 flagrt.Value
			{
				var and_tmp = flagrt.Ge(n, flagrt.NewLong(2))
				var if_result_207 flagrt.Value
				if and_tmp {
					var let_result_206 flagrt.Value
					{
						var and_tmp = flagrt.NewBool(flagrt.Eq(flagrt.NewString("\""), flagrt.First(chars)))
						var if_result_205 flagrt.Value
						if flagrt.IsTruthy(and_tmp) {
							if_result_205 = flagrt.NewBool(flagrt.Eq(flagrt.NewString("\""), flagrt.First(flagrt.Drop(flagrt.Sub(n, flagrt.NewLong(1)), chars))))
						} else {
							if_result_205 = and_tmp
						}
						let_result_206 = if_result_205
					}
					if_result_207 = let_result_206
				} else {
					if_result_207 = flagrt.NewBool(and_tmp)
				}
				let_result_208 = if_result_207
			}
			var if_result_210 flagrt.Value
			if flagrt.IsTruthy(let_result_208) {
				if_result_210 = flagrt.Call(compiler__strip_quoted_token, token, flagrt.NewLong(1), flagrt.NewLong(1))
			} else {
				var if_result_209 flagrt.Value
				if flagrt.IsTruthy(flagrt.NewBool(true)) {
					if_result_209 = token
				} else {
					if_result_209 = flagrt.NilValue()
				}
				if_result_210 = if_result_209
			}
			if_result_211 = if_result_210
		}
		let_result_212 = if_result_211
	}
	return let_result_212
}

func compiler__token__gtstring_value_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__token__gtstring_value expects exactly 1 arguments")
	}
	return compiler__token__gtstring_value_arity_1(args[0])
}

func compiler__source_token__gtparse_token_arity_1(__arg0 flagrt.Value) flagrt.Value {
	var token = flagrt.Get(__arg0, flagKw_token)
	_ = token
	var line = flagrt.Get(__arg0, flagKw_line)
	_ = line
	var offset = flagrt.Get(__arg0, flagKw_offset)
	_ = offset
	var if_result_230 flagrt.Value
	if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(token, flagrt.NewString("(")))) {
		if_result_230 = flagrt.Call(compiler____gtParseToken, compiler__token_list_open, flagStr_, flagStr_, flagStr_, line, offset)
	} else {
		var if_result_229 flagrt.Value
		if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(token, flagrt.NewString(")")))) {
			if_result_229 = flagrt.Call(compiler____gtParseToken, compiler__token_list_close, flagStr_, flagStr_, flagStr_, line, offset)
		} else {
			var if_result_228 flagrt.Value
			if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(token, flagrt.NewString("[")))) {
				if_result_228 = flagrt.Call(compiler____gtParseToken, compiler__token_vector_open, flagStr_, flagStr_, flagStr_, line, offset)
			} else {
				var if_result_227 flagrt.Value
				if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(token, flagrt.NewString("]")))) {
					if_result_227 = flagrt.Call(compiler____gtParseToken, compiler__token_vector_close, flagStr_, flagStr_, flagStr_, line, offset)
				} else {
					var if_result_226 flagrt.Value
					if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(token, flagrt.NewString("|")))) {
						if_result_226 = flagrt.Call(compiler____gtParseToken, compiler__token_pipe, flagStr_, flagStr_, flagStr_, line, offset)
					} else {
						var if_result_225 flagrt.Value
						if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(token, flagrt.NewString("{")))) {
							if_result_225 = flagrt.Call(compiler____gtParseToken, compiler__token_map_open, flagStr_, flagStr_, flagStr_, line, offset)
						} else {
							var if_result_224 flagrt.Value
							if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(token, flagrt.NewString("}")))) {
								if_result_224 = flagrt.Call(compiler____gtParseToken, compiler__token_map_close, flagStr_, flagStr_, flagStr_, line, offset)
							} else {
								var if_result_223 flagrt.Value
								if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(token, flagrt.NewString("^")))) {
									if_result_223 = flagrt.Call(compiler____gtParseToken, compiler__token_metadata, flagStr_, flagStr_, flagStr_, line, offset)
								} else {
									var if_result_222 flagrt.Value
									if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(token, flagrt.NewString("'")))) {
										if_result_222 = flagrt.Call(compiler____gtParseToken, compiler__token_quote, flagStr_, flagStr_, flagStr_, line, offset)
									} else {
										var if_result_221 flagrt.Value
										if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(token, flagrt.NewString("#{")))) {
											if_result_221 = flagrt.Call(compiler____gtParseToken, compiler__token_dispatch_set_open, flagStr_, flagStr_, flagStr_, line, offset)
										} else {
											var if_result_220 flagrt.Value
											if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(token, flagrt.NewString("#(")))) {
												if_result_220 = flagrt.Call(compiler____gtParseToken, compiler__token_dispatch_fn_open, flagStr_, flagStr_, flagStr_, line, offset)
											} else {
												var if_result_219 flagrt.Value
												if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(token, flagrt.NewString("#")))) {
													if_result_219 = flagrt.Call(compiler____gtParseToken, compiler__token_error, flagStr_, flagStr_, flagStr_unexpected_end_after__, line, offset)
												} else {
													var let_result_216 flagrt.Value
													{
														var and_tmp = flagrt.Ge(flagrt.NewLong(int64(flagrt.Count(token))), flagrt.NewLong(2))
														var if_result_215 flagrt.Value
														if and_tmp {
															var let_result_214 flagrt.Value
															{
																var and_tmp = flagrt.NewBool(flagrt.Eq(flagrt.NewString("\""), flagrt.First(flagrt.Seq(token))))
																var if_result_213 flagrt.Value
																if flagrt.IsTruthy(and_tmp) {
																	if_result_213 = flagrt.NewBool(flagrt.Eq(flagrt.NewString("\""), flagrt.Last(flagrt.Seq(token))))
																} else {
																	if_result_213 = and_tmp
																}
																let_result_214 = if_result_213
															}
															if_result_215 = let_result_214
														} else {
															if_result_215 = flagrt.NewBool(and_tmp)
														}
														let_result_216 = if_result_215
													}
													var if_result_218 flagrt.Value
													if flagrt.IsTruthy(let_result_216) {
														if_result_218 = flagrt.Call(compiler____gtParseToken, compiler__token_string, flagStr_, flagrt.Call(compiler__token__gtstring_value, token), flagStr_, line, offset)
													} else {
														var if_result_217 flagrt.Value
														if flagrt.IsTruthy(flagrt.NewBool(true)) {
															if_result_217 = flagrt.Call(compiler____gtParseToken, compiler__token_atom, token, flagStr_, flagStr_, line, offset)
														} else {
															if_result_217 = flagrt.NilValue()
														}
														if_result_218 = if_result_217
													}
													if_result_219 = if_result_218
												}
												if_result_220 = if_result_219
											}
											if_result_221 = if_result_220
										}
										if_result_222 = if_result_221
									}
									if_result_223 = if_result_222
								}
								if_result_224 = if_result_223
							}
							if_result_225 = if_result_224
						}
						if_result_226 = if_result_225
					}
					if_result_227 = if_result_226
				}
				if_result_228 = if_result_227
			}
			if_result_229 = if_result_228
		}
		if_result_230 = if_result_229
	}
	return if_result_230
}

func compiler__source_token__gtparse_token_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__source_token__gtparse_token expects exactly 1 arguments")
	}
	return compiler__source_token__gtparse_token_arity_1(args[0])
}

func compiler__token_end_col_arity_1(source_token flagrt.Value) flagrt.Value {
	return flagrt.Add(flagrt.Call(flagKw_offset, source_token), flagrt.NewLong(int64(flagrt.Count(flagrt.Call(flagKw_token, source_token)))))
}

func compiler__token_end_col_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__token_end_col expects exactly 1 arguments")
	}
	return compiler__token_end_col_arity_1(args[0])
}

func compiler__tokenize_line_step_bang_arity_5(out flagrt.Value, chars flagrt.Value, line flagrt.Value, column flagrt.Value, state flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		var remaining = chars
		var col = column
		var current = state
		for {
			var if_result_251 flagrt.Value
			if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(remaining))) {
				var if_result_231 flagrt.Value
				if flagrt.IsTruthy(flagrt.Call(flagKw_in_string, current)) {
					if_result_231 = current
				} else {
					_ = flagrt.Call(compiler__emit_token_bang, out, flagrt.Call(flagKw_token, current), flagrt.Call(flagKw_start_line, current), flagrt.Call(flagKw_start_offset, current))
					if_result_231 = compiler__empty_token_state
				}
				if_result_251 = if_result_231
			} else {
				var let_result_250 flagrt.Value
				{
					var ch = flagrt.First(remaining)
					var if_result_249 flagrt.Value
					if flagrt.IsTruthy(flagrt.Call(flagKw_in_string, current)) {
						var if_result_239 flagrt.Value
						if flagrt.IsTruthy(flagrt.Call(flagKw_triple, current)) {
							var if_result_233 flagrt.Value
							if flagrt.IsTruthy(flagrt.Call(compiler__starts_triple_quote_q, remaining)) {
								var let_result_232 flagrt.Value
								{
									var token = flagrt.Str(flagrt.Call(flagKw_token, current), "\"\"\"")
									_ = flagrt.Call(compiler__emit_token_bang, out, flagrt.NewString(token), flagrt.Call(flagKw_start_line, current), flagrt.Call(flagKw_start_offset, current))
									let_result_232 = flagrt.NewRecur(flagrt.Drop(flagrt.NewLong(3), remaining), flagrt.Add(col, flagrt.NewLong(3)), compiler__empty_token_state)
								}
								if_result_233 = let_result_232
							} else {
								if_result_233 = flagrt.NewRecur(flagrt.Rest(remaining), flagrt.Call(inc, col), flagrt.Call(compiler__make_state, flagrt.NewString(flagrt.Str(flagrt.Call(flagKw_token, current), ch)), flagrt.Call(flagKw_start_line, current), flagrt.Call(flagKw_start_offset, current), flagrt.NewBool(true), flagrt.NewBool(true), flagrt.NewBool(false)))
							}
							if_result_239 = if_result_233
						} else {
							var let_result_238 flagrt.Value
							{
								var token = flagrt.Str(flagrt.Call(flagKw_token, current), ch)
								var if_result_237 flagrt.Value
								if flagrt.IsTruthy(flagrt.Call(flagKw_escaped, current)) {
									if_result_237 = flagrt.NewRecur(flagrt.Rest(remaining), flagrt.Call(inc, col), flagrt.Call(compiler__make_state, flagrt.NewString(token), flagrt.Call(flagKw_start_line, current), flagrt.Call(flagKw_start_offset, current), flagrt.NewBool(true), flagrt.NewBool(false), flagrt.NewBool(false)))
								} else {
									var if_result_236 flagrt.Value
									if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(flagrt.NewString("\\"), ch))) {
										if_result_236 = flagrt.NewRecur(flagrt.Rest(remaining), flagrt.Call(inc, col), flagrt.Call(compiler__make_state, flagrt.NewString(token), flagrt.Call(flagKw_start_line, current), flagrt.Call(flagKw_start_offset, current), flagrt.NewBool(true), flagrt.NewBool(false), flagrt.NewBool(true)))
									} else {
										var if_result_235 flagrt.Value
										if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(flagrt.NewString("\""), ch))) {
											_ = flagrt.Call(compiler__emit_token_bang, out, flagrt.NewString(token), flagrt.Call(flagKw_start_line, current), flagrt.Call(flagKw_start_offset, current))
											if_result_235 = flagrt.NewRecur(flagrt.Rest(remaining), flagrt.Call(inc, col), compiler__empty_token_state)
										} else {
											var if_result_234 flagrt.Value
											if flagrt.IsTruthy(flagrt.NewBool(true)) {
												if_result_234 = flagrt.NewRecur(flagrt.Rest(remaining), flagrt.Call(inc, col), flagrt.Call(compiler__make_state, flagrt.NewString(token), flagrt.Call(flagKw_start_line, current), flagrt.Call(flagKw_start_offset, current), flagrt.NewBool(true), flagrt.NewBool(false), flagrt.NewBool(false)))
											} else {
												if_result_234 = flagrt.NilValue()
											}
											if_result_235 = if_result_234
										}
										if_result_236 = if_result_235
									}
									if_result_237 = if_result_236
								}
								let_result_238 = if_result_237
							}
							if_result_239 = let_result_238
						}
						if_result_249 = if_result_239
					} else {
						var if_result_248 flagrt.Value
						if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(flagrt.NewString(";"), ch))) {
							_ = flagrt.Call(compiler__emit_token_bang, out, flagrt.Call(flagKw_token, current), flagrt.Call(flagKw_start_line, current), flagrt.Call(flagKw_start_offset, current))
							if_result_248 = compiler__empty_token_state
						} else {
							var if_result_247 flagrt.Value
							if flagrt.IsTruthy(flagrt.Call(compiler__whitespace_char_q, ch)) {
								_ = flagrt.Call(compiler__emit_token_bang, out, flagrt.Call(flagKw_token, current), flagrt.Call(flagKw_start_line, current), flagrt.Call(flagKw_start_offset, current))
								if_result_247 = flagrt.NewRecur(flagrt.Rest(remaining), flagrt.Call(inc, col), compiler__empty_token_state)
							} else {
								var if_result_246 flagrt.Value
								if flagrt.IsTruthy(flagrt.Call(compiler__delimiter_char_q, ch)) {
									_ = flagrt.Call(compiler__emit_token_bang, out, flagrt.Call(flagKw_token, current), flagrt.Call(flagKw_start_line, current), flagrt.Call(flagKw_start_offset, current))
									_ = flagrt.Call(compiler__emit_token_bang, out, ch, line, col)
									if_result_246 = flagrt.NewRecur(flagrt.Rest(remaining), flagrt.Call(inc, col), compiler__empty_token_state)
								} else {
									var if_result_245 flagrt.Value
									if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(flagrt.NewString("\""), ch))) {
										var if_result_240 flagrt.Value
										if flagrt.IsTruthy(flagrt.Call(compiler__starts_triple_quote_q, remaining)) {
											_ = flagrt.Call(compiler__emit_token_bang, out, flagrt.Call(flagKw_token, current), flagrt.Call(flagKw_start_line, current), flagrt.Call(flagKw_start_offset, current))
											if_result_240 = flagrt.NewRecur(flagrt.Drop(flagrt.NewLong(3), remaining), flagrt.Add(col, flagrt.NewLong(3)), flagrt.Call(compiler__make_state, flagStr____, line, col, flagrt.NewBool(true), flagrt.NewBool(true), flagrt.NewBool(false)))
										} else {
											_ = flagrt.Call(compiler__emit_token_bang, out, flagrt.Call(flagKw_token, current), flagrt.Call(flagKw_start_line, current), flagrt.Call(flagKw_start_offset, current))
											if_result_240 = flagrt.NewRecur(flagrt.Rest(remaining), flagrt.Call(inc, col), flagrt.Call(compiler__make_state, flagStr__, line, col, flagrt.NewBool(true), flagrt.NewBool(false), flagrt.NewBool(false)))
										}
										if_result_245 = if_result_240
									} else {
										var if_result_244 flagrt.Value
										if flagrt.IsTruthy(flagrt.Call(compiler__starts_dispatch_set_q, remaining)) {
											_ = flagrt.Call(compiler__emit_token_bang, out, flagrt.Call(flagKw_token, current), flagrt.Call(flagKw_start_line, current), flagrt.Call(flagKw_start_offset, current))
											_ = flagrt.Call(compiler__emit_token_bang, out, flagStr___, line, col)
											if_result_244 = flagrt.NewRecur(flagrt.Drop(flagrt.NewLong(2), remaining), flagrt.Add(col, flagrt.NewLong(2)), compiler__empty_token_state)
										} else {
											var if_result_243 flagrt.Value
											if flagrt.IsTruthy(flagrt.Call(compiler__starts_dispatch_fn_q, remaining)) {
												_ = flagrt.Call(compiler__emit_token_bang, out, flagrt.Call(flagKw_token, current), flagrt.Call(flagKw_start_line, current), flagrt.Call(flagKw_start_offset, current))
												_ = flagrt.Call(compiler__emit_token_bang, out, flagStr____1, line, col)
												if_result_243 = flagrt.NewRecur(flagrt.Drop(flagrt.NewLong(2), remaining), flagrt.Add(col, flagrt.NewLong(2)), compiler__empty_token_state)
											} else {
												var if_result_242 flagrt.Value
												if flagrt.IsTruthy(flagrt.NewBool(true)) {
													var if_result_241 flagrt.Value
													if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(flagrt.Call(flagKw_token, current)))) {
														if_result_241 = flagrt.NewRecur(flagrt.Rest(remaining), flagrt.Call(inc, col), flagrt.Call(compiler__make_state, ch, line, col, flagrt.NewBool(false), flagrt.NewBool(false), flagrt.NewBool(false)))
													} else {
														if_result_241 = flagrt.NewRecur(flagrt.Rest(remaining), flagrt.Call(inc, col), flagrt.Call(compiler__make_state, flagrt.NewString(flagrt.Str(flagrt.Call(flagKw_token, current), ch)), flagrt.Call(flagKw_start_line, current), flagrt.Call(flagKw_start_offset, current), flagrt.NewBool(false), flagrt.NewBool(false), flagrt.NewBool(false)))
													}
													if_result_242 = if_result_241
												} else {
													if_result_242 = flagrt.NilValue()
												}
												if_result_243 = if_result_242
											}
											if_result_244 = if_result_243
										}
										if_result_245 = if_result_244
									}
									if_result_246 = if_result_245
								}
								if_result_247 = if_result_246
							}
							if_result_248 = if_result_247
						}
						if_result_249 = if_result_248
					}
					let_result_250 = if_result_249
				}
				if_result_251 = let_result_250
			}
			__loopResult := if_result_251
			if __recurValues, __isRecur := flagrt.UnwrapRecur(__loopResult); __isRecur {
				if len(__recurValues) != 3 {
					panic("internal error: recur arity mismatch")
				}
				remaining = __recurValues[0]
				col = __recurValues[1]
				current = __recurValues[2]
				continue
			}
			return __loopResult
		}
	}()
}

func compiler__tokenize_line_step_bang_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 5 {
		panic("compiler__tokenize_line_step_bang expects exactly 5 arguments")
	}
	return compiler__tokenize_line_step_bang_arity_5(args[0], args[1], args[2], args[3], args[4])
}

func compiler__tokenize_lines_bang_arity_3(out flagrt.Value, lines flagrt.Value, line_number flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		var remaining = lines
		var line = line_number
		var state = compiler__empty_token_state
		for {
			var if_result_257 flagrt.Value
			if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(remaining))) {
				if_result_257 = flagrt.Call(compiler__emit_token_bang, out, flagrt.Call(flagKw_token, state), flagrt.Call(flagKw_start_line, state), flagrt.Call(flagKw_start_offset, state))
			} else {
				var let_result_256 flagrt.Value
				{
					var next_state = flagrt.Call(compiler__tokenize_line_step_bang, out, flagrt.Seq(flagrt.NewString(flagrt.Str(flagrt.First(remaining)))), line, flagrt.NewLong(1), state)
					var if_result_252 flagrt.Value
					if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(flagrt.Rest(remaining)))) {
						if_result_252 = flagrt.NewBool(false)
					} else {
						if_result_252 = flagrt.NewBool(true)
					}
					var has_more = if_result_252
					var let_result_254 flagrt.Value
					{
						var and_tmp = has_more
						var if_result_253 flagrt.Value
						if flagrt.IsTruthy(and_tmp) {
							if_result_253 = flagrt.Call(flagKw_in_string, next_state)
						} else {
							if_result_253 = and_tmp
						}
						let_result_254 = if_result_253
					}
					var if_result_255 flagrt.Value
					if flagrt.IsTruthy(let_result_254) {
						if_result_255 = flagrt.Call(compiler__make_state, flagrt.NewString(flagrt.Str(flagrt.Call(flagKw_token, next_state), "\n")), flagrt.Call(flagKw_start_line, next_state), flagrt.Call(flagKw_start_offset, next_state), flagrt.NewBool(true), flagrt.Call(flagKw_triple, next_state), flagrt.Call(flagKw_escaped, next_state))
					} else {
						if_result_255 = next_state
					}
					var carry_state = if_result_255
					let_result_256 = flagrt.NewRecur(flagrt.Rest(remaining), flagrt.Add(line, flagrt.NewLong(1)), carry_state)
				}
				if_result_257 = let_result_256
			}
			__loopResult := if_result_257
			if __recurValues, __isRecur := flagrt.UnwrapRecur(__loopResult); __isRecur {
				if len(__recurValues) != 3 {
					panic("internal error: recur arity mismatch")
				}
				remaining = __recurValues[0]
				line = __recurValues[1]
				state = __recurValues[2]
				continue
			}
			return __loopResult
		}
	}()
}

func compiler__tokenize_lines_bang_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 3 {
		panic("compiler__tokenize_lines_bang expects exactly 3 arguments")
	}
	return compiler__tokenize_lines_bang_arity_3(args[0], args[1], args[2])
}

func compiler__split_lines_arity_1(source flagrt.Value) flagrt.Value {
	return func() flagrt.Value {
		var chars = flagrt.Seq(source)
		var line = flagStr_
		var lines = flagVec
		for {
			var if_result_261 flagrt.Value
			if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(chars))) {
				var if_result_258 flagrt.Value
				if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsEmpty(line))) {
					if_result_258 = lines
				} else {
					if_result_258 = flagrt.Conj(lines, line)
				}
				if_result_261 = if_result_258
			} else {
				var let_result_260 flagrt.Value
				{
					var ch = flagrt.First(chars)
					var if_result_259 flagrt.Value
					if flagrt.IsTruthy(flagrt.NewBool(flagrt.Eq(flagrt.NewString("\n"), ch))) {
						if_result_259 = flagrt.NewRecur(flagrt.Rest(chars), flagStr_, flagrt.Conj(lines, line))
					} else {
						if_result_259 = flagrt.NewRecur(flagrt.Rest(chars), flagrt.NewString(flagrt.Str(line, ch)), lines)
					}
					let_result_260 = if_result_259
				}
				if_result_261 = let_result_260
			}
			__loopResult := if_result_261
			if __recurValues, __isRecur := flagrt.UnwrapRecur(__loopResult); __isRecur {
				if len(__recurValues) != 3 {
					panic("internal error: recur arity mismatch")
				}
				chars = __recurValues[0]
				line = __recurValues[1]
				lines = __recurValues[2]
				continue
			}
			return __loopResult
		}
	}()
}

func compiler__split_lines_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__split_lines expects exactly 1 arguments")
	}
	return compiler__split_lines_arity_1(args[0])
}

func compiler__tokenize_source_arity_1(source flagrt.Value) flagrt.Value {
	var let_result_262 flagrt.Value
	{
		var out = flagrt.Call(async__make_channel, flagrt.NewLong(64))
		_ = flagrt.Call(async__go_run, flagrt.NewFunction(func(args ...flagrt.Value) flagrt.Value {
			if len(args) != 0 {
				panic("fn expects exactly 0 arguments")
			}
			_ = flagrt.Call(compiler__tokenize_lines_bang, out, flagrt.Call(compiler__split_lines, source), flagrt.NewLong(1))
			return flagrt.Call(async__channel_close, out)
		}))
		let_result_262 = out
	}
	return let_result_262
}

func compiler__tokenize_source_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__tokenize_source expects exactly 1 arguments")
	}
	return compiler__tokenize_source_arity_1(args[0])
}

func compiler__tokenize_file_arity_1(path flagrt.Value) flagrt.Value {
	var let_result_263 flagrt.Value
	{
		var out = flagrt.Call(async__make_channel, flagrt.NewLong(64))
		_ = flagrt.Call(async__go_run, flagrt.NewFunction(func(args ...flagrt.Value) flagrt.Value {
			if len(args) != 0 {
				panic("fn expects exactly 0 arguments")
			}
			return func() flagrt.Value {
				var rdr = flagrt.Call(flagrt.GoBind_runtime_OpenFile, path)
				defer flagrt.Call(flagrt.NewFunction(func(args ...flagrt.Value) flagrt.Value {
					if len(args) != 0 {
						panic("fn expects exactly 0 arguments")
					}
					return flagrt.Call(prologue_close, rdr)
				}))
				_ = flagrt.Call(compiler__tokenize_lines_bang, out, flagrt.LineSeq(rdr), flagrt.NewLong(1))
				return flagrt.Call(async__channel_close, out)
			}()
		}))
		let_result_263 = out
	}
	return let_result_263
}

func compiler__tokenize_file_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__tokenize_file expects exactly 1 arguments")
	}
	return compiler__tokenize_file_arity_1(args[0])
}

func compiler__tokenize_file_parse_tokens_arity_1(path flagrt.Value) flagrt.Value {
	var let_result_269 flagrt.Value
	{
		var out = flagrt.Call(async__make_channel, flagrt.NewLong(64))
		var in = flagrt.Call(compiler__tokenize_file, path)
		_ = flagrt.Call(async__go_run, flagrt.NewFunction(func(args ...flagrt.Value) flagrt.Value {
			if len(args) != 0 {
				panic("fn expects exactly 0 arguments")
			}
			return func() flagrt.Value {
				var last_token = flagrt.NilValue()
				for {
					var let_result_268 flagrt.Value
					{
						var source_token = flagrt.Call(async__channel_receive, in)
						var if_result_267 flagrt.Value
						if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsNil(source_token))) {
							var let_result_266 flagrt.Value
							{
								var if_result_264 flagrt.Value
								if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsNil(last_token))) {
									if_result_264 = flagrt.NewLong(1)
								} else {
									if_result_264 = flagrt.Call(flagKw_line, last_token)
								}
								var eof_line = if_result_264
								var if_result_265 flagrt.Value
								if flagrt.IsTruthy(flagrt.NewBool(flagrt.IsNil(last_token))) {
									if_result_265 = flagrt.NewLong(1)
								} else {
									if_result_265 = flagrt.Call(compiler__token_end_col, last_token)
								}
								var eof_col = if_result_265
								_ = flagrt.Call(async__channel_send, out, flagrt.Call(compiler____gtParseToken, compiler__token_eof, flagStr_, flagStr_, flagStr_, eof_line, eof_col))
								let_result_266 = flagrt.Call(async__channel_close, out)
							}
							if_result_267 = let_result_266
						} else {
							_ = flagrt.Call(async__channel_send, out, flagrt.Call(compiler__source_token__gtparse_token, source_token))
							if_result_267 = flagrt.NewRecur(source_token)
						}
						let_result_268 = if_result_267
					}
					__loopResult := let_result_268
					if __recurValues, __isRecur := flagrt.UnwrapRecur(__loopResult); __isRecur {
						if len(__recurValues) != 1 {
							panic("internal error: recur arity mismatch")
						}
						last_token = __recurValues[0]
						continue
					}
					return __loopResult
				}
			}()
		}))
		let_result_269 = out
	}
	return let_result_269
}

func compiler__tokenize_file_parse_tokens_variadic(args ...flagrt.Value) flagrt.Value {
	if len(args) != 1 {
		panic("compiler__tokenize_file_parse_tokens expects exactly 1 arguments")
	}
	return compiler__tokenize_file_parse_tokens_arity_1(args[0])
}

var inc = flagrt.NewFunction(inc_variadic)

var prologue_close = flagrt.NewFunction(close_variadic)

var async__channel_send = flagrt.GoBind_async_ChannelSend

var async__go_run = flagrt.GoBind_async_GoRun

var async__channel_close = flagrt.GoBind_async_ChannelClose

var async__make_channel = flagrt.GoBind_async_MakeChannel
var async__channel_receive = flagrt.GoBind_async_ChannelReceive

var stdlib__second = flagrt.NewFunction(stdlib__second_variadic)
var stdlib__third = flagrt.NewFunction(stdlib__third_variadic)
var compiler__whitespace_chars = flagSet
var compiler__delimiter_chars = flagSet_1
var compiler__token_eof = flagrt.NewLong(0)
var compiler__token_error = flagrt.NewLong(1)
var compiler__token_list_open = flagrt.NewLong(2)
var compiler__token_list_close = flagrt.NewLong(3)
var compiler__token_vector_open = flagrt.NewLong(4)
var compiler__token_vector_close = flagrt.NewLong(5)
var compiler__token_map_open = flagrt.NewLong(6)
var compiler__token_map_close = flagrt.NewLong(7)
var compiler__token_metadata = flagrt.NewLong(8)
var compiler__token_quote = flagrt.NewLong(9)
var compiler__token_dispatch_set_open = flagrt.NewLong(10)
var compiler__token_dispatch_fn_open = flagrt.NewLong(11)
var compiler__token_string = flagrt.NewLong(12)
var compiler__token_atom = flagrt.NewLong(13)
var compiler__token_pipe = flagrt.NewLong(14)
var compiler__whitespace_char_q = flagrt.NewFunction(compiler__whitespace_char_q_variadic)
var compiler__delimiter_char_q = flagrt.NewFunction(compiler__delimiter_char_q_variadic)
var compiler____gtSourceToken = flagrt.NewFunction(compiler____gtSourceToken_variadic)
var compiler__map__gtSourceToken = flagrt.NewFunction(compiler__map__gtSourceToken_variadic)
var compiler____gtTokenState = flagrt.NewFunction(compiler____gtTokenState_variadic)
var compiler__map__gtTokenState = flagrt.NewFunction(compiler__map__gtTokenState_variadic)
var compiler____gtParseToken = flagrt.NewFunction(compiler____gtParseToken_variadic)
var compiler__map__gtParseToken = flagrt.NewFunction(compiler__map__gtParseToken_variadic)
var compiler__emit_token_bang = flagrt.NewFunction(compiler__emit_token_bang_variadic)
var compiler__make_state = flagrt.NewFunction(compiler__make_state_variadic)
var compiler__empty_token_state = flagrt.Call(compiler__make_state, flagStr_, flagrt.NewLong(0), flagrt.NewLong(0), flagrt.NewBool(false), flagrt.NewBool(false), flagrt.NewBool(false))
var compiler__starts_triple_quote_q = flagrt.NewFunction(compiler__starts_triple_quote_q_variadic)
var compiler__starts_dispatch_set_q = flagrt.NewFunction(compiler__starts_dispatch_set_q_variadic)
var compiler__starts_dispatch_fn_q = flagrt.NewFunction(compiler__starts_dispatch_fn_q_variadic)
var compiler__strip_quoted_token = flagrt.NewFunction(compiler__strip_quoted_token_variadic)
var compiler__token__gtstring_value = flagrt.NewFunction(compiler__token__gtstring_value_variadic)
var compiler__source_token__gtparse_token = flagrt.NewFunction(compiler__source_token__gtparse_token_variadic)
var compiler__token_end_col = flagrt.NewFunction(compiler__token_end_col_variadic)
var compiler__tokenize_line_step_bang = flagrt.NewFunction(compiler__tokenize_line_step_bang_variadic)
var compiler__tokenize_lines_bang = flagrt.NewFunction(compiler__tokenize_lines_bang_variadic)
var compiler__split_lines = flagrt.NewFunction(compiler__split_lines_variadic)
var compiler__tokenize_source = flagrt.NewFunction(compiler__tokenize_source_variadic)
var compiler__tokenize_file = flagrt.NewFunction(compiler__tokenize_file_variadic)
var compiler__tokenize_file_parse_tokens = flagrt.NewFunction(compiler__tokenize_file_parse_tokens_variadic)
var flagSet = flagrt.NewSet(flagrt.NewString(" "), flagrt.NewString("\t"), flagrt.NewString("\n"), flagrt.NewString("\r"), flagrt.NewString(","))
var flagSet_1 = flagrt.NewSet(flagrt.NewString("("), flagrt.NewString(")"), flagrt.NewString("["), flagrt.NewString("]"), flagrt.NewString("{"), flagrt.NewString("}"), flagrt.NewString("^"), flagrt.NewString("'"), flagrt.NewString("|"))
var flagKw_token = flagrt.NewKeyword("token")
var flagKw_line = flagrt.NewKeyword("line")
var flagKw_offset = flagrt.NewKeyword("offset")
var flagKw_start_line = flagrt.NewKeyword("start-line")
var flagKw_start_offset = flagrt.NewKeyword("start-offset")
var flagKw_in_string = flagrt.NewKeyword("in-string")
var flagKw_triple = flagrt.NewKeyword("triple")
var flagKw_escaped = flagrt.NewKeyword("escaped")
var flagKw_kind = flagrt.NewKeyword("kind")
var flagKw_lexeme = flagrt.NewKeyword("lexeme")
var flagKw_string = flagrt.NewKeyword("string")
var flagKw_message = flagrt.NewKeyword("message")
var flagKw_col = flagrt.NewKeyword("col")
var flagStr_ = flagrt.NewString("")
var flagStr_unexpected_end_after__ = flagrt.NewString("unexpected end after #")
var flagStr____ = flagrt.NewString("\"\"\"")
var flagStr__ = flagrt.NewString("\"")
var flagStr___ = flagrt.NewString("#{")
var flagStr____1 = flagrt.NewString("#(")
var flagVec = flagrt.NewArray()
