// Generates internal/compiler/tokenizer_flag_gen.go from libraries/compiler/tokenizer.lib.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"

	"flag-lang/internal/compiler"
)

func main() {
	root, err := findRepoRoot()
	if err != nil {
		fail(err)
	}
	lib := filepath.Join(root, "libraries", "compiler", "tokenizer.lib")
	outFile := filepath.Join(root, "internal", "compiler", "tokenizer_flag_gen.go")

	src, err := compiler.CompileProgram(lib)
	if err != nil {
		fail(fmt.Errorf("compile tokenizer.lib: %w", err))
	}

	filtered, err := filterGenerated(src)
	if err != nil {
		fail(err)
	}
	if err := os.WriteFile(outFile, filtered, 0o644); err != nil {
		fail(err)
	}
}

func filterGenerated(src []byte) ([]byte, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "tokenizer.go", src, 0)
	if err != nil {
		return nil, fmt.Errorf("parse generated Go: %w", err)
	}

	keepNames := reachableNames(file)
	kept := make([]ast.Decl, 0, len(file.Decls))
	for _, decl := range file.Decls {
		if gen, ok := decl.(*ast.GenDecl); ok && gen.Tok == token.IMPORT {
			specs := make([]ast.Spec, 0, 1)
			for _, spec := range gen.Specs {
				imp := spec.(*ast.ImportSpec)
				if importPath(imp) == "flag-lang/runtime" {
					specs = append(specs, spec)
				}
			}
			if len(specs) == 0 {
				continue
			}
			gen.Specs = specs
			kept = append(kept, gen)
			continue
		}
		if keepDecl(decl, keepNames) {
			kept = append(kept, decl)
		}
	}
	file.Decls = kept
	file.Name = ast.NewIdent("compiler")
	compiler.RewriteGoPredeclaredShadows(file)

	var buf bytes.Buffer
	buf.WriteString("// Code generated by internal/compiler/tokengen; DO NOT EDIT.\n")
	buf.WriteString("//go:generate go run flag-lang/internal/compiler/tokengen\n\n")
	if err := format.Node(&buf, fset, file); err != nil {
		return nil, fmt.Errorf("format generated Go: %w", err)
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("gofmt generated Go: %w", err)
	}
	return formatted, nil
}

func reachableNames(file *ast.File) map[string]bool {
	declsByName := map[string][]ast.Decl{}
	for _, decl := range file.Decls {
		for _, name := range declNames(decl) {
			declsByName[name] = append(declsByName[name], decl)
		}
	}

	queue := make([]string, 0)
	seen := map[string]bool{}
	enqueue := func(name string) {
		if name == "" || name == "main" || name == "init" || seen[name] {
			return
		}
		if _, ok := declsByName[name]; !ok {
			return
		}
		seen[name] = true
		queue = append(queue, name)
	}

	for _, decl := range file.Decls {
		switch d := decl.(type) {
		case *ast.FuncDecl:
			if d.Recv == nil && seedFunc(d.Name.Name) {
				enqueue(d.Name.Name)
			}
		case *ast.GenDecl:
			if d.Tok == token.TYPE {
				for _, spec := range d.Specs {
					if ts, ok := spec.(*ast.TypeSpec); ok {
						enqueue(ts.Name.Name)
					}
				}
			}
			if d.Tok == token.VAR || d.Tok == token.CONST {
				for _, spec := range d.Specs {
					vs, ok := spec.(*ast.ValueSpec)
					if !ok {
						continue
					}
					for _, ident := range vs.Names {
						if seedVar(ident.Name) {
							enqueue(ident.Name)
						}
					}
				}
			}
		}
	}

	for len(queue) > 0 {
		name := queue[0]
		queue = queue[1:]
		for _, decl := range declsByName[name] {
			ast.Inspect(decl, func(n ast.Node) bool {
				id, ok := n.(*ast.Ident)
				if !ok {
					return true
				}
				enqueue(id.Name)
				return true
			})
		}
	}
	return seen
}

func seedFunc(name string) bool {
	return strings.HasPrefix(name, "compiler__") || strings.HasPrefix(name, "stdlib__")
}

func seedVar(name string) bool {
	return strings.HasPrefix(name, "flag") || strings.HasPrefix(name, "compiler__") || strings.HasPrefix(name, "stdlib__")
}

func keepDecl(decl ast.Decl, keepNames map[string]bool) bool {
	switch d := decl.(type) {
	case *ast.FuncDecl:
		if d.Recv != nil {
			return false
		}
		return keepNames[d.Name.Name]
	case *ast.GenDecl:
		if d.Tok != token.VAR && d.Tok != token.CONST && d.Tok != token.TYPE {
			return false
		}
		for _, name := range declNames(decl) {
			if keepNames[name] {
				return true
			}
		}
		return false
	default:
		return false
	}
}

func declNames(decl ast.Decl) []string {
	switch d := decl.(type) {
	case *ast.FuncDecl:
		if d.Recv != nil {
			return nil
		}
		return []string{d.Name.Name}
	case *ast.GenDecl:
		names := make([]string, 0, len(d.Specs))
		for _, spec := range d.Specs {
			switch s := spec.(type) {
			case *ast.ValueSpec:
				for _, ident := range s.Names {
					names = append(names, ident.Name)
				}
			case *ast.TypeSpec:
				names = append(names, s.Name.Name)
			}
		}
		return names
	default:
		return nil
	}
}

func importPath(imp *ast.ImportSpec) string {
	s := imp.Path.Value
	if len(s) >= 2 && s[0] == '"' && s[len(s)-1] == '"' {
		return s[1 : len(s)-1]
	}
	return s
}

func findRepoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("could not find repository root (go.mod) from %s", dir)
		}
		dir = parent
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "tokengen:", err)
	os.Exit(1)
}
