// Generates internal/repl/runtime_symbols_gen.go from exported runtime identifiers
// so the Yaegi REPL can evaluate the same flagrt.X calls the compiler emits.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	root, err := findRepoRoot()
	if err != nil {
		fail(err)
	}
	runtimeDir := filepath.Join(root, "runtime")
	outFile := filepath.Join(root, "internal", "repl", "runtime_symbols_gen.go")

	names, err := exportedRuntimeNames(runtimeDir)
	if err != nil {
		fail(err)
	}

	src, err := renderSymbols(names)
	if err != nil {
		fail(err)
	}
	if err := os.WriteFile(outFile, src, 0o644); err != nil {
		fail(err)
	}
}

type exportKind int

const (
	exportFunc exportKind = iota
	exportVar
	exportType
)

type export struct {
	name string
	kind exportKind
}

func exportedRuntimeNames(runtimeDir string) ([]export, error) {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, runtimeDir, func(info os.FileInfo) bool {
		name := info.Name()
		return strings.HasSuffix(name, ".go") && !strings.HasSuffix(name, "_test.go")
	}, 0)
	if err != nil {
		return nil, err
	}
	pkg, ok := pkgs["runtime"]
	if !ok {
		return nil, fmt.Errorf("package runtime not found in %s", runtimeDir)
	}

	seen := map[string]exportKind{}
	for _, file := range pkg.Files {
		for _, decl := range file.Decls {
			switch d := decl.(type) {
			case *ast.FuncDecl:
				if d.Recv != nil || d.Name == nil || !d.Name.IsExported() {
					continue
				}
				// Generic functions cannot be registered with reflect.ValueOf.
				if d.Type != nil && d.Type.TypeParams != nil {
					continue
				}
				seen[d.Name.Name] = exportFunc
			case *ast.GenDecl:
				switch d.Tok {
				case token.TYPE:
					for _, spec := range d.Specs {
						ts, ok := spec.(*ast.TypeSpec)
						if !ok || ts.Name == nil || !ts.Name.IsExported() {
							continue
						}
						seen[ts.Name.Name] = exportType
					}
				case token.VAR:
					for _, spec := range d.Specs {
						vs, ok := spec.(*ast.ValueSpec)
						if !ok {
							continue
						}
						for _, name := range vs.Names {
							if name.IsExported() {
								seen[name.Name] = exportVar
							}
						}
					}
				}
			}
		}
	}

	out := make([]export, 0, len(seen))
	for name, kind := range seen {
		out = append(out, export{name: name, kind: kind})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].name < out[j].name })
	return out, nil
}

func renderSymbols(names []export) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Code generated by internal/repl/symbolgen; DO NOT EDIT.\n\n")
	b.WriteString("package repl\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"reflect\"\n\n")
	b.WriteString("\tflagrt \"flag-lang/runtime\"\n")
	b.WriteString(")\n\n")
	b.WriteString("// generatedRuntimeSymbols registers every exported runtime func, var, and\n")
	b.WriteString("// type so Yaegi can evaluate compiler output without a hand-maintained allowlist.\n")
	b.WriteString("func generatedRuntimeSymbols() map[string]reflect.Value {\n")
	b.WriteString("\treturn map[string]reflect.Value{\n")
	for _, item := range names {
		switch item.kind {
		case exportType:
			fmt.Fprintf(&b, "\t\t%q: reflect.ValueOf((*%s)(nil)),\n", item.name, "flagrt."+item.name)
		default:
			fmt.Fprintf(&b, "\t\t%q: reflect.ValueOf(%s),\n", item.name, "flagrt."+item.name)
		}
	}
	b.WriteString("\t}\n")
	b.WriteString("}\n")
	return format.Source(b.Bytes())
}

func findRepoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("could not find repository root (go.mod) from %s", dir)
		}
		dir = parent
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "symbolgen:", err)
	os.Exit(1)
}
