package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

var (
	tokenDefRE    = regexp.MustCompile(`^\(def\s+(token-[a-z0-9-]+)\s+([0-9]+)\s*\)$`)
	parseRecRE    = regexp.MustCompile(`^\(defrecord\s+ParseToken\s+\[([a-z0-9\-\s]+)\]\s*\)$`)
	sourceRecRE   = regexp.MustCompile(`^\(defrecord\s+SourceToken\s+\[([a-z0-9\-\s]+)\]\s*\)$`)
)

type tokenKind struct {
	flagName string
	value    int
}

func main() {
	repoRoot, err := findRepoRoot()
	if err != nil {
		fail(err)
	}
	tokenizerLib := filepath.Join(repoRoot, "libraries", "compiler", "tokenizer.lib")
	outFile := filepath.Join(repoRoot, "internal", "compiler", "parse_token_schema_gen.go")

	sourceFields, parseFields, tokenKinds, err := parseTokenizerSchema(tokenizerLib)
	if err != nil {
		fail(err)
	}

	if len(sourceFields) == 0 {
		fail(fmt.Errorf("SourceToken defrecord not found in %s", filepath.ToSlash(tokenizerLib)))
	}
	if len(parseFields) == 0 {
		fail(fmt.Errorf("ParseToken defrecord not found in %s", filepath.ToSlash(tokenizerLib)))
	}
	if len(tokenKinds) == 0 {
		fail(fmt.Errorf("token-* kind constants not found in %s", filepath.ToSlash(tokenizerLib)))
	}

	src, err := render(sourceFields, parseFields, tokenKinds)
	if err != nil {
		fail(err)
	}
	if err := os.WriteFile(outFile, src, 0o644); err != nil {
		fail(err)
	}
}

func findRepoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("could not find repository root (go.mod) from %s", dir)
		}
		dir = parent
	}
}

func parseTokenizerSchema(path string) ([]string, []string, []tokenKind, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, nil, nil, err
	}
	defer f.Close()

	var sourceFields []string
	var parseFields []string
	kinds := make([]tokenKind, 0, 16)

	s := bufio.NewScanner(f)
	for s.Scan() {
		line := strings.TrimSpace(s.Text())
		if m := sourceRecRE.FindStringSubmatch(line); len(m) == 2 {
			sourceFields = sourceFields[:0]
			sourceFields = append(sourceFields, strings.Fields(strings.TrimSpace(m[1]))...)
			continue
		}
		if m := parseRecRE.FindStringSubmatch(line); len(m) == 2 {
			parseFields = parseFields[:0]
			parseFields = append(parseFields, strings.Fields(strings.TrimSpace(m[1]))...)
			continue
		}
		if m := tokenDefRE.FindStringSubmatch(line); len(m) == 3 {
			n, err := strconv.Atoi(m[2])
			if err != nil {
				return nil, nil, nil, fmt.Errorf("parse token kind value for %s: %w", m[1], err)
			}
			kinds = append(kinds, tokenKind{flagName: m[1], value: n})
		}
	}
	if err := s.Err(); err != nil {
		return nil, nil, nil, err
	}
	return sourceFields, parseFields, kinds, nil
}

func render(sourceFields, parseFields []string, kinds []tokenKind) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Code generated by internal/compiler/tokenschemagen; DO NOT EDIT.\n\n")
	b.WriteString("package compiler\n\n")
	b.WriteString("//go:generate go run flag-lang/internal/compiler/tokenschemagen\n\n")
	b.WriteString("type ParseTokenKind int\n\n")
	b.WriteString("const (\n")
	for _, kind := range kinds {
		fmt.Fprintf(&b, "\t%-20s ParseTokenKind = %d\n", tokenKindName(kind.flagName), kind.value)
	}
	b.WriteString(")\n\n")
	b.WriteString("type SourceToken struct {\n")
	for _, field := range sourceFields {
		fmt.Fprintf(&b, "\t%-7s %s\n", structFieldName(field), fieldType(field))
	}
	b.WriteString("}\n\n")

	b.WriteString("type ParseToken struct {\n")
	for _, field := range parseFields {
		fmt.Fprintf(&b, "\t%-7s %s\n", structFieldName(field), fieldType(field))
	}
	b.WriteString("}\n")

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated schema: %w", err)
	}
	return formatted, nil
}

func tokenKindName(flagName string) string {
	name := strings.TrimPrefix(flagName, "token-")
	parts := strings.Split(name, "-")
	var b strings.Builder
	b.WriteString("Token")
	for _, part := range parts {
		if part == "eof" {
			b.WriteString("EOF")
			continue
		}
		if part == "" {
			continue
		}
		b.WriteString(strings.ToUpper(part[:1]))
		b.WriteString(part[1:])
	}
	return b.String()
}

func structFieldName(flagField string) string {
	parts := strings.Split(flagField, "-")
	var b strings.Builder
	for _, part := range parts {
		if part == "eof" {
			b.WriteString("EOF")
			continue
		}
		if part == "" {
			continue
		}
		b.WriteString(strings.ToUpper(part[:1]))
		b.WriteString(part[1:])
	}
	return b.String()
}

func fieldType(flagField string) string {
	switch flagField {
	case "kind":
		return "ParseTokenKind"
	case "line", "col", "offset":
		return "int"
	default:
		return "string"
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "tokenschemagen:", err)
	os.Exit(1)
}
