package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

var tokenDefRE = regexp.MustCompile(`^\(def\s+(token-[a-z0-9-]+)\s+([0-9]+)\s*\)$`)

type tokenKind struct {
	flagName string
	value    int
}

func main() {
	repoRoot, err := findRepoRoot()
	if err != nil {
		fail(err)
	}
	tokenizerLib := filepath.Join(repoRoot, "libraries", "compiler", "tokenizer.lib")
	outFile := filepath.Join(repoRoot, "internal", "compiler", "parse_token_schema_gen.go")

	tokenKinds, err := parseTokenizerSchema(tokenizerLib)
	if err != nil {
		fail(err)
	}
	if len(tokenKinds) == 0 {
		fail(fmt.Errorf("token-* kind constants not found in %s", filepath.ToSlash(tokenizerLib)))
	}

	src, err := render(tokenKinds)
	if err != nil {
		fail(err)
	}
	if err := os.WriteFile(outFile, src, 0o644); err != nil {
		fail(err)
	}
}

func findRepoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("could not find repository root (go.mod) from %s", dir)
		}
		dir = parent
	}
}

func parseTokenizerSchema(path string) ([]tokenKind, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	kinds := make([]tokenKind, 0, 16)
	s := bufio.NewScanner(f)
	for s.Scan() {
		line := strings.TrimSpace(s.Text())
		if m := tokenDefRE.FindStringSubmatch(line); len(m) == 3 {
			n, err := strconv.Atoi(m[2])
			if err != nil {
				return nil, fmt.Errorf("parse token kind value for %s: %w", m[1], err)
			}
			kinds = append(kinds, tokenKind{flagName: m[1], value: n})
		}
	}
	if err := s.Err(); err != nil {
		return nil, err
	}
	return kinds, nil
}

func render(kinds []tokenKind) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Code generated by internal/compiler/tokenschemagen; DO NOT EDIT.\n\n")
	b.WriteString("package compiler\n\n")
	b.WriteString("//go:generate go run flag-lang/internal/compiler/tokenschemagen\n\n")
	b.WriteString("type ParseTokenKind int\n\n")
	b.WriteString("const (\n")
	for _, kind := range kinds {
		fmt.Fprintf(&b, "\t%-20s ParseTokenKind = %d\n", tokenKindName(kind.flagName), kind.value)
	}
	b.WriteString(")\n")

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated schema: %w", err)
	}
	return formatted, nil
}

func tokenKindName(flagName string) string {
	name := strings.TrimPrefix(flagName, "token-")
	parts := strings.Split(name, "-")
	var b strings.Builder
	b.WriteString("Token")
	for _, part := range parts {
		if part == "eof" {
			b.WriteString("EOF")
			continue
		}
		if part == "" {
			continue
		}
		b.WriteString(strings.ToUpper(part[:1]))
		b.WriteString(part[1:])
	}
	return b.String()
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "tokenschemagen:", err)
	os.Exit(1)
}
