// Generates internal/compiler/build_ast_flag_gen.go from libraries/compiler/build-ast.lib.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"

	"flag-lang/internal/compiler"
)

func main() {
	root, err := findRepoRoot()
	if err != nil {
		fail(err)
	}
	lib := filepath.Join(root, "libraries", "compiler", "build-ast.lib")
	outFile := filepath.Join(root, "internal", "compiler", "build_ast_flag_gen.go")
	existingFile := filepath.Join(root, "internal", "compiler", "tokenizer_flag_gen.go")

	src, err := compiler.CompileProgram(lib)
	if err != nil {
		fail(fmt.Errorf("compile build-ast.lib: %w", err))
	}

	existing, err := topLevelNames(existingFile)
	if err != nil {
		fail(err)
	}

	filtered, err := filterGenerated(src, existing)
	if err != nil {
		fail(err)
	}
	if err := os.WriteFile(outFile, filtered, 0o644); err != nil {
		fail(err)
	}
}

func filterGenerated(src []byte, existing map[string]bool) ([]byte, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "build-ast.go", src, 0)
	if err != nil {
		return nil, fmt.Errorf("parse generated Go: %w", err)
	}

	kept := make([]ast.Decl, 0, len(file.Decls))
	for _, decl := range file.Decls {
		if gen, ok := decl.(*ast.GenDecl); ok && gen.Tok == token.IMPORT {
			specs := make([]ast.Spec, 0, 1)
			for _, spec := range gen.Specs {
				imp := spec.(*ast.ImportSpec)
				if importPath(imp) == "flag-lang/runtime" {
					specs = append(specs, spec)
				}
			}
			if len(specs) == 0 {
				continue
			}
			gen.Specs = specs
			kept = append(kept, gen)
			continue
		}
		if keepDecl(decl, existing) {
			kept = append(kept, decl)
		}
	}
	file.Decls = kept
	file.Name = ast.NewIdent("compiler")
	prefixFlagIdents(file)

	var buf bytes.Buffer
	buf.WriteString("// Code generated by internal/compiler/astgen; DO NOT EDIT.\n\n")
	if err := format.Node(&buf, fset, file); err != nil {
		return nil, fmt.Errorf("format generated Go: %w", err)
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("gofmt generated Go: %w", err)
	}
	return formatted, nil
}

func keepDecl(decl ast.Decl, existing map[string]bool) bool {
	switch d := decl.(type) {
	case *ast.FuncDecl:
		if d.Recv != nil {
			return false
		}
		return keepIdent(d.Name.Name, existing) && strings.HasPrefix(d.Name.Name, "compiler__")
	case *ast.GenDecl:
		if d.Tok != token.VAR && d.Tok != token.CONST && d.Tok != token.TYPE {
			return false
		}
		for _, spec := range d.Specs {
			switch s := spec.(type) {
			case *ast.ValueSpec:
				for _, ident := range s.Names {
					if !keepVar(ident.Name, existing, s) {
						return false
					}
				}
			case *ast.TypeSpec:
				if !keepIdent(s.Name.Name, existing) {
					return false
				}
			default:
				return false
			}
		}
		return len(d.Specs) > 0
	default:
		return false
	}
}

func keepVar(name string, existing map[string]bool, spec *ast.ValueSpec) bool {
	if name == "main" || name == "init" {
		return false
	}
	if strings.HasPrefix(name, "flag") {
		return true
	}
	if existing[name] {
		return false
	}
	if strings.HasPrefix(name, "compiler__") {
		return true
	}
	if strings.HasPrefix(name, "async__") {
		return valueSpecCallsGoBind(spec)
	}
	return false
}

func keepIdent(name string, existing map[string]bool) bool {
	return !existing[name] && name != "main" && name != "init"
}

func prefixFlagIdents(file *ast.File) {
	ast.Inspect(file, func(n ast.Node) bool {
		id, ok := n.(*ast.Ident)
		if !ok {
			return true
		}
		if strings.HasPrefix(id.Name, "flag") && id.Name != "flagrt" {
			id.Name = "ast" + id.Name
		}
		return true
	})
}

func valueSpecCallsGoBind(spec *ast.ValueSpec) bool {
	for _, value := range spec.Values {
		if strings.Contains(exprString(value), "GoBind_") {
			return true
		}
	}
	return false
}

func exprString(e ast.Expr) string {
	var buf bytes.Buffer
	if err := format.Node(&buf, token.NewFileSet(), e); err != nil {
		return ""
	}
	return buf.String()
}

func declNames(decl ast.Decl) []string {
	switch d := decl.(type) {
	case *ast.FuncDecl:
		if d.Recv != nil {
			return nil
		}
		return []string{d.Name.Name}
	case *ast.GenDecl:
		names := make([]string, 0, len(d.Specs))
		for _, spec := range d.Specs {
			switch s := spec.(type) {
			case *ast.ValueSpec:
				for _, ident := range s.Names {
					names = append(names, ident.Name)
				}
			case *ast.TypeSpec:
				names = append(names, s.Name.Name)
			}
		}
		return names
	default:
		return nil
	}
}

func topLevelNames(path string) (map[string]bool, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, path, nil, 0)
	if err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	out := map[string]bool{}
	for _, decl := range file.Decls {
		for _, name := range declNames(decl) {
			out[name] = true
		}
	}
	return out, nil
}

func importPath(imp *ast.ImportSpec) string {
	s := imp.Path.Value
	if len(s) >= 2 && s[0] == '"' && s[len(s)-1] == '"' {
		return s[1 : len(s)-1]
	}
	return s
}

func findRepoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("could not find repository root (go.mod) from %s", dir)
		}
		dir = parent
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "astgen:", err)
	os.Exit(1)
}
